//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDMOVIE_H
#define UIFLOWWNDMOVIE_H

#include "UIFramework.h"

extern VControl UIFlowWndMovieCtrl;//Panel type 

extern VControl UIFlowWndMovie_Static_cameraCtrl;//Static type 

extern VControl UIFlowWndMovie_Status_aeCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_ae_ICON_EV_M2P0,
UIFlowWndMovie_Status_ae_ICON_EV_M1P6,
UIFlowWndMovie_Status_ae_ICON_EV_M1P3,
UIFlowWndMovie_Status_ae_ICON_EV_M1P0,
UIFlowWndMovie_Status_ae_ICON_EV_M0P6,
UIFlowWndMovie_Status_ae_ICON_EV_M0P3,
UIFlowWndMovie_Status_ae_ICON_EV_P0P0,
UIFlowWndMovie_Status_ae_ICON_EV_P0P3,
UIFlowWndMovie_Status_ae_ICON_EV_P0P6,
UIFlowWndMovie_Status_ae_ICON_EV_P1P0,
UIFlowWndMovie_Status_ae_ICON_EV_P1P3,
UIFlowWndMovie_Status_ae_ICON_EV_P1P6,
UIFlowWndMovie_Status_ae_ICON_EV_P2P0,
UIFlowWndMovie_Status_ae_MAX
}UIFlowWndMovie_Status_ae_Setting;

extern VControl UIFlowWndMovie_Status_awbCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_awb_ICON_WB_AUTO,
UIFlowWndMovie_Status_awb_ICON_WB_CLOUDY,
UIFlowWndMovie_Status_awb_ICON_WB_DAYLIGHT,
UIFlowWndMovie_Status_awb_ICON_WB_FLUORESCENT,
UIFlowWndMovie_Status_awb_ICON_WB_TUNGSTEN,
UIFlowWndMovie_Status_awb_MAX
}UIFlowWndMovie_Status_awb_Setting;

extern VControl UIFlowWndMovie_Status_batteryCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Status_battery_ICON_BATTERY_FULL,
UIFlowWndMovie_Status_battery_ICON_BATTERY_MED,
UIFlowWndMovie_Status_battery_ICON_BATTERY_LOW,
UIFlowWndMovie_Status_battery_ICON_BATTERY_EMPTY,
UIFlowWndMovie_Status_battery_ICON_BATTERY_ZERO,
UIFlowWndMovie_Status_battery_MAX
}UIFlowWndMovie_Status_battery_Setting;

extern VControl UIFlowWndMovie_PanelCtrl;//Panel type 

extern VControl UIFlowWndMovie_Static_timeCtrl;//Static type 

extern VControl UIFlowWndMovie_Static_maxtimeCtrl;//Static type 

extern VControl UIFlowWndMovie_Static_resolutionCtrl;//Static type 

extern VControl UIFlowWndMovie_Zoom_StaticCtrl;//Static type 

extern VControl UIFlowWnd_HistoCtrl;//Tab type 

typedef enum
{
UIFlowWnd_Histo_MAX
}UIFlowWnd_Histo_Setting;

extern VControl UIFlowWndMovie_YMD_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_HMS_StaticCtrl;//Static type 

extern VControl UIFlowWndMovie_Macro_StatusCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_Macro_Status_ICON_MACRO,
UIFlowWndMovie_Macro_Status_ICONID_NULL,
UIFlowWndMovie_Macro_Status_MAX
}UIFlowWndMovie_Macro_Status_Setting;

extern VControl UIFlowWndMovie_StatusICN_StorageCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_StatusICN_Storage_ICON_INTERNAL_FLASH,
UIFlowWndMovie_StatusICN_Storage_ICON_SD_CARD,
UIFlowWndMovie_StatusICN_Storage_MAX
}UIFlowWndMovie_StatusICN_Storage_Setting;

extern VControl UIFlowWndMovie_StaticIcon_PIMCtrl;//Static type 

extern VControl UIFlowWndMovie_StatusIcon_DISCtrl;//Status type 

typedef enum
{
UIFlowWndMovie_StatusIcon_DIS_ICONID_NULL,
UIFlowWndMovie_StatusIcon_DIS_ICON_SHAKE_ON,
UIFlowWndMovie_StatusIcon_DIS_MAX
}UIFlowWndMovie_StatusIcon_DIS_Setting;

#endif
