//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupLanguageRes.c"
#include "UIMenuWndSetupLanguage.h"
//#NT#2009/08/19#Chris Chung -begin
#include "UISystemObj.h"
#include "PrimaryTsk.h"
#include "UIMenuWndPhotoStill.h"
#include "UIMenuWndMovieVideo.h"
#include "UIMenuWndPlayback.h"
#include "UIMenuSetupSettings.h"
//#NT#2009/08/19#Chris Chung -end
//---------------------UIMenuWndSetupLanguageCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLanguage)
CTRL_LIST_ITEM(UIMenuWndSetupLanguage_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetupLanguageCtrl Event---------------------------
INT32 UIMenuWndSetupLanguage_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLanguage)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupLanguage_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupLanguage_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupLanguage_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupLanguage_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupLanguage_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupLanguage_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/19#Chris Chung -begin
    UxList_SetData(&UIMenuWndSetupLanguage_List_TextCtrl, LST_CURITM, Get_LanguageIndex());
    //#NT#2009/08/19#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupLanguageCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/17#Chris Chung -begin
    switch(Primary_GetCurrentMode())
    {
    case PRIMARY_MODE_MOVIE:
        Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
        break;
    case PRIMARY_MODE_PHOTO:
        Ux_CloseWindow(&UIMenuWndPhotoStillCtrl,0);
        break;
    case PRIMARY_MODE_PLAYBACK:
        Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);
        break;
    }
    //#NT#2009/08/17#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/17#Chris Chung -begin
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    //#NT#2009/08/17#Chris Chung -end
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupLanguage_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLanguage_Panel)
CTRL_LIST_ITEM(UIMenuWndSetupLanguage_List_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupLanguage_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupLanguage_Panel)
EVENT_END

//----------------------UIMenuWndSetupLanguage_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupLanguage_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLanguage_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLanguage_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupLanguage_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupLanguage_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupLanguage_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupLanguage_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLanguage_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 ui32CurrListItem;

    ui32CurrListItem = UxList_GetData(pCtrl, LST_CURITM);
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_LANGUAGE,1,ui32CurrListItem);
    Ux_CloseWindow(&UIMenuWndSetupLanguageCtrl, 0);
    return NVTEVT_CONSUME;
}
