//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPVERSION_H
#define UIMENUWNDSETUPVERSION_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupVersionCtrl;//Panel type 

extern VControl UIMenuWndSetupVersion_PanelCtrl;//Panel type 

extern VControl UIMenuWndSetupVersion_StaticTXT_FwVerCtrl;//Static type 

#endif
