//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPTVMODE_H
#define UIMENUWNDSETUPTVMODE_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupTVModeCtrl;//Panel type 

extern VControl UIMenuWndSetupTVMode_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndSetupTVMode_List_Text_STRID_TV_NTSC,
UIMenuWndSetupTVMode_List_Text_STRID_TV_PAL,
UIMenuWndSetupTVMode_List_Text_MAX
}UIMenuWndSetupTVMode_List_Text_Setting;

#endif
