//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPFREQUENCY_H
#define UIMENUWNDSETUPFREQUENCY_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupFrequencyCtrl;//Panel type 

extern VControl UIMenuWndSetupFrequency_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndSetupFrequency_List_Text_STRID_50HZ,
UIMenuWndSetupFrequency_List_Text_STRID_60HZ,
UIMenuWndSetupFrequency_List_Text_MAX
}UIMenuWndSetupFrequency_List_Text_Setting;

#endif
