//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoStillRes.c"
#include "UIMenuWndPhotoStill.h"
//---------------------UIMenuWndPhotoStillCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill)
CTRL_LIST_ITEM(PhotoMenuBackground)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_Item)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_PageNum_Static)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStillCtrl Event---------------------------
INT32 UIMenuWndPhotoStill_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoStill)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoStill_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoStill_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPhotoStill_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoStill_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPhotoStill_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPhotoStill_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoStill_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPhotoStill_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoStill_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------PhotoMenuBackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(PhotoMenuBackground)
CTRL_LIST_END

//----------------------PhotoMenuBackgroundCtrl Event---------------------------
EVENT_BEGIN(PhotoMenuBackground)
EVENT_END

//---------------------UIMenuWndPhotoStill_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_TitleBar)
EVENT_END

//----------------------UIMenuWndPhotoStill_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_TitleName)
EVENT_END

//---------------------UIMenuWndPhotoStill_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_ReturnTips)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_LDRTips)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_LUDRTips)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_LUDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_TipsBar)
EVENT_END

//----------------------UIMenuWndPhotoStill_ReturnTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_ReturnTips)
EVENT_END

//---------------------UIMenuWndPhotoStill_LDRTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_LDRTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_LDRTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_LDRTips)
EVENT_END

//---------------------UIMenuWndPhotoStill_LUDRTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_LUDRTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_LUDRTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_LUDRTips)
EVENT_END

//---------------------UIMenuWndPhotoStill_LUDOKTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_LUDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_LUDOKTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_LUDOKTips)
EVENT_END

//----------------------UIMenuWndPhotoStill_ItemCtrl Event---------------------------
INT32 UIMenuWndPhotoStill_Item_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoStill_Item)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoStill_Item_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoStill_Item_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoStill_Item_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPhotoStill_Item_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoStill_Item_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoStill_Item_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPhotoStill_PageNum_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_PageNum_Static)
EVENT_END

