//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoColorRes.c"
#include "UIMenuWndPhotoColor.h"
#include "UIMenuWndPhotoStill.h"
#include "UIMenuWndMovieVideo.h"
#include "UIPhotoObj.h"
#include "UISystemObj.h"
#include "PrimaryTsk.h"
#include "KeyScanTsk.h"

static UINT32 g_uiColorValue = 0; // for Color setting backup

//---------------------UIMenuWndPhotoColorCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoColor)
CTRL_LIST_ITEM(UIMenuWndPhotoColor_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPhotoColorCtrl Event---------------------------
INT32 UIMenuWndPhotoColor_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoColor)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoColor_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoColor_OnClose)
EVENT_END

INT32 UIMenuWndPhotoColor_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_uiColorValue = Get_ColorIndex(); // backup Color setting
    UxMenu_SetData(&UIMenuWndPhotoColor_MenuCtrl,MNU_CURITM,g_uiColorValue);
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_RedrawAllWind();

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_EXE_COLOR,1,g_uiColorValue); // recall Color setting
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoColor_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoColor_Panel)
CTRL_LIST_ITEM(UIMenuWndPhotoColor_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoColor_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoColor_Panel)
EVENT_END

//----------------------UIMenuWndPhotoColor_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoColor_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_Menu_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_Menu_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoColor_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoColor_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoColor_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoColor_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoColor_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPhotoColor_Menu_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPhotoColor_Menu_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoColor_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  value;
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    value = UxMenu_GetData(pCtrl,MNU_CURITM);
    Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_EXE_COLOR,1,value);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  value;
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    value = UxMenu_GetData(pCtrl,MNU_CURITM);
    Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_EXE_COLOR,1,value);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndPhotoColorCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_uiColorValue = UxMenu_GetData(pCtrl,MNU_CURITM); // change Color setting
    Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_EXE_COLOR,1,g_uiColorValue);
    Ux_CloseWindow(&UIMenuWndPhotoColorCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_Menu_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(Primary_GetCurrentMode())
    {
    case PRIMARY_MODE_PHOTO:
        Ux_CloseWindow(&UIMenuWndPhotoStillCtrl,0); // close photo still menu
        break;
    case PRIMARY_MODE_MOVIE:
        Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0); // close movie still menu
        break;
    default:
        Ux_CloseWindow(pCtrl,0); // close current window
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_Menu_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
