//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOISO_H
#define UIMENUWNDPHOTOISO_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoISOCtrl;//Panel type 

extern VControl UIMenuWndPhotoISO_PanelCtrl;//Panel type 

extern VControl UIMenuWndPhotoISO_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoISO_Menu_STRID_AUTO,
UIMenuWndPhotoISO_Menu_STRID_ISO100,
UIMenuWndPhotoISO_Menu_STRID_ISO200,
UIMenuWndPhotoISO_Menu_STRID_ISO400,
UIMenuWndPhotoISO_Menu_MAX
}UIMenuWndPhotoISO_Menu_Setting;

#endif
