//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOCOMPRESSION_H
#define UIMENUWNDPHOTOCOMPRESSION_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoCompressionCtrl;//Panel type 

extern VControl UIMenuWndPhotoCompression_PanelCtrl;//Panel type 

extern VControl UIMenuWndPhotoCompression_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoCompression_Menu_STRID_SUPER,
UIMenuWndPhotoCompression_Menu_STRID_FINE,
UIMenuWndPhotoCompression_Menu_STRID_NORMAL,
UIMenuWndPhotoCompression_Menu_MAX
}UIMenuWndPhotoCompression_Menu_Setting;

#endif
