//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTODATESTAMP_H
#define UIMENUWNDPHOTODATESTAMP_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoDateStampCtrl;//Panel type 

extern VControl UIMenuWndPhotoDateStamp_PanelCtrl;//Panel type 

extern VControl UIMenuWndPhotoDateStamp_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoDateStamp_Menu_STRID_OFF,
UIMenuWndPhotoDateStamp_Menu_STRID_DATE,
UIMenuWndPhotoDateStamp_Menu_STRID_DATE_TIME,
UIMenuWndPhotoDateStamp_Menu_MAX
}UIMenuWndPhotoDateStamp_Menu_Setting;

#endif
