//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOEV_H
#define UIMENUWNDPHOTOEV_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoEVCtrl;//Panel type 

extern VControl UIMenuWndPhotoEV_PanelCtrl;//Panel type 

extern VControl UIMenuWndPhotoEV_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoEV_Menu_STRID_EV_P2P0,
UIMenuWndPhotoEV_Menu_STRID_EV_P1P6,
UIMenuWndPhotoEV_Menu_STRID_EV_P1P3,
UIMenuWndPhotoEV_Menu_STRID_EV_P1P0,
UIMenuWndPhotoEV_Menu_STRID_EV_P0P6,
UIMenuWndPhotoEV_Menu_STRID_EV_P0P3,
UIMenuWndPhotoEV_Menu_STRID_EV_P0P0,
UIMenuWndPhotoEV_Menu_STRID_EV_M0P3,
UIMenuWndPhotoEV_Menu_STRID_EV_M0P6,
UIMenuWndPhotoEV_Menu_STRID_EV_M1P0,
UIMenuWndPhotoEV_Menu_STRID_EV_M1P3,
UIMenuWndPhotoEV_Menu_STRID_EV_M1P6,
UIMenuWndPhotoEV_Menu_STRID_EV_M2P0,
UIMenuWndPhotoEV_Menu_MAX
}UIMenuWndPhotoEV_Menu_Setting;

#endif
