//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOANTISHA_H
#define UIMENUWNDPHOTOANTISHA_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoAntiShaCtrl;//Panel type 

extern VControl UIMenuWndPhotoAntiSha_PanelCtrl;//Panel type 

extern VControl UIMenuWndPhotoAntiSha_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoAntiSha_Menu_STRID_OFF,
UIMenuWndPhotoAntiSha_Menu_STRID_ON,
UIMenuWndPhotoAntiSha_Menu_MAX
}UIMenuWndPhotoAntiSha_Menu_Setting;

#endif
