/*

Abstract:
   AAC Decoder API

*/
#ifndef _AACD_H_
#define _AACD_H_


typedef struct AudioProperty
{
  int SampleRate;
  int BitRate;
  int Channel;

  /* These are specific for MPEG-1 Decoder. */
  unsigned char *start;
  unsigned int length;

  /* 
  1. It is used by Codec. It determines that the encoded or decoded frame will have header or not.
  2. Encoder : one  => encode with header.
               zero => encode without header.
  3. Decoder : one  => decode with header.
               zero => decode without header.
  */
  int CodingType;
  
}AudioProperty;


/*
   Memory Block Information.
*/
typedef struct MemBlkInfo
{
  unsigned int align;
  unsigned int size;     /* In Bytes */
  void *ptr;
}MemBlkInfo;


typedef enum AudioError
{
  AUDIO_ERROR_NONE          = 0x0000,   /* no error */
  AUDIO_ERROR_UNKNOWN       = 0x0001,   /* unknown error */
  AUDIO_ERROR_NONCONFIGURE  = 0x0002,   /* not yet configure the decoder */
  AUDIO_ERROR_CONFIGUREFAIL = 0x0003,   /* fail to configure the decoder */
  AUDIO_ERROR_RUNFAIL       = 0x0004    /* fail to run the decoder */
}AudioError;


/*
  1. Allocate the private memory space which is used by AAC Decoder.
*/
void * AACD_Create(void (*CreateObj)(MemBlkInfo *, int));


/*
  1. Delete the private data which is used by AAC Decoder.
*/
void AACD_Delete(void *object, void (*DeleteObj)(MemBlkInfo *, int));


/*
  1. Configure the property which is used by AAC Decoder.
*/
AudioError AACD_Configure(void *object, AudioProperty *property);


/*
  1. Decode One Frame
  2. Frame content: Header + Raw Data
*/
AudioError AACD_Run(void *object, unsigned char *inbuf, short *outbuf);


/*
  1. Return value: Bitstrem Length is returned by decoder when decoding one Frame. (Bytes)
  2. It gives the information about one encoded frame size.
  3. It is used by input buffer, one encoded frame size.
*/
unsigned int AACD_GetBitstreamLength(void *object);


/*
  1. Return value: Data Length is returned by decoder when decoding one Frame (Bytes)
  2. It gives the information about the size of raw data when decoding one frame.
  3. It is used by output buffer, total samples are generated by decoding one frame.
*/
unsigned int AACD_GetDataLength(void *object);


unsigned int AACD_GetChannel(void *object);

unsigned int AACD_GetSampleRate(void *object);

unsigned int AACD_GetBitRate(void *object);

extern void AACDCreateObj(MemBlkInfo *memblk, int num);


#endif
