//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupVersionRes.c"
#include "UIMenuWndSetupVersion.h"
//#include "UIMenuWndPhotoStill.h"
#include "UIMenuWndMovieVideo.h"
#include "UIMenuWndPlayback.h"
#include "UISystemStatusSettings.h"
#include "UISystemObj.h"
#include "PrimaryTsk.h"
#include "KeyScanTsk.h"

//---------------------UIMenuWndSetupVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersionCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupVersion_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupVersion_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupVersion_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupVersion_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupVersion_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxStatic_SetData(&UIMenuWndSetupVersion_StaticTXT_FwVerCtrl,STATIC_VALUE,Txt_Pointer(GetVersionString()));
    UxCtrl_SetShow(&UIMenuWndSetupVersion_StaticTXT_FwVerCtrl,TRUE);

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupVersionCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndSetupVersionCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(Primary_GetCurrentMode())
    {
    case PRIMARY_MODE_PHOTO:
//        Ux_CloseWindow(&UIMenuWndPhotoStillCtrl,0);
        break;
    case PRIMARY_MODE_MOVIE:
        Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
        break;
    case PRIMARY_MODE_PLAYBACK:
        Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);
        break;
    default:
        Ux_CloseWindow(pCtrl,0); // close current window
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupVersion_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion_Panel)
CTRL_LIST_ITEM(UIMenuWndSetupVersion_StaticTXT_FwVer)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersion_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupVersion_Panel)
EVENT_END

//----------------------UIMenuWndSetupVersion_StaticTXT_FwVerCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupVersion_StaticTXT_FwVer)
EVENT_END

