//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupDelayPowerOffRes.c"
#include "UIMenuWndSetupDelayPowerOff.h"
//#NT#2009/08/19#Chris Chung -begin
#include "UISystemObj.h"
#include "PrimaryTsk.h"
//#include "UIMenuWndPhotoStill.h"
#include "UIMenuWndMovieVideo.h"
#include "UIMenuWndPlayback.h"
#include "UIMenuSetupSettings.h"
//#NT#2009/08/19#Chris Chung -end
//---------------------UIMenuWndSetupDelayPowerOffCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDelayPowerOff)
CTRL_LIST_ITEM(UIMenuWndSetupDelayPowerOff_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetupDelayPowerOffCtrl Event---------------------------
INT32 UIMenuWndSetupDelayPowerOff_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDelayPowerOff)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupDelayPowerOff_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupDelayPowerOff_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupDelayPowerOff_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupDelayPowerOff_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupDelayPowerOff_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupDelayPowerOff_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/19#Chris Chung -begin
    UxList_SetData(&UIMenuWndSetupDelayPowerOff_List_TextCtrl, LST_CURITM, Get_DelayPowerOffIndex());
    //#NT#2009/08/19#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
   //#NT#2009/08/17#Chris Chung -begin
    switch(Primary_GetCurrentMode())
    {
    case PRIMARY_MODE_MOVIE:
        Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
        break;
    case PRIMARY_MODE_PHOTO:
//        Ux_CloseWindow(&UIMenuWndPhotoStillCtrl,0);
        break;
    case PRIMARY_MODE_PLAYBACK:
        Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);
        break;
    }
    //#NT#2009/08/17#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/17#Chris Chung -begin
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    //#NT#2009/08/17#Chris Chung -end
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupDelayPowerOff_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDelayPowerOff_Panel)
CTRL_LIST_ITEM(UIMenuWndSetupDelayPowerOff_List_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupDelayPowerOff_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDelayPowerOff_Panel)
EVENT_END

//----------------------UIMenuWndSetupDelayPowerOff_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDelayPowerOff_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupDelayPowerOff_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupDelayPowerOff_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupDelayPowerOff_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 ui32CurrListItem;

    ui32CurrListItem = UxList_GetData(pCtrl, LST_CURITM);
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_DELAYPOWEROFF,1,ui32CurrListItem);
    Ux_CloseWindow(&UIMenuWndSetupDelayPowerOffCtrl, 0);

    return NVTEVT_CONSUME;
}
