//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupRes.c"
#include "UIMenuWndSetup.h"
//#NT#2009/09/11#KS Hung -begin
#include "PrimaryTsk.h"
#include "UIMenuWndMovieResolution.h"
#include "UIMenuWndPhotoStill.h"
#include "UIMenuWndMovieVideo.h"
#include "UIMenuWndPlayback.h"
#include "debug.h"
#include "UIMenuWndSetupDateTime.h"
#include "UIMenuWndSetupAutoPowerOff.h"
#include "UIMenuWndSetupBeepSound.h"
#include "UIMenuWndSetupLanguage.h"
#include "UIMenuWndSetupTVMode.h"
#include "UIMenuWndSetupFormat.h"
#include "UIMenuWndSetupDefaultSetting.h"
#include "UIMenuWndSetupFrequency.h"
#include "UIMenuWndSetupFormat.h"
#include "UISystemObj.h"
#include "UIMenuWndSetupVersion.h"
#include "UIMenuWndSetupLcdOff.h"
#include "UIMenuWndPhotoAntiSha.h"
#include "UIMenuWndSetupImageRotate.h"
#include "UIMenuWndSetupDelayPowerOff.h"

//#NT#2009/09/11#KS Hung -end
//---------------------UIMenuWndSetupCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup)
CTRL_LIST_ITEM(UIMenuWndSetup_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_End_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Setup_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupCtrl Event---------------------------
INT32 UIMenuWndSetup_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetup)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetup_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetup_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndSetup_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetup_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetup_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetup_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetup_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetup_OnKeyMode)
EVENT_END

static UINT8 BottomBar_Buf[20];
static BOOL bUIMenuWndSetup_Setup_MenuCtrl_rx_event = FALSE;
static UINT32 gOldTitle_Mode = UIMenuWndSetup_Title_Old_Status_ICON_MENU_STILL_OFF;

INT32 UIMenuWndSetup_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 item,page,total_page;

    UxState_SetData(&UIMenuWndSetup_Title_Mode_StatusCtrl,STATE_CURITEM,UIMenuWndSetup_Title_Mode_Status_STRID_SETUP);

    switch(Primary_GetCurrentMode())
    {
        case PRIMARY_MODE_PHOTO:
            UxState_SetData(&UIMenuWndSetup_Title_Old_StatusCtrl,STATE_CURITEM,UIMenuWndSetup_Title_Old_Status_ICON_MENU_STILL_OFF);
            gOldTitle_Mode = UIMenuWndSetup_Title_Old_Status_ICON_MENU_STILL_OFF;
            break;
        case PRIMARY_MODE_PLAYBACK:
            UxState_SetData(&UIMenuWndSetup_Title_Old_StatusCtrl,STATE_CURITEM,UIMenuWndSetup_Title_Old_Status_ICON_MENU_PLAYBACK_OFF);
            gOldTitle_Mode = UIMenuWndSetup_Title_Old_Status_ICON_MENU_PLAYBACK_OFF;
            break;
        case PRIMARY_MODE_MOVIE:
            UxState_SetData(&UIMenuWndSetup_Title_Old_StatusCtrl,STATE_CURITEM,UIMenuWndSetup_Title_Old_Status_ICON_MENU_VIDEO_OFF);
            gOldTitle_Mode = UIMenuWndSetup_Title_Old_Status_ICON_MENU_VIDEO_OFF;
            break;
        default:
            UxState_SetData(&UIMenuWndSetup_Title_Old_StatusCtrl,STATE_CURITEM,UIMenuWndSetup_Title_Old_Status_ICON_MENU_STILL_OFF);
            gOldTitle_Mode = UIMenuWndSetup_Title_Old_Status_ICON_MENU_STILL_OFF;
            break;
    }

    UxMenu_SetData(&UIMenuWndSetup_Setup_MenuCtrl,MNU_CURITM,0);

    item = UxMenu_GetData(&UIMenuWndSetup_Setup_MenuCtrl,MNU_CURITM);
    page = UxMenu_GetData(&UIMenuWndSetup_Setup_MenuCtrl,MNU_PAGEITEM);
    item = (item / page) + 1;
    total_page = ((UIMenuWndSetup_Setup_Menu_MAX % page) == 0)?(UIMenuWndSetup_Setup_Menu_MAX / page):(UIMenuWndSetup_Setup_Menu_MAX / page + 1);
    sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
    UxStatic_SetData(&UIMenuWndSetup_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

    for(item = UIMenuWndSetup_Setup_Menu_STRID_DATE_TIME;item < UIMenuWndSetup_Setup_Menu_MAX;item++)
        UxMenu_SetItemData(&UIMenuWndSetup_Setup_MenuCtrl,item,MNUITM_STATUS,(STATUS_DISABLE));

    //UxCtrl_SetShow(&UIMenuWndSetup_Dir_PanelCtrl,TRUE);
    //UxCtrl_SetShow(&UIMenuWndSetup_Dir2_PanelCtrl,FALSE);
    UxCtrl_SetShow(&UIMenuWndSetup_Dir3_PanelCtrl,TRUE);

    bUIMenuWndSetup_Setup_MenuCtrl_rx_event = FALSE;
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxState_SetData(&UIMenuWndSetup_Title_Mode_StatusCtrl,STATE_CURITEM,UIMenuWndSetup_Title_Mode_Status_STRID_SETUP);

    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == FALSE)
    {
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir_PanelCtrl,TRUE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir2_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir3_PanelCtrl,FALSE);
    }
    else
    {
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir2_PanelCtrl,TRUE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir3_PanelCtrl,FALSE);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == FALSE)
    {
        Ux_CloseWindow(pCtrl,0);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndSetup_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == FALSE)
    {
        Ux_CloseWindow(pCtrl,0);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndSetup_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 item,page,total_page;
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == FALSE)
    {
        bUIMenuWndSetup_Setup_MenuCtrl_rx_event = TRUE;
        for(item = UIMenuWndSetup_Setup_Menu_STRID_DATE_TIME;item < UIMenuWndSetup_Setup_Menu_MAX;item++)
        {
            UxMenu_SetItemData(&UIMenuWndSetup_Setup_MenuCtrl,item,MNUITM_STATUS,(STATUS_ENABLE));
        }
        item = UxMenu_GetData(&UIMenuWndSetup_Setup_MenuCtrl,MNU_CURITM);
        page = UxMenu_GetData(&UIMenuWndSetup_Setup_MenuCtrl,MNU_PAGEITEM);

        debug_msg("UIMenuWndSetup_OnKeyDown item = %d, page = %d\n\r",item, page);
        item = (item / page)+1;
        total_page = ((UIMenuWndSetup_Setup_Menu_MAX % page) == 0)?(UIMenuWndSetup_Setup_Menu_MAX / page):(UIMenuWndSetup_Setup_Menu_MAX / page + 1);
        //total_page = (UIMenuWndSetup_Setup_Menu_MAX / page);
        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        debug_msg("%s\n\r",BottomBar_Buf);
        UxStatic_SetData(&UIMenuWndSetup_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        //UxCtrl_SetShow(&UIMenuWndSetup_Dir_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir2_PanelCtrl,TRUE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir3_PanelCtrl,FALSE);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndSetup_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(gOldTitle_Mode)
    {
    case UIMenuWndSetup_Title_Old_Status_ICON_MENU_STILL_OFF:
        Ux_CloseWindow(&UIMenuWndPhotoStillCtrl,0);
        break;
    case UIMenuWndSetup_Title_Old_Status_ICON_MENU_PLAYBACK_OFF:
        Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);		
	 debug_err(("close setup menu windows...\r\n"));		
        break;
    case UIMenuWndSetup_Title_Old_Status_ICON_MENU_VIDEO_OFF:
        Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
        break;
    case UIMenuWndSetup_Title_Old_Status_ICON_MENU_PRINT_OFF:
        break;
    }
    Ux_CloseWindow(pCtrl,0);	
    return NVTEVT_CONSUME;
}
//#NT#2009/09/14#KS Hung -begin
INT32 UIMenuWndSetup_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//#NT#2009/09/14#KS Hung -end
//---------------------UIMenuWndSetup_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Panel)
EVENT_END

//---------------------UIMenuWndSetup_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Title_Mode_Status)
CTRL_LIST_ITEM(UIMenuWndSetup_Title_Old_Status)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Title_Panel)
EVENT_END

//----------------------UIMenuWndSetup_Title_Mode_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Title_Mode_Status)
EVENT_END

//----------------------UIMenuWndSetup_Title_Old_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Title_Old_Status)
EVENT_END

//---------------------UIMenuWndSetup_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_End_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Return_Static)
CTRL_LIST_ITEM(UIMenuWndSetup_Dir_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Dir2_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Dir3_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_PageNum_Static)
CTRL_LIST_END

//----------------------UIMenuWndSetup_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_End_Panel)
EVENT_END

//----------------------UIMenuWndSetup_Return_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Return_Static)
EVENT_END

//---------------------UIMenuWndSetup_Dir_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Dir_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Dir_Panel)
EVENT_END

//---------------------UIMenuWndSetup_Dir2_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Dir2_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Dir2_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Dir2_Panel)
EVENT_END

//---------------------UIMenuWndSetup_Dir3_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Dir3_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Dir3_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Dir3_Panel)
EVENT_END

//----------------------UIMenuWndSetup_PageNum_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_PageNum_Static)
EVENT_END

//----------------------UIMenuWndSetup_Setup_MenuCtrl Event---------------------------
INT32 UIMenuWndSetup_Setup_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetup_Setup_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetup_Setup_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetup_Setup_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetup_Setup_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetup_Setup_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetup_Setup_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetup_Setup_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    INT32   page,total_page;
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        if(item == 0)
        {
            item = UIMenuWndSetup_Setup_Menu_MAX - 1;
            item = (item/ page) + 1;
        }
        else
            item = ((item-1) / page) + 1;
        total_page = ((UIMenuWndSetup_Setup_Menu_MAX % page) == 0)?(UIMenuWndSetup_Setup_Menu_MAX / page):(UIMenuWndSetup_Setup_Menu_MAX / page + 1);
        //total_page = (UIMenuWndSetup_Setup_Menu_MAX / page);
        debug_msg("UIMenuWndSetup_Setup_Menu_OnKeyUp item = %d, page = %d\n\r",item, page);

        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        UxStatic_SetData(&UIMenuWndSetup_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    INT32   page,total_page;
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        if(item == (UIMenuWndSetup_Setup_Menu_MAX - 1))
        {
            item = 0;
            item = (item/ page) + 1;
        }
        else
            item = ((item+1) / page) + 1;
        total_page = ((UIMenuWndSetup_Setup_Menu_MAX % page) == 0)?(UIMenuWndSetup_Setup_Menu_MAX / page):(UIMenuWndSetup_Setup_Menu_MAX / page + 1);
        //total_page = (UIMenuWndSetup_Setup_Menu_MAX / page);
        debug_msg("UIMenuWndSetup_Setup_Menu_OnKeyDown item = %d, page = %d\n\r",item, page);

        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        UxStatic_SetData(&UIMenuWndSetup_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item,page,total_page;
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == TRUE)
    {
        for(item = UIMenuWndSetup_Setup_Menu_STRID_DATE_TIME;item < UIMenuWndSetup_Setup_Menu_MAX;item++)
        {
            UxMenu_SetItemData(&UIMenuWndSetup_Setup_MenuCtrl,item,MNUITM_STATUS,(STATUS_DISABLE | STATUS_NORMAL_BIT));
        }
        UxMenu_SetData(pCtrl,MNU_CURITM,UIMenuWndSetup_Setup_Menu_STRID_DATE_TIME);

        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        item = (item / page)+1;
        total_page = ((UIMenuWndSetup_Setup_Menu_MAX % page) == 0)?(UIMenuWndSetup_Setup_Menu_MAX / page):(UIMenuWndSetup_Setup_Menu_MAX / page + 1);
        //total_page = (UIMenuWndSetup_Setup_Menu_MAX / page);
        debug_msg("UIMenuWndSetup_Setup_Menu_OnKeyLeft item = %d, page = %d\n\r",item, page);
        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        debug_msg("%s\n\r",BottomBar_Buf);
        UxStatic_SetData(&UIMenuWndSetup_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        //UxCtrl_SetShow(&UIMenuWndSetup_Dir_PanelCtrl,TRUE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir2_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir3_PanelCtrl,FALSE);
    }
    bUIMenuWndSetup_Setup_MenuCtrl_rx_event = FALSE;
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        UxState_SetData(&UIMenuWndSetup_Title_Mode_StatusCtrl,STATE_CURITEM,(UIMenuWndSetup_Title_Mode_Status_STRID_SETUP + item + 1));
        UxCtrl_SetDirty(&UIMenuWndSetup_Title_PanelCtrl, TRUE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir2_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir3_PanelCtrl,TRUE);
        Ux_Redraw();
        //#NT#2009/09/11#Ks Hung -begin
        switch (item)
        {
        case UIMenuWndSetup_Setup_Menu_STRID_DATE_TIME:
            Ux_OpenWindow(&UIMenuWndSetupDateTimeCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_AUTO_OFF:
            Ux_OpenWindow(&UIMenuWndSetupAutoPowerOffCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_BEEPER:
            Ux_OpenWindow(&UIMenuWndSetupBeepSoundCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_LANGUAGE:
            Ux_OpenWindow(&UIMenuWndSetupLanguageCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_FREQUENCY:
            Ux_OpenWindow(&UIMenuWndSetupFrequencyCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_TV_MODE:
            Ux_OpenWindow(&UIMenuWndSetupTVModeCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_DEFAULT_SETTING:
            Ux_OpenWindow(&UIMenuWndSetupDefaultSettingCtrl,0);
            break;		
        case UIMenuWndSetup_Setup_Menu_STRID_VERSION:
            Ux_OpenWindow(&UIMenuWndSetupVersionCtrl,0);
            break;
/*			
        case UIMenuWndSetup_Setup_Menu_STRID_DELAY_POWEROFF:
            Ux_OpenWindow(&UIMenuWndSetupDelayPowerOffCtrl,0);
            break;	
        case UIMenuWndSetup_Setup_Menu_STRID_ANTI_SHAKING:
            Ux_OpenWindow(&UIMenuWndPhotoAntiShaCtrl,0);
            break;			
        case UIMenuWndSetup_Setup_Menu_STRID_SENSOR_ROTATE:
            Ux_OpenWindow(&UIMenuWndSetupImageRotateCtrl,0);
            break;	
*/             
        case UIMenuWndSetup_Setup_Menu_STRID_SCEEN_SAVE:	
            Ux_OpenWindow(&UIMenuWndSetupLcdOffCtrl,0);	
           break;
        default:
            debug_err(("No any item is selected in setup menu\n\r"));
            break;
        }
        //#NT#2009/09/11#Ks Hung -end
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    if(bUIMenuWndSetup_Setup_MenuCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        UxState_SetData(&UIMenuWndSetup_Title_Mode_StatusCtrl,STATE_CURITEM,(UIMenuWndSetup_Title_Mode_Status_STRID_SETUP + item + 1));
        UxCtrl_SetDirty(&UIMenuWndSetup_Title_PanelCtrl, TRUE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir2_PanelCtrl,FALSE);
        //UxCtrl_SetShow(&UIMenuWndSetup_Dir3_PanelCtrl,TRUE);
        Ux_Redraw();
        //#NT#2009/09/11#Ks Hung -begin
        switch (item)
        {
        case UIMenuWndSetup_Setup_Menu_STRID_DATE_TIME:
            Ux_OpenWindow(&UIMenuWndSetupDateTimeCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_AUTO_OFF:
            Ux_OpenWindow(&UIMenuWndSetupAutoPowerOffCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_BEEPER:
            Ux_OpenWindow(&UIMenuWndSetupBeepSoundCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_LANGUAGE:
            Ux_OpenWindow(&UIMenuWndSetupLanguageCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_FREQUENCY:
            Ux_OpenWindow(&UIMenuWndSetupFrequencyCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_TV_MODE:
            Ux_OpenWindow(&UIMenuWndSetupTVModeCtrl,0);
            break;
        case UIMenuWndSetup_Setup_Menu_STRID_DEFAULT_SETTING:
            Ux_OpenWindow(&UIMenuWndSetupDefaultSettingCtrl,0);
            break;
		
        case UIMenuWndSetup_Setup_Menu_STRID_VERSION:
            Ux_OpenWindow(&UIMenuWndSetupVersionCtrl,0);
            break;
			
        case UIMenuWndSetup_Setup_Menu_STRID_FORMAT:
            Ux_OpenWindow(&UIMenuWndSetupFormatCtrl,0);
            break;			
        case UIMenuWndSetup_Setup_Menu_STRID_SENSOR_ROTATE:
            Ux_OpenWindow(&UIMenuWndSetupImageRotateCtrl,0);
            break;			
        case UIMenuWndSetup_Setup_Menu_STRID_SCEEN_SAVE:	
            Ux_OpenWindow(&UIMenuWndSetupLcdOffCtrl,0);		
		break;
        default:
            debug_err(("No any item is selected in setup menu\n\r"));
            break;
        }
        //#NT#2009/09/11#Ks Hung -end
    }
    return NVTEVT_CONSUME;
}
