//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPRINT_CROP_H
#define UIMENUWNDPRINT_CROP_H

#include "UIFramework.h"

//-------------------------------------------------------------------------------------------------
#define UIMenuWndPrint_Crop_WIN_STEP    1
#define UIMenuWndPrint_Crop_WIN_X1      0
#define UIMenuWndPrint_Crop_WIN_Y1      0
#define UIMenuWndPrint_Crop_WIN_X2      260
#define UIMenuWndPrint_Crop_WIN_Y2      180
//-------------------------------------------------------------------------------------------------

extern VControl UIMenuWndPrint_CropCtrl;//Panel type 

extern VControl UIMenuWndPrint_Crop_Title_Text_StatusCtrl;//Status type 

typedef enum
{
UIMenuWndPrint_Crop_Title_Text_Status_STRID_CROP,
UIMenuWndPrint_Crop_Title_Text_Status_MAX
}UIMenuWndPrint_Crop_Title_Text_Status_Setting;

extern VControl UIMenuWndPrint_Crop_End_Dir_Menu_PanelCtrl;//Panel type

//-------------------------------------------------------------------------------------------------
typedef enum
{
    UIMenuWndPrint_Crop_OPER_NONE,
    UIMenuWndPrint_Crop_OPER_SIZE,
    UIMenuWndPrint_Crop_OPER_POS
}UIMenuWndPrint_Crop_OPER_ENUM;
//-------------------------------------------------------------------------------------------------
#endif
