//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIERESOLUTION_H
#define UIMENUWNDMOVIERESOLUTION_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieResCtrl;//Panel type 

extern VControl UIMenuWndMovieRes_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieRes_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieRes_Menu_STRID_NULL,
UIMenuWndMovieRes_Menu_STRID_IMGSIZE,
UIMenuWndMovieRes_Menu_STRID_MODE,
UIMenuWndMovieRes_Menu_STRID_RESOLUTION,
UIMenuWndMovieRes_Menu_MAX
}UIMenuWndMovieRes_Menu_Setting;

#endif
