//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndMovieMotionDetectRes.c"
#include "UIMenuWndMovieMotionDetect.h"
#include "UIMovieObj.h"
#include "UISystemObj.h"
#include "UIMenuWndMovieVideo.h"

//---------------------UIMenuWndMovieMotionDetCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieMotionDet)
CTRL_LIST_ITEM(UIMenuWndMovieMotionDet_Panel)
CTRL_LIST_END

//----------------------UIMenuWndMovieMotionDetCtrl Event---------------------------
INT32 UIMenuWndMovieMotionDet_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieMotionDet_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieMotionDet)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndMovieMotionDet_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndMovieMotionDet_OnClose)
EVENT_END

INT32 UIMenuWndMovieMotionDet_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxMenu_SetData(&UIMenuWndMovieMotionDet_MenuCtrl,MNU_CURITM,Get_MovieMotionDetIndex());
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieMotionDet_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndMovieMotionDet_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieMotionDet_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieMotionDet_Menu)
CTRL_LIST_END

//----------------------UIMenuWndMovieMotionDet_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieMotionDet_Panel)
EVENT_END

//----------------------UIMenuWndMovieMotionDet_MenuCtrl Event---------------------------
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieMotionDet_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndMovieMotionDet_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndMovieMotionDet_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndMovieMotionDet_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndMovieMotionDet_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndMovieMotionDet_Menu_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndMovieMotionDet_Menu_OnKeyMode)
EVENT_END

INT32 UIMenuWndMovieMotionDet_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieMotionDetCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 INT32 ui32CurrListItem;

    ui32CurrListItem = UxMenu_GetData(pCtrl,MNU_CURITM);
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_MOTION_DET,1,ui32CurrListItem);
    Ux_CloseWindow(&UIMenuWndMovieMotionDetCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieMotionDet_Menu_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
