//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndMovieFlashRecRes.c"
#include "UIMenuWndMovieFlashRec.h"
#include "UIMenuWndMovieVideo.h"
#include "UIMovieObj.h"
#include "UISystemObj.h"
//---------------------UIMenuWndMovieFlashRecCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieFlashRec)
CTRL_LIST_ITEM(UIMenuWndMovieFlashRec_Panel)
CTRL_LIST_END

//----------------------UIMenuWndMovieFlashRecCtrl Event---------------------------
INT32 UIMenuWndMovieFlashRec_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieFlashRec_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieFlashRec)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndMovieFlashRec_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndMovieFlashRec_OnClose)
EVENT_END

INT32 UIMenuWndMovieFlashRec_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxMenu_SetData(&UIMenuWndMovieFlashRec_MenuCtrl, MNU_CURITM, Get_MovieFlashRecIndex());
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieFlashRec_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndMovieFlashRec_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieFlashRec_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieFlashRec_Menu)
CTRL_LIST_END

//----------------------UIMenuWndMovieFlashRec_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieFlashRec_Panel)
EVENT_END

//----------------------UIMenuWndMovieFlashRec_MenuCtrl Event---------------------------
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieFlashRec_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndMovieFlashRec_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndMovieFlashRec_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndMovieFlashRec_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndMovieFlashRec_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndMovieFlashRec_Menu_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndMovieFlashRec_Menu_OnKeyMode)
EVENT_END

INT32 UIMenuWndMovieFlashRec_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieFlashRecCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 INT32 ui32CurrListItem;

    ui32CurrListItem = UxMenu_GetData(pCtrl,MNU_CURITM);
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_FLASH_REC,1,ui32CurrListItem);
    Ux_CloseWindow(&UIMenuWndMovieFlashRecCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieFlashRec_Menu_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
