//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEFLASHREC_H
#define UIMENUWNDMOVIEFLASHREC_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieFlashRecCtrl;//Panel type 

extern VControl UIMenuWndMovieFlashRec_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieFlashRec_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieFlashRec_Menu_STRID_OFF,
UIMenuWndMovieFlashRec_Menu_STRID_ON,
UIMenuWndMovieFlashRec_Menu_MAX
}UIMenuWndMovieFlashRec_Menu_Setting;

#endif
