//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEMOTIONDETECT_H
#define UIMENUWNDMOVIEMOTIONDETECT_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieMotionDetCtrl;//Panel type 

extern VControl UIMenuWndMovieMotionDet_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieMotionDet_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieMotionDet_Menu_STRID_OFF,
UIMenuWndMovieMotionDet_Menu_STRID_ON,
UIMenuWndMovieMotionDet_Menu_MAX
}UIMenuWndMovieMotionDet_Menu_Setting;

#endif
