//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEGOLFREC_H
#define UIMENUWNDMOVIEGOLFREC_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieGolfRecCtrl;//Panel type 

extern VControl UIMenuWndMovieGolfRec_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieGolfRec_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieGolfRec_Menu_STRID_OFF,
UIMenuWndMovieGolfRec_Menu_STRID_ON,
UIMenuWndMovieGolfRec_Menu_MAX
}UIMenuWndMovieGolfRec_Menu_Setting;

#endif
