//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEGODBLESS_H
#define UIMENUWNDMOVIEGODBLESS_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieGodBlessCtrl;//Panel type 

extern VControl UIMenuWndMovieGodBless_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieGodBless_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieGodBless_Menu_STRID_OFF,
UIMenuWndMovieGodBless_Menu_STRID_ON,
UIMenuWndMovieGodBless_Menu_MAX
}UIMenuWndMovieGodBless_Menu_Setting;

#endif
