//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEAUDIOSET_H
#define UIMENUWNDMOVIEAUDIOSET_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieAudioSetCtrl;//Panel type 

extern VControl UIMenuWndMovieAudioSet_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieAudioSet_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieAudioSet_Menu_STRID_OFF,
UIMenuWndMovieAudioSet_Menu_STRID_ON,
UIMenuWndMovieAudioSet_Menu_MAX
}UIMenuWndMovieAudioSet_Menu_Setting;

#endif
