//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMovieObj.h"
#include "UISystemObj.h"
#include "UIMenuWndMovieCyclicRecRes.c"
#include "UIMenuWndMovieCyclicRec.h"
#include "UIMenuWndMovieVideo.h"
//---------------------UIMenuWndMovieCyclicRecCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieCyclicRec)
CTRL_LIST_ITEM(UIMenuWndMovieCyclicRec_Panel)
CTRL_LIST_END

//----------------------UIMenuWndMovieCyclicRecCtrl Event---------------------------
INT32 UIMenuWndMovieCyclicRec_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieCyclicRec_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieCyclicRec)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndMovieCyclicRec_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndMovieCyclicRec_OnClose)
EVENT_END

INT32 UIMenuWndMovieCyclicRec_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxMenu_SetData(&UIMenuWndMovieCyclicRec_MenuCtrl,MNU_CURITM,Get_MovieCyclicRecIndex());
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieCyclicRec_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndMovieCyclicRec_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieCyclicRec_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieCyclicRec_Menu)
CTRL_LIST_END

//----------------------UIMenuWndMovieCyclicRec_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieCyclicRec_Panel)
EVENT_END

//----------------------UIMenuWndMovieCyclicRec_MenuCtrl Event---------------------------
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieCyclicRec_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndMovieCyclicRec_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndMovieCyclicRec_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndMovieCyclicRec_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndMovieCyclicRec_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndMovieCyclicRec_Menu_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndMovieCyclicRec_Menu_OnKeyMode)
EVENT_END

INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieCyclicRecCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 INT32 ui32CurrListItem;

    ui32CurrListItem = UxMenu_GetData(pCtrl,MNU_CURITM);
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_CYCLIC_REC,1,ui32CurrListItem);
    Ux_CloseWindow(&UIMenuWndMovieCyclicRecCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieCyclicRec_Menu_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
