//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIECYCLICREC_H
#define UIMENUWNDMOVIECYCLICREC_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieCyclicRecCtrl;//Panel type 

extern VControl UIMenuWndMovieCyclicRec_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieCyclicRec_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieCyclicRec_Menu_STRID_OFF,
UIMenuWndMovieCyclicRec_Menu_STRID_3MIN,
UIMenuWndMovieCyclicRec_Menu_STRID_5MIN,
UIMenuWndMovieCyclicRec_Menu_STRID_10MIN,
UIMenuWndMovieCyclicRec_Menu_MAX
}UIMenuWndMovieCyclicRec_Menu_Setting;

#endif
