//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDCOMMON_H
#define UIFLOWWNDCOMMON_H

#include "UIFramework.h"

void UIFlowWndCommon_QuantizeHistoData(UINT32 *HistogramData, UINT32 uiTotal);
void UIFlowWndCommon_GetHistogram(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
#endif
