//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndWrnMsgRes.c"
#include "UIFlowWndWrnMsg.h"
#include "UISystemObj.h"
#include "KeyScanTsk.h"


//-----------------------------------------------------------------------------
// UIFlowWndWrnMsg User Variable & Function Declarations
//-----------------------------------------------------------------------------
static UINT32 g_uiWrnMsgIssue       = 0;
static UINT32 g_uiWrnMsgExpTime     = 0;
static UINT32 g_uiExpTimerID        = NULL_TIMER;

#define TIMER_ONE_SEC               1000
#define TIMER_TWO_SEC               2000

//-----------------------------------------------------------------------------
// UIFlowWndWrnMsg ToolGen
//-----------------------------------------------------------------------------
//---------------------UIFlowWndWrnMsg Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndWrnMsg)
CTRL_LIST_ITEM(UIFlowWndWrnMsg_StatusTXT_Msg)
CTRL_LIST_END

//----------------------UIFlowWndWrnMsg Event---------------------------
INT32 UIFlowWndWrnMsg_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnMsg_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndWrnMsg)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndWrnMsg_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndWrnMsg_OnClose)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndWrnMsg_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndWrnMsg_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndWrnMsg_OnKeyPlayback)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndWrnMsg_OnTimer)
EVENT_END

INT32 UIFlowWndWrnMsg_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    debug_ind(("UIFlowWndWrnMsg: OnOpen\r\n"));

    if(paramNum > 0)
    {
        g_uiWrnMsgIssue = paramArray[0];
        debug_ind(("UIFlowWndWrnMsg: Issue case = 0x%x\r\n", g_uiWrnMsgIssue));
        if(paramNum > 1)
        {
            g_uiWrnMsgExpTime = paramArray[1];
            debug_ind(("UIFlowWndWrnMsg: Exp time = 0x%x\r\n", g_uiWrnMsgExpTime));
        }
    }
    UxState_SetData(&UIFlowWndWrnMsg_StatusTXT_MsgCtrl,STATE_CURITEM,g_uiWrnMsgIssue);
    UxCtrl_SetShow(&UIFlowWndWrnMsg_StatusTXT_MsgCtrl,TRUE);

    /* Start window expiration timer */
    if(g_uiWrnMsgExpTime)
    {
        g_uiExpTimerID = KeyScan_startTimer((TIMER_ONE_SEC * g_uiWrnMsgExpTime), NVTEVT_WRNMSG_WND_EXP_TIMER, ONE_SHOT);
    }

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    debug_ind(("UIFlowWndWrnMsg: OnClose\r\n"));

    /* Stop window expiration timer if exists */
    if(g_uiExpTimerID != NULL_TIMER)
    {
        KeyScan_stopTimer(&g_uiExpTimerID);
    }

    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Let parent window do creating Menu window */
    Ux_CloseWindow(pCtrl,1,NVTRET_ENTER_MENU);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/03#Chris Chung -begin
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_PLAYBACK_MODE,0);
    //#NT#2009/09/03#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnMsg_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVTEVT event;

    event = paramArray[0];
    debug_ind(("UIFlowWndWrnMsg OnTimer event = 0x%x\r\n", event));

    switch(event)
    {
        case NVTEVT_WRNMSG_WND_EXP_TIMER:
            /**************************************************************************************
            **
            ** Warning Timeout Action
            **
            **************************************************************************************/
            if(g_uiExpTimerID != NULL_TIMER)
            {
                KeyScan_stopTimer(&g_uiExpTimerID);
            }
            Ux_CloseWindow(pCtrl,0);
            break;

        default:
            debug_err(("UIFlowWndWrnMsg OnTimer: Unknown event 0x%x\r\n", event));
            break;
    }

    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndWrnMsg_StatusTXT_Msg Event---------------------------
EVENT_BEGIN(UIFlowWndWrnMsg_StatusTXT_Msg)
EVENT_END

//-----------------------------------------------------------------------------
// UIFlowWndWrnMsg User Functions
//-----------------------------------------------------------------------------

