//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYFORMAT_H
#define UIMENUWNDPLAYFORMAT_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayFormatCtrl;//Panel type 

extern VControl UIMenuWndPlayFormat_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndPlayFormat_List_Text_STRID_INT_FLASH,
UIMenuWndPlayFormat_List_Text_STRID_EXT_CARD,
UIMenuWndPlayFormat_List_Text_MAX
}UIMenuWndPlayFormat_List_Text_Setting;

#endif
