//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayFormatConfirmRes.c"
#include "UIMenuWndPlayFormatConfirm.h"
#include "UIMenuWndPlayFormat.h"
#include "PrimaryTsk.h"
#include "UIMenuWndMovieVideo.h"
#include "UIMenuWndPlayback.h"
#include "UIFlowWndWrnMsg.h"
#include "UISystemStatusSettings.h"
#include "UIFlowWndWaitMoment.h"
#include "UIPlayObj.h"
#include "UISystemObj.h"

UINT32 g_u32FormatIndex = 0;
//#NT#2009/08/17#Chris Chung -end
//---------------------UIMenuWndPlayFormatConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayFormatConfirm)
CTRL_LIST_ITEM(UIMenuWndPlayFormatConfirm_List_Text)
CTRL_LIST_ITEM(UIMenuWndPlayFormatConfirm_Static_Text)
CTRL_LIST_END

//----------------------UIMenuWndPlayFormatConfirmCtrl Event---------------------------
INT32 UIMenuWndPlayFormatConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayFormatConfirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayFormatConfirm_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayFormatConfirm_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayFormatConfirm_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayFormatConfirm_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayFormatConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayFormatConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayFormatConfirm_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayFormatConfirm_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayFormatConfirm_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayFormatConfirm_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayFormatConfirm_OnKeyMode)
EVENT_END

INT32 UIMenuWndPlayFormatConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

    if(paramNum > 0)
    {
        g_u32FormatIndex = paramArray[0];
    }
    UxList_SetData(&UIMenuWndPlayFormatConfirm_List_TextCtrl, LST_CURITM, 0);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayFormatConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayFormatConfirm_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT && paramArray[1]==NVTRET_FORMAT)
        {
            Ux_CloseWindow(&UIMenuWndPlayFormatCtrl, 0);
        }
        else if(paramArray[0]==NVTRET_ENTER_MENU)
        {
            Ux_RedrawAllWind();
        }
    }
    else
    {
        Ux_RedrawAllWind();
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayFormatConfirm_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndPlayFormatCtrl, 0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayFormatConfirm_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndPlayFormatCtrl, 0);
#if 0
    //#NT#2009/07/28#Chris Chung -begin
    switch(Primary_GetCurrentMode())
    {
    case PRIMARY_MODE_MOVIE:
        Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0);
        break;
    case PRIMARY_MODE_PHOTO:
//        Ux_CloseWindow(&UIMenuWndPhotoStillCtrl,0);
        break;
    case PRIMARY_MODE_PLAYBACK:
        Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);
        break;
    }
	#endif
    //#NT#2009/07/28#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayFormatConfirm_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/17#Chris Chung -begin
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    //#NT#2009/08/17#Chris Chung -end
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayFormatConfirm_List_TextCtrl Event---------------------------
INT32 UIMenuWndPlayFormatConfirm_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayFormatConfirm_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayFormatConfirm_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayFormatConfirm_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayFormatConfirm_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayFormatConfirm_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayFormatConfirm_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayFormatConfirm_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayFormatConfirm_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayFormatConfirm_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/12/07#Chris Chung -begin
    if(UxList_GetData(pCtrl,LST_CURITM)==UIMenuWndPlayFormatConfirm_List_Text_STRID_OK)
    {
        if(g_u32FormatIndex==0)
        {
            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
            Ux_BackgroundPostEvent(NVTEVT_BKW_FORMATNAND);
        }
        else if(g_u32FormatIndex==1)
        {
            if(GetCardStatus() == CARD_REMOVED)
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            }
            else
            {
                if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
                {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
                    return NVTEVT_CONSUME;
                }
            }

            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
            Ux_BackgroundPostEvent(NVTEVT_BKW_FORMATCARD);
        }
        else
        {
            Ux_CloseWindow(&UIMenuWndPlayFormatCtrl, 0);
        }
    }
    else
    {
        Ux_CloseWindow(&UIMenuWndPlayFormatCtrl, 0);
    }
    //#NT#2009/12/07#Chris Chung -end
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayFormatConfirm_Static_TextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayFormatConfirm_Static_Text)
EVENT_END

