//This source code is generated by UI Designer Studio.

#include "SysCfg.h"
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndCalibrationRes.c"
#include "UIMenuWndCalibration.h"
#include "CalibrationInt.h"
#include "KeyScanTsk.h"
#include "UISystemObj.h"
#include "Debug.h"

#if (_CALIBRATION_MODE_ == ENABLE)

//---------------------UIMenuWndCalibrationCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndCalibration)
CTRL_LIST_ITEM(UIMenuWndCalibration_Background)
CTRL_LIST_ITEM(UIMenuWndCalibration_TitleBar)
CTRL_LIST_ITEM(UIMenuWndCalibration_TipsBar)
CTRL_LIST_ITEM(UIMenuWndCalibration_Item)
CTRL_LIST_END

//----------------------UIMenuWndCalibrationCtrl Event---------------------------
INT32 UIMenuWndCalibration_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndCalibration_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndCalibration_OnChildClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndCalibration)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndCalibration_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndCalibration_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndCalibration_OnChildClose)
EVENT_END

#define TM_ITEMS_PERPAGE    4

typedef struct _CAL_DATA {
    INT16   SelItem;    // selected item number in total items
    INT16   FirstItem;  // first item number in current menu page
    INT16   Count;      // total item number
} CAL_DATA;

CAL_DATA g_CalData = { 0 };

char g_CalibrationTitle[20] = "Calibration";
char g_CalibrationItem[TM_ITEMS_PERPAGE][32];

void UIMenuWndCalibration_SelectItem(INT16 new_sel)
{
    INT16   old_sel, old_first;

    // original selected items
    old_sel = g_CalData.SelItem;
    old_first = g_CalData.FirstItem;

    // new item
    g_CalData.SelItem = new_sel;

    if (g_CalData.SelItem >= g_CalData.Count)
        g_CalData.SelItem = 0;
    else if (g_CalData.SelItem < 0)
        g_CalData.SelItem = g_CalData.Count - 1;

    g_CalData.FirstItem = (g_CalData.SelItem / TM_ITEMS_PERPAGE) * TM_ITEMS_PERPAGE;

    if (g_CalData.FirstItem != old_first)
    {
        UINT32  i, count = g_CalData.Count - g_CalData.FirstItem;

        if (count > TM_ITEMS_PERPAGE)
            count = TM_ITEMS_PERPAGE;

        UxMenu_SetData(&UIMenuWndCalibration_ItemCtrl, MNU_TOTITM, count);
        if (new_sel > old_sel)
            UxMenu_SetData(&UIMenuWndCalibration_ItemCtrl, MNU_CURITM, 0);
        else
            UxMenu_SetData(&UIMenuWndCalibration_ItemCtrl, MNU_CURITM, count - 1);

        for (i = 0; i < count; i++)
        {
            sprintf(g_CalibrationItem[i], "%d. %s", i + g_CalData.FirstItem + 1, g_CalItem[i + g_CalData.FirstItem].pItemName);
            UxMenu_SetItemData(&UIMenuWndCalibration_ItemCtrl, UIMenuWndCalibration_Item_STRID_A1 + i, MNUITM_STRID, Txt_Pointer(g_CalibrationItem[i]));
        }
    }
    else if (g_CalData.SelItem != old_sel)
    {
    }
}

void UIMenuWndCalibration_ShiftItem(INT16 offset)
{
	UIMenuWndCalibration_SelectItem(g_CalData.SelItem + offset);
}

INT32 UIMenuWndCalibration_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  i;
    UINT32  count = TM_ITEMS_PERPAGE;

    g_CalData.SelItem = 0;
    g_CalData.FirstItem = 0;
    g_CalData.Count = Cal_GetMaxItemNum();

    UxStatic_SetData(&UIMenuWndCalibration_TitleNameCtrl, STATIC_VALUE, Txt_Pointer(g_CalibrationTitle));
    UxCtrl_SetShow(&UIMenuWndCalibration_TitleNameCtrl, TRUE);

    if (g_CalData.Count < TM_ITEMS_PERPAGE)
    {
        count = g_CalData.Count;
        UxMenu_SetData(&UIMenuWndCalibration_ItemCtrl, MNU_TOTITM, count);
    }

    for (i = 0; i < count; i++)
    {
        sprintf(g_CalibrationItem[i], "%d. %s", i + 1, g_CalItem[i].pItemName);
        UxMenu_SetItemData(&UIMenuWndCalibration_ItemCtrl, UIMenuWndCalibration_Item_STRID_A1 + i, MNUITM_STRID, Txt_Pointer(g_CalibrationItem[i]));
    }

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndCalibration_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndCalibration_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndCalibration_BackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndCalibration_Background)
CTRL_LIST_END

//----------------------UIMenuWndCalibration_BackgroundCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndCalibration_Background)
EVENT_END

//---------------------UIMenuWndCalibration_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndCalibration_TitleBar)
CTRL_LIST_ITEM(UIMenuWndCalibration_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndCalibration_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndCalibration_TitleBar)
EVENT_END

//----------------------UIMenuWndCalibration_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndCalibration_TitleName)
EVENT_END

//---------------------UIMenuWndCalibration_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndCalibration_TipsBar)
CTRL_LIST_ITEM(UIMenuWndCalibration_UDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndCalibration_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndCalibration_TipsBar)
EVENT_END

//---------------------UIMenuWndCalibration_UDOKTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndCalibration_UDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndCalibration_UDOKTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndCalibration_UDOKTips)
EVENT_END

//----------------------UIMenuWndCalibration_ItemCtrl Event---------------------------
INT32 UIMenuWndCalibration_Item_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndCalibration_Item_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndCalibration_Item_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndCalibration_Item)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndCalibration_Item_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndCalibration_Item_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndCalibration_Item_OnKeyEnter)
EVENT_END

INT32 UIMenuWndCalibration_Item_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    UIMenuWndCalibration_ShiftItem(-1);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndCalibration_Item_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    UIMenuWndCalibration_ShiftItem(+1);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndCalibration_Item_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    static BOOL bIsFirst = TRUE;

    /* Must ignore the 1st S2 key evt, coz S2 key is also the Engineering Mode hotkey */
    if(bIsFirst)
    {
        bIsFirst = FALSE;
        return NVTEVT_CONSUME;
    }

    if(g_CalItem[g_CalData.SelItem].ItemFunction != NULL)
    {
        clr_flg(FLG_ID_KEY, 0xffffffff);
        g_CalItem[g_CalData.SelItem].ItemFunction();
    }
    Ux_FlushEvent();
    UxCtrl_SetShow(&UIMenuWndCalibrationCtrl, TRUE);
    Ux_Redraw();
    return NVTEVT_CONSUME;
}

#endif