//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPRINT_PRINTDPOF_H
#define UIMENUWNDPRINT_PRINTDPOF_H

#include "UIFramework.h"

extern VControl UIMenuWndPrint_PrintDPOFCtrl;//Panel type 

extern VControl UIMenuWndPrint_PrintDPOF_Content_PanelCtrl;//Panel type 

extern VControl UIMenuWndPrint_PrintDPOF_Title_PanelCtrl;//Panel type 

extern VControl UIMenuWndPrint_PrintDPOF_Title_Text_StatusCtrl;//Status type 

typedef enum
{
UIMenuWndPrint_PrintDPOF_Title_Text_Status_STRID_DPOF,
UIMenuWndPrint_PrintDPOF_Title_Text_Status_MAX
}UIMenuWndPrint_PrintDPOF_Title_Text_Status_Setting;

extern VControl UIMenuWndPrint_PrintDPOF_Title_Icon_StatusCtrl;//Status type 

typedef enum
{
UIMenuWndPrint_PrintDPOF_Title_Icon_Status_ICON_MENU_PRINT_OFF,
UIMenuWndPrint_PrintDPOF_Title_Icon_Status_MAX
}UIMenuWndPrint_PrintDPOF_Title_Icon_Status_Setting;

extern VControl UIMenuWndPrint_PrintDPOF_End_PanelCtrl;//Panel type 

extern VControl UIMenuWndPrint_PrintDPOF_End_Dir_PanelCtrl;//Panel type 

extern VControl UIMenuWndPrint_PrintDPOF_Menu_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPrint_PrintDPOF_Menu_Menu_STRID_DPOF,
UIMenuWndPrint_PrintDPOF_Menu_Menu_STRID_DPOF_RESTART,
UIMenuWndPrint_PrintDPOF_Menu_Menu_STRID_RETURN,
UIMenuWndPrint_PrintDPOF_Menu_Menu_MAX
}UIMenuWndPrint_PrintDPOF_Menu_Menu_Setting;

#endif
