//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWRNMSG_H
#define UIFLOWWNDWRNMSG_H

#include "UIFramework.h"


//-----------------------------------------------------------------------------
// UIFlowWndWrnMsg User Definitions
//-----------------------------------------------------------------------------
// Warning message issue
typedef enum
{
    FLOWWRNMSG_ISSUE_BATTERY_LOW    = 0,
    FLOWWRNMSG_ISSUE_MEM_FULL,
    FLOWWRNMSG_ISSUE_MEM_ERR,
    FLOWWRNMSG_ISSUE_CARD_FULL,
    FLOWWRNMSG_ISSUE_CARD_ERR,
    FLOWWRNMSG_ISSUE_CARD_LOCKED,
    FLOWWRNMSG_ISSUE_FILE_PROTECTED,
    FLOWWRNMSG_ISSUE_NO_IMAGE,
    FLOWWRNMSG_ISSUE_NO_CARD,
    FLOWWRNMSG_ISSUE_FOLDERFULL,
    FLOWWRNMSG_ISSUE_NOT_JPEG,
    FLOWWRNMSG_ISSUE_NO_MOVIE,
    FLOWWRNMSG_ISSUE_CLUSTER_WRONG,
    FLOWWRNMSG_ISSUE_MAX
} FLOWWRNMSG_ISSUE;

// Warning message window timeout value
typedef enum
{
    FLOWWRNMSG_TIMER_KEEP    = 0,
    FLOWWRNMSG_TIMER_1SEC,
    FLOWWRNMSG_TIMER_2SEC,
    FLOWWRNMSG_TIMER_3SEC,
    FLOWWRNMSG_TIMER_4SEC,
    FLOWWRNMSG_TIMER_5SEC,
    FLOWWRNMSG_TIMER_MAX
} FLOWWRNMSG_TIMER;

//-----------------------------------------------------------------------------
// UIFlowWndWrnMsg ToolGen
//-----------------------------------------------------------------------------
extern VControl UIFlowWndWrnMsgCtrl;

extern VControl UIFlowWndWrnMsg_StatusTXT_MsgCtrl;

typedef enum
{
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORY_FULL,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORYERROR,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARD_FULL,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARDERROR,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARD_LOCKED,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_FILE_PROTECT,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NO_IMAGE,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NO_CARD,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_FOLDERFULL,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NOT_JPEG,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_NO_MOVIE,
UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CLUSTER_WRONG,
UIFlowWndWrnMsg_StatusTXT_Msg_MAX
}UIFlowWndWrnMsg_StatusTXT_Msg_Setting;

//-----------------------------------------------------------------------------
// UIFlowWndWrnMsg User Functions
//-----------------------------------------------------------------------------

#endif
