//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDCOMMON_H
#define UIFLOWWNDCOMMON_H

#include "UIFramework.h"

extern VControl UIFlowWndCommonCtrl;

extern VControl UIFlowWndCommon_TabHistogramCtrl;

#endif
