//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWAITMOMENT_H
#define UIFLOWWNDWAITMOMENT_H

#include "UIFramework.h"


//-----------------------------------------------------------------------------
// UIFlowWndWaitMoment User Definitions
//-----------------------------------------------------------------------------
// Warning message issue
typedef enum
{
    FLOWWAITMOMENT_MSG_PLEASEWAIT    = 0,
    FLOWWAITMOMENT_MSG_MAX
} FLOWWAITMOMENT_MSG;

//-----------------------------------------------------------------------------
// UIFlowWndWaitMoment ToolGen
//-----------------------------------------------------------------------------
extern VControl UIFlowWndWaitMomentCtrl;

extern VControl UIFlowWndWaitMoment_StatusTXT_MsgCtrl;

typedef enum
{
UIFlowWndWaitMoment_StatusTXT_Msg_STRID_PLEASE_WAIT,
UIFlowWndWaitMoment_StatusTXT_Msg_MAX
}UIFlowWndWaitMoment_StatusTXT_Msg_Setting;
extern VControl UIFlowWndWaitMoment_StatusICN_IcnCtrl;

typedef enum
{
UIFlowWndWaitMoment_StatusICN_Icn_ICON_EV_P2P0,
UIFlowWndWaitMoment_StatusICN_Icn_ICON_EV_P1P0,
UIFlowWndWaitMoment_StatusICN_Icn_ICON_EV_P0P0,
UIFlowWndWaitMoment_StatusICN_Icn_ICON_EV_M2P0,
UIFlowWndWaitMoment_StatusICN_Icn_ICON_EV_M1P0,
UIFlowWndWaitMoment_StatusICN_Icn_MAX
}UIFlowWndWaitMoment_StatusICN_Icn_Setting;

//-----------------------------------------------------------------------------
// UIFlowWndWaitMoment User Functions
//-----------------------------------------------------------------------------

#endif
