//This source code is generated by UI Designer Studio.
#include <stdio.h>
#include <string.h>
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPCBRes.c"
#include "UIMenuWndPCB.h"
#include "UISystemObj.h"
#include "UIPhotoObj.h"
#include "KeyScanTsk.h"
#include "Debug.h"


//-----------------------------------------------------------------------------
// UIMenuWndPCB User Variable & Function Declarations
//-----------------------------------------------------------------------------
#define TIMER_ONE_SEC                   1000
#define MAX_RTC_STR_LEN                 32
#define MAX_KEY_STR_LEN                 12
#define MAX_KEY_NUM                     12
#define PCB_KEY_TOTAL_NUM               8

typedef struct _PCB_KEY_CTRL
{
    UINT32          uiKeyCode;
    VControl        *pKeyBtnCtrl;
    CHAR            strKeyName[MAX_KEY_STR_LEN];
} PCB_KEY_CTRL;

static PCB_KEY_CTRL g_PcbKeyCtrlTbl[MAX_KEY_NUM] =
{
        { FLGKEY_UP,                &UIMenuWndPCB_BtnTXT_K1Ctrl,            "Up"            },
        { FLGKEY_DOWN,              &UIMenuWndPCB_BtnTXT_K2Ctrl,            "Down"          },
        { FLGKEY_LEFT,              &UIMenuWndPCB_BtnTXT_K3Ctrl,            "Left"          },
        { FLGKEY_RIGHT,             &UIMenuWndPCB_BtnTXT_K4Ctrl,            "Right"         },
        { FLGKEY_ENTER,             &UIMenuWndPCB_BtnTXT_K5Ctrl,            "OK"            },
        { FLGKEY_PLAYBACK,          &UIMenuWndPCB_BtnTXT_K6Ctrl,            "Pbk"           },
        { FLGKEY_MENU,              &UIMenuWndPCB_BtnTXT_K7Ctrl,            "Menu"          },
        { FLGKEY_MODE,              &UIMenuWndPCB_BtnTXT_K8Ctrl,            "Mode"          },
        { FLGKEY_MODE,              &UIMenuWndPCB_BtnTXT_K9Ctrl,            ""              },
        { FLGKEY_MODE,              &UIMenuWndPCB_BtnTXT_K10Ctrl,           ""              },
        { FLGKEY_MODE,              &UIMenuWndPCB_BtnTXT_K11Ctrl,           ""              },
        { FLGKEY_MODE,              &UIMenuWndPCB_BtnTXT_K12Ctrl,           ""              }
};

static UINT32 g_uiRTCGetTimerID         = NULL_TIMER;
static CHAR g_cRTCStr[MAX_RTC_STR_LEN]  = {0};

static void UIMenuWndPCB_UpdateWndInfo(void);
static CHAR *UIMenuWndPCB_GetRTCString(void);
static void UIMenuWndPCB_SetKeyPressed(UINT32);

//-----------------------------------------------------------------------------
// UIMenuWndPCB ToolGen
//-----------------------------------------------------------------------------
//---------------------UIMenuWndPCBCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPCB)
CTRL_LIST_ITEM(UIMenuWndPCB_Background)
CTRL_LIST_ITEM(UIMenuWndPCB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPCB_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPCB_StatusICN_Battery)
CTRL_LIST_ITEM(UIMenuWndPCB_StaticTXT_RTC)
CTRL_LIST_ITEM(UIMenuWndPCB_StatusICN_Macro)
CTRL_LIST_ITEM(UIMenuWndPCB_StatusICN_Storage)
CTRL_LIST_ITEM(UIMenuWndPCB_StaticTXT_FwVer)
CTRL_LIST_ITEM(UIMenuWndPCB_PNL_KFrame)
CTRL_LIST_END

//----------------------UIMenuWndPCBCtrl Event---------------------------
INT32 UIMenuWndPCB_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnKeyDel(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnMacroChange(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPCB_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPCB)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPCB_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPCB_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPCB_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPCB_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPCB_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPCB_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPCB_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPCB_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPCB_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPCB_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPCB_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPCB_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPCB_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIMenuWndPCB_OnKeyPlayback)
EVENT_ITEM(NVTEVT_KEY_DEL,UIMenuWndPCB_OnKeyDel)
EVENT_ITEM(NVTEVT_STORAGE_INIT,UIMenuWndPCB_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIMenuWndPCB_OnStorageChange)
EVENT_ITEM(NVTEVT_MACRO_CHANGE,UIMenuWndPCB_OnMacroChange)
EVENT_ITEM(NVTEVT_BATTERY,UIMenuWndPCB_OnBattery)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndPCB_OnTimer)
EVENT_END

INT32 UIMenuWndPCB_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    KeyScan_EnableAutoPoweroff(FALSE);
    KeyScan_EnableUSBDet(FALSE);

    /* Update window info */
    UIMenuWndPCB_UpdateWndInfo();

    /* Start RTCGet timer */
    if(g_uiRTCGetTimerID == NULL_TIMER)
    {
        g_uiRTCGetTimerID = KeyScan_startTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
    }

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    KeyScan_EnableAutoPoweroff(TRUE);
    KeyScan_EnableUSBDet(TRUE);

    /* Stop RTCGet timer if exists */
    if(g_uiRTCGetTimerID != NULL_TIMER)
    {
        KeyScan_stopTimer(&g_uiRTCGetTimerID);
    }

    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_UP);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_DOWN);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_LEFT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_RIGHT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_ZOOMIN);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_ZOOMOUT);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_ENTER);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_SHUTTER2);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_MODE);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_MENU);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_PLAYBACK);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnKeyDel(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UIMenuWndPCB_SetKeyPressed(FLGKEY_DEL);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    BOOL bCurrCardRemoved = (GetCardStatus() == CARD_REMOVED)? TRUE : FALSE;
    debug_err(("UIMenuWndPCB: OnStorageInit - %s\r\n", (bCurrCardRemoved)? "MEM" : "Card"));
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnMacroChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    debug_err(("UIMenuWndPCB: OnMacroChange - %s\r\n", (Get_MacroIndex() == MACRO_ON)? "ON" : "OFF"));

    /* Update window info */
    UIMenuWndPCB_UpdateWndInfo();

    /* Redraw all window OSD */
    UxCtrl_SetDirty(pCtrl, TRUE);

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Update window info */
    UIMenuWndPCB_UpdateWndInfo();

    /* Redraw all window OSD */
    UxCtrl_SetDirty(pCtrl, TRUE);

    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPCB_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVTEVT event;

    event = paramArray[0];
    debug_ind(("UIMenuWndPCB OnTimer event = 0x%x\r\n", event));

    switch(event)
    {
        case NVTEVT_1SEC_TIMER:
        {
            /**************************************************************************************
            **
            ** 1sec Timeout Action
            **
            **************************************************************************************/
            /* Update window info */
            UIMenuWndPCB_UpdateWndInfo();

            /* Redraw all window OSD */
            UxCtrl_SetDirty(pCtrl, TRUE);
            break;
        }

        default:
            break;
    }

    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPCB_BackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPCB_Background)
CTRL_LIST_END

//----------------------UIMenuWndPCB_BackgroundCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_Background)
EVENT_END

//---------------------UIMenuWndPCB_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPCB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPCB_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndPCB_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_TitleBar)
EVENT_END

//----------------------UIMenuWndPCB_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_TitleName)
EVENT_END

//---------------------UIMenuWndPCB_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPCB_TipsBar)
CTRL_LIST_END

//----------------------UIMenuWndPCB_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_TipsBar)
EVENT_END

//----------------------UIMenuWndPCB_StatusICN_BatteryCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_StatusICN_Battery)
EVENT_END

//----------------------UIMenuWndPCB_StaticTXT_RTCCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_StaticTXT_RTC)
EVENT_END

//----------------------UIMenuWndPCB_StatusICN_MacroCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_StatusICN_Macro)
EVENT_END

//----------------------UIMenuWndPCB_StatusICN_StorageCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_StatusICN_Storage)
EVENT_END

//----------------------UIMenuWndPCB_StaticTXT_FwVerCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_StaticTXT_FwVer)
EVENT_END

//---------------------UIMenuWndPCB_PNL_KFrameCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPCB_PNL_KFrame)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K1)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K2)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K3)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K4)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K5)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K6)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K7)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K8)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K9)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K10)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K11)
CTRL_LIST_ITEM(UIMenuWndPCB_BtnTXT_K12)
CTRL_LIST_END

//----------------------UIMenuWndPCB_PNL_KFrameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_PNL_KFrame)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K1)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K2)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K3)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K4)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K5Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K5)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K6Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K6)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K7Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K7)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K8Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K8)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K9Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K9)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K10Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K10)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K11Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K11)
EVENT_END

//----------------------UIMenuWndPCB_BtnTXT_K12Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndPCB_BtnTXT_K12)
EVENT_END

//-----------------------------------------------------------------------------
// UIMenuWndPCB User Functions
//-----------------------------------------------------------------------------
static void UIMenuWndPCB_UpdateWndInfo(void)
{
    UINT32 uiValue = 0;
    UINT32 i;

    /* Update status item data */
    uiValue = (GetCardStatus() == CARD_REMOVED)? UIMenuWndPCB_StatusICN_Storage_ICON_INTERNAL_FLASH : UIMenuWndPCB_StatusICN_Storage_ICON_SD_CARD;
    UxState_SetData(&UIMenuWndPCB_StatusICN_StorageCtrl,STATE_CURITEM,uiValue);
    UxState_SetData(&UIMenuWndPCB_StatusICN_BatteryCtrl,STATE_CURITEM,GetBatteryLevel());
    UxState_SetData(&UIMenuWndPCB_StatusICN_MacroCtrl,STATE_CURITEM,Get_MacroIndex());
    UxStatic_SetData(&UIMenuWndPCB_StaticTXT_RTCCtrl,STATIC_VALUE,Txt_Pointer(UIMenuWndPCB_GetRTCString()));
    UxStatic_SetData(&UIMenuWndPCB_StaticTXT_FwVerCtrl,STATIC_VALUE,Txt_Pointer(GetVersionString()));
    for(i=0; i < MAX_KEY_NUM; i++)
    {
        UxButton_SetItemData(g_PcbKeyCtrlTbl[i].pKeyBtnCtrl,BUTTON_ONE,BTNITM_STRID,Txt_Pointer(g_PcbKeyCtrlTbl[i].strKeyName));
    }

    /* Always show/hidden when updating */
    UxCtrl_SetShow(&UIMenuWndPCB_StatusICN_StorageCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndPCB_StatusICN_BatteryCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndPCB_StatusICN_MacroCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndPCB_StaticTXT_RTCCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndPCB_StaticTXT_FwVerCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndPCB_PNL_KFrameCtrl,TRUE);
    for(i=0; i < MAX_KEY_NUM; i++)
    {
        UxCtrl_SetShow(g_PcbKeyCtrlTbl[i].pKeyBtnCtrl,TRUE);
    }
}

static CHAR *UIMenuWndPCB_GetRTCString(void)
{
    RTC_DATE Date;
    RTC_TIME Time;

    Date = rtc_getDate();
    Time = rtc_getTime();
    sprintf(g_cRTCStr, "");
    snprintf(g_cRTCStr, MAX_RTC_STR_LEN, "%04d/%02d/%02d  %02d:%02d:%02d",
        Date.s.year, Date.s.month, Date.s.day,
        Time.s.hour, Time.s.minute, Time.s.second);

    return g_cRTCStr;
}

static void UIMenuWndPCB_SetKeyPressed(UINT32 uiKeyCode)
{
    UINT32 uiBtnStatus = 0;
    UINT32 i;

    for(i=0; i < PCB_KEY_TOTAL_NUM; i++)
    {
        if(uiKeyCode == g_PcbKeyCtrlTbl[i].uiKeyCode)
        {
            uiBtnStatus = UxButton_GetItemData(g_PcbKeyCtrlTbl[i].pKeyBtnCtrl,BUTTON_ONE,BTNITM_STATUS);

            if((uiBtnStatus & STATUS_FOCUS_MASK) & STATUS_FOCUS_BIT)
            {
                UxButton_SetItemData(g_PcbKeyCtrlTbl[i].pKeyBtnCtrl,BUTTON_ONE,BTNITM_STATUS,(STATUS_ENABLE|STATUS_NORMAL_BIT));
            }
            else
            {
                UxButton_SetItemData(g_PcbKeyCtrlTbl[i].pKeyBtnCtrl,BUTTON_ONE,BTNITM_STATUS,(STATUS_ENABLE|STATUS_FOCUS_BIT));
            }
            break;
        }
    }
}

