//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "SysCfg.h"
#include "PhotoTsk.h"
#include "PhotoDisTsk.h"
#include "FileSysTsk.h"
#include "PrimaryTsk.h"
#include "KeyScanTsk.h"
#include "UIFlowWndCommonAPI.h"
#include "UIMenuWndMovieVideo.h"
//#include "UIMenuWndPhotoQuickSetting.h"
#include "UIPhotoObj.h"
#include "UIMovieObj.h"
#include "UISystemObj.h"
#include "UISystemStatusSettings.h"
#include "UIFlowWndMovieRes.c"
#include "UIFlowWndMovie.h"
#include "UIFlowWndWrnMsg.h"
#include "rtc.h"
#include "MediaRecAPI.h"
#if (_MOVIE_PIM_MODE_ == ENABLE)
#include "RawEncApi.h"
#endif
#include "GPS.h"
#include "Gsensor.h"
#include "UICustomer.h"
#include "PlaybackTsk.h"
#include "Alg_IPLMode.h"
#include "UIMenuSetupSettings.h"

//---------------------UIFlowWndMovieCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie)
CTRL_LIST_ITEM(UIFlowWndMovie_Static_camera)
CTRL_LIST_ITEM(UIFlowWndMovie_Status_battery)
CTRL_LIST_ITEM(UIFlowWndMovie_Panel)
CTRL_LIST_ITEM(UIFlowWndMovie_Static_time)
CTRL_LIST_ITEM(UIFlowWndMovie_Static_maxtime)
CTRL_LIST_ITEM(UIFlowWndMovie_Static_resolution)
CTRL_LIST_ITEM(UIFlowWndMovie_Zoom_Static)
CTRL_LIST_ITEM(UIFlowWndMovie_YMD_Static)
CTRL_LIST_ITEM(UIFlowWndMovie_HMS_Static)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_Storage)
CTRL_LIST_ITEM(UIFlowWndMovie_StaticIcon_PIM)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_CyclicRec)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_MotionDet)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_LEDLight)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_Audio)
CTRL_LIST_ITEM(UIFlowWndMovie_StaticIcon_Lock)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_Color)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_EV)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_WB)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_GSENSOR)
CTRL_LIST_ITEM(UIFlowWndMovie_Speed)
CTRL_LIST_ITEM(UIFlowWndMovie_GPS)
CTRL_LIST_ITEM(UIFlowWndMovie_StatusICN_GPS)
CTRL_LIST_END

//----------------------UIFlowWndMovieCtrl Event---------------------------
INT32 UIFlowWndMovie_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnKeyDisplay(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnMovieFinish(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnMovieFull(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnMovieWrError(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnOZoomStepChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnDZoomStepChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnMacroChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnOSDReflash(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnCultNormal(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMovie_OnAutoRecordStop(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIFlowWndMovie)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndMovie_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndMovie_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndMovie_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndMovie_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndMovie_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndMovie_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndMovie_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndMovie_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIFlowWndMovie_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIFlowWndMovie_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIFlowWndMovie_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndMovie_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndMovie_OnKeyPlayback)
EVENT_ITEM(NVTEVT_KEY_DISPLAY,UIFlowWndMovie_OnKeyDisplay)
EVENT_ITEM(NVTEVT_BATTERY,UIFlowWndMovie_OnBattery)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndMovie_OnChildClose)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH,UIFlowWndMovie_OnMovieFinish)
EVENT_ITEM(NVTEVT_CB_MOVIE_ONE_SEC,UIFlowWndMovie_OnMovieOneSec)
EVENT_ITEM(NVTEVT_CB_MOVIE_FULL,UIFlowWndMovie_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_WR_ERROR,UIFlowWndMovie_OnMovieWrError)
EVENT_ITEM(NVTEVT_CB_OZOOMSTEPCHG,UIFlowWndMovie_OnOZoomStepChange)
EVENT_ITEM(NVTEVT_CB_DZOOMSTEPCHG,UIFlowWndMovie_OnDZoomStepChange)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIFlowWndMovie_OnStorageChange)
EVENT_ITEM(NVTEVT_MACRO_CHANGE,UIFlowWndMovie_OnMacroChange)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndMovie_OnTimer)
EVENT_ITEM(NVTEVT_OSD_REFLASH,UIFlowWndMovie_OnOSDReflash)
EVENT_ITEM(NVTEVT_CB_MOVIE_CULT_NORMAL,UIFlowWndMovie_OnCultNormal)
EVENT_ITEM(NVTEVT_MOVIEAUTORECORDSTOP,UIFlowWndMovie_OnAutoRecordStop)


EVENT_END

//------------------------------------------------------------
#define _UIRECAVI_DBG_MSG_              1
#if _UIRECAVI_DBG_MSG_
    #include "Debug.h"
    #define DbgMsg_UIRecAvi(msg)        debug_msg msg
    #define DbgCode_UIRecAvi(x)         x
#else
    #define DbgMsg_UIRecAvi(msg)
    #define DbgCode_UIRecAvi(x)
#endif

// Movie mode key mask
#define MOVIE_KEY_PRESS_MASK        (FLGKEY_KEY_MASK_DEFAULT)
//#define MOVIE_KEY_RELEASE_MASK      (FLGKEY_ZOOMIN | FLGKEY_ZOOMOUT)
#define MOVIE_KEY_RELEASE_MASK      (FLGKEY_ZOOMIN | FLGKEY_ZOOMOUT | FLGKEY_UP | FLGKEY_DOWN)

//#define MOVIERECORD_KEY_PRESS_MASK  (FLGKEY_ZOOMIN | FLGKEY_ZOOMOUT | FLGKEY_SHUTTER2 | FLGKEY_MODE | FLGKEY_RIGHT)
#define MOVIERECORD_KEY_PRESS_MASK  (FLGKEY_ZOOMIN | FLGKEY_ZOOMOUT | FLGKEY_SHUTTER2 | FLGKEY_MODE | FLGKEY_UP | FLGKEY_DOWN | FLGKEY_RIGHT | FLGKEY_ENTER|FLGKEY_MENU)
//#define MOVIEERR_KEY_PRESS_MASK     (FLGKEY_MENU|FLGKEY_UP|FLGKEY_DOWN|FLGKEY_LEFT|FLGKEY_RIGHT|FLGKEY_MODE|FLGKEY_PLAYBACK)
#define TIMER_ONE_SEC               1000
#define TIMER_HALF_SEC               500
//------------------------------------------------------------
CHAR    gUIAviRecMaxTimeStr[20] = {0};
CHAR    gUIAviRecCurTimeStr[20] = {0};
__align(4)  GPSDATA gpsdata={0};

BOOL    gUIFlashAviIsRecording = FALSE;
BOOL    gUIAviIsRecording = FALSE;
BOOL    gUIAviStoreFull = FALSE;
UINT32  gUIAviRecMaxTime = 0;
UINT32  gUIAviRecCurTime = 0;
UINT32  gUIAviSelfTimerSec = 0;
UINT32  gUIAviTimerID = NULL_TIMER;
UINT32  g_uiUpdateSpeedTimerID = NULL_TIMER;
extern BOOL bStarMovie;
extern BOOL gbKscanTVPlug;

extern BOOL GPSStatus;
extern UINT32 GPSTime_Y;
extern UINT32 GPSTime_M;
extern UINT32 GPSTime_D;
extern UINT32 GPSTime_H;
extern UINT32 GPSTime_Mi;
extern UINT32 GPSTime_S;
extern UINT32 GPSDataCounter;
BOOL GPSDataInputFlag = FALSE;
extern BOOL ACC5MinMode;
BOOL GPSSetTime = TRUE;

// MOVIE mode child window mode
typedef enum
{
    MOVIE_CHILD_WND_NULL        = 0,
    MOVIE_CHILD_WND_MENU,
    MOVIE_CHILD_WND_QUICKSETTING,
    MOVIE_CHILD_WND_WRNMSG
} MOVIE_CHILD_WND;

static UINT32   g_uiChildWndMode = MOVIE_CHILD_WND_NULL;
static UINT32   gHistogram_show_timer = NULL_TIMER;
static UINT32   g_uiTimeTimerID = NULL_TIMER;
static CHAR resolution_Buf[MOVIE_SIZE_SETTING_MAX][10]=
{
    "720P",
    "WVGA",
    "VGA",
    "QVGA"
};
static CHAR        date_str[20];
static CHAR        time_str[20];
static UINT32      g_uiMaskKeyPress         = MOVIE_KEY_PRESS_MASK;
static UINT32      g_uiMaskKeyRelease       = MOVIE_KEY_RELEASE_MASK;
static BOOL        g_bPIMReady              = FALSE;
static BOOL        g_uiRecordIngMotionDet   = FALSE;
static UINT32      gUIMotionDetTimerID      = TIMER_NULL;
//static BOOL   g_bManualStop         = FALSE;

BOOL gbMoviFileLock = FALSE;

#define	 MAX_GFILE_NUM	(6)
#define	 GFILE_FOLDER	"CRASH"
static CHAR		GFileName[MAX_GFILE_NUM][32] = {0};
static UINT32		sUIGfileNum = 0;
static UINT32		sUIGFileFileID = 1000;
static CHAR		CCrashFolderName[32] = {0};
UINT32 uiImageRotatePreValue = 0;
static CHAR  Speed_buf[20];
extern UINT32 Speed[2];
extern UINT32 SP_1[12];
static CHAR  SP_buf[20];

#if 0
static CHAR dzoom_Buf[MOVIE_DZOOM_SETTING_MAX][10]=
{
    "*1.0",
    "*2.0",
    "*3.0",
    "*4.0"
};
#endif
static UINT32 FlowMovie_CheckMemoryForCyclicRec(UINT32 uiCyclicRecTime);

void UIFlowWndMovie_OnExeLockFile(BOOL En)
{
     debug_err(("------------gbMoviFileLock : %d-----------\r\n",En));	
	gbMoviFileLock = En;
}

void GFILE_CreateFolder(CHAR *FolderName)
{
	HNVT_FILE *pFile;
	CHAR	TempFile[] = "\\DEMO.txt";
	CHAR 	TempPath[32] = {0};

	strcpy(TempPath, FolderName);
	strcat(TempPath, TempFile);
	pFile = fs_fopen(TempPath,"w");
	if(pFile == NULL)
	{
		debug_err(("open file error\r\n"));
	}
	fs_fclose(pFile);   

	FilesysDeleteByName(TempPath,FALSE);
}

void GFile_ClearGFileFolder(void)
{
	UINT32	i = 0;

	memset(CCrashFolderName, 0, 32);
	for (i = 0; i < MAX_GFILE_NUM; i ++)
	{
		memset(GFileName[i], 0, 32);
	}
	sUIGfileNum = 0;
}

void GFile_SearchActiveCrashFolder(void)
{
	UINT32	TotalFileNum = 0, i;
	UH		DirID = 99, FileID = 0;
	BOOL	Find = FALSE;
	CHAR	TempFile[32] = {0}, SrcFileName[32] = "A:\\DCIM\\100CRASH\\00000001.AVI";
	CHAR	*pSrcFileName;
	CHAR	CharDirID[3] = {0};

	if (CCrashFolderName[0] != 0)
	{
		debug_err(("Crash folder exist already, %s\r\n",CCrashFolderName));
		return;
	}

	TotalFileNum = PB_GetCurrFileSysInfo(PLAYFILEINFO_FILENUMS);

	if (TotalFileNum > 0)
	{
		for (i = 1; i <= TotalFileNum; i ++)
		{
			FilesysGetDCFIDBySeq(i, &DirID, &FileID);
			FilesysGetDCFFileName(SrcFileName, DirID, FileID, FST_FMT_AVI);
			debug_err(("ID (%d, %d)\tSrcFileName = %s, SrcFileName[11] = %c\r\n",DirID, FileID, SrcFileName,SrcFileName[11]));
			pSrcFileName = SrcFileName + 11;

			if (!strncmp(pSrcFileName, GFILE_FOLDER, 5))
			{
				Find = TRUE;
				break;
			}
		}
	}
		
	if (Find)
	{
		for (i = 0; i <= 15; i ++)
		{
			CCrashFolderName[i] = SrcFileName[i];
		}
		debug_err(("Crash folder exist,did not create!!!\r\n"));
	}
	else
	{
		DirID ++;
		if (DirID > 999)
		{
			DirID = 100;
		}
		for (i = 0; i <= 10; i ++)
		{
			CCrashFolderName[i] = SrcFileName[i];
		}
		CCrashFolderName[8] = DirID / 100 + '0';		//Num + '0' switch to ASCII code.
		CCrashFolderName[9] = (DirID % 100) / 10 + '0';
		CCrashFolderName[10] = (DirID % 10) + '0';
		strcat(CCrashFolderName, GFILE_FOLDER);
		debug_err(("Crash folder did not exist,create it!!!\r\n"));
		GFILE_CreateFolder(CCrashFolderName);
	}
	debug_err(("CCrashFolderName is %s \r\n",CCrashFolderName));
}

void GFile_MoveFileToCrashFolder(UINT32 FileID, UINT32 DirID, CHAR *pDstFileName)
{
	CHAR	SrcFileName[32] = {0}, DstFileName[32] = {0}, i;
	CHAR	*pSrcFileName,  ReNameFileName[32] = {0};
	int		rval = 0;

	sUIGFileFileID ++;
	if (sUIGFileFileID > 9999)
	{
		sUIGFileFileID = 1;
	}

	FilesysGetDCFFileName(SrcFileName, DirID, FileID, FST_FMT_AVI);

	debug_err(("\r\nSOURCE NAME %s \r\n",SrcFileName));
	
	pSrcFileName = SrcFileName + 16;
	strcpy(DstFileName, CCrashFolderName);
	strcat(DstFileName, pSrcFileName);

	DstFileName[21] = sUIGFileFileID / 1000 + '0';
	DstFileName[22] = (sUIGFileFileID % 1000) / 100 + '0';
	DstFileName[23] = (sUIGFileFileID % 100) / 10 + '0';
	DstFileName[24] = sUIGFileFileID % 10 + '0';

	for (i = 17; i < 32; i ++)	//Rename file in the same folder.
	{
		ReNameFileName[i - 17] = DstFileName[i];
	}

	debug_err(("rename %s to %s,result = %d\r\n",SrcFileName,ReNameFileName,rval));

	rval = FilesysRename(ReNameFileName, SrcFileName, FALSE, TRUE);

	for (i = 17; i < 32; i ++)
	{
		SrcFileName[i] = ReNameFileName[i - 17];
	}
	
	rval = FilesysMoveFile(SrcFileName, DstFileName);	//Move to CRASH folder.

	debug_err(("move %s to %s,result = %d\r\n\r\n",SrcFileName,DstFileName,rval));
	
	FilesysSetAttribByName(DstFileName,FST_ATTRIB_READONLY,TRUE);
		
	for (i = 0; i < 32; i ++)
	{
		*(pDstFileName + i) = DstFileName[i];
	}
}


void GFILE_SetGfile(UINT32 FileID, UINT32 DirID)
{
	INT		rval = 0, i;
	CHAR	SrcFileName[32] = {0};

	GFile_SearchActiveCrashFolder();
	GFile_MoveFileToCrashFolder(FileID, DirID, SrcFileName);
	
	if (sUIGfileNum < MAX_GFILE_NUM)
	{
		sUIGfileNum ++;
	}
	else
	{
		//Ux_OpenWindow(&UIFlowWndGsensorRecFullCtrl,0);
		rval = FilesysSetAttribByName(GFileName[0],FST_ATTRIB_READONLY,FALSE);
		rval = FilesysDeleteByName(GFileName[0], FALSE);	
		FilesysWaitInitFinish(FST_TIME_INFINITE);	 
		FilesysWaitCmdFinish(FST_TIME_INFINITE); 
		debug_err(("GFILE FULL,delete --%s-- result = %d!!!\r\n",GFileName[0],rval));
		for (i = 0; i < MAX_GFILE_NUM - 1; i ++)
		{
			strcpy(GFileName[i], GFileName[i + 1]);
		}
		memset(GFileName[MAX_GFILE_NUM - 1], 0, 32);
	}
	
	if (GFileName[sUIGfileNum - 1][0] == 0)
	{
		debug_err(("sUIGfileNum = %d, FileName = %s !!!\r\n",sUIGfileNum,SrcFileName));
		strcpy(GFileName[sUIGfileNum - 1], SrcFileName);
	}
	else
	{
		debug_err(("GFILE OVERRIDE!!!\r\n"));
	}

	for (i = 0; i < MAX_GFILE_NUM; i ++)
	{
		debug_err(("GFileName[%d] = %s!!!\r\n",i,GFileName[i]));
	}

}

void UIFlowWndMovie_SetPIMReady(BOOL bReady)
{
    g_bPIMReady = bReady;
}

BOOL UIFlowWndMovie_CheckPIMReady(void)
{
    return g_bPIMReady;
}

void UIFlowWndMovie_DrawPIM(BOOL bDraw)
{
    UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_PIMCtrl, bDraw);
}

static void FlowMovie_DrawMaxRecTime(BOOL bDraw)
{
    memset((void *)gUIAviRecMaxTimeStr, 0, sizeof(gUIAviRecMaxTimeStr));
    gUIAviRecMaxTime = UIRecMovie_GetData(RECMOVIE_MAXSECOND);
    DbgMsg_UIRecAvi(("DrawMaxRecTime:bDraw=%d,gUIAviRecMaxTime=%d\r\n", bDraw, gUIAviRecMaxTime));
    if (GPIOMap_DetStrgCard() == FALSE)
    {
        gUIAviStoreFull = TRUE;
        gUIAviRecMaxTime = 0;	
    }	
    else
    {
    if (gUIAviRecMaxTime <= 1)
    {
        DbgMsg_UIRecAvi(("Storage Full\r\n"));
        gUIAviStoreFull = TRUE;
        gUIAviRecMaxTime = 0;
    }
    else if (gUIAviRecMaxTime > 86399)
    {   ///23:59:59
        DbgMsg_UIRecAvi(("Max-Rec-Time=%d > 23:59:59\r\n", gUIAviRecMaxTime));
        gUIAviRecMaxTime = 86399;
    }
    }
    sprintf(gUIAviRecMaxTimeStr,"%02d:%02d:%02d", gUIAviRecMaxTime/3600,(gUIAviRecMaxTime%3600)/60, (gUIAviRecMaxTime%3600)%60);
    UxStatic_SetData(&UIFlowWndMovie_Static_maxtimeCtrl,STATIC_VALUE,Txt_Pointer(gUIAviRecMaxTimeStr));
    if (Get_MovieGodBlessIndex()==MOVIE_GODBLESS_ON)
    {
        UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl, FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_timeCtrl, FALSE);
    } else {
        UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl, bDraw);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_timeCtrl, !bDraw);
    }
}
static void FlowMovie_DrawRecTime(BOOL bDraw, UINT32 recTime)
{
    if(gUIAviIsRecording == TRUE)
    {
        gUIAviRecCurTime = recTime;
        memset((void *)gUIAviRecCurTimeStr, 0, sizeof(gUIAviRecCurTimeStr));
        sprintf(gUIAviRecCurTimeStr,"%02d:%02d:%02d", recTime/3600,(recTime%3600)/60, (recTime%3600)%60);
        DbgMsg_UIRecAvi(("#%s \r\n",gUIAviRecCurTimeStr));
        UxStatic_SetData(&UIFlowWndMovie_Static_timeCtrl,STATIC_VALUE,Txt_Pointer(gUIAviRecCurTimeStr));
        if (Get_MovieGodBlessIndex()==MOVIE_GODBLESS_ON)
        {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_timeCtrl, FALSE);
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl, FALSE);
        } else {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_timeCtrl, bDraw);
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl, !bDraw);
        }
    }
}

static BOOL FlowMovie_IsEnvErr(BOOL bCheckCyclicRec)
{
    UINT32  maskKey = (FLGKEY_MENU|FLGKEY_UP|FLGKEY_DOWN|FLGKEY_LEFT|FLGKEY_RIGHT|FLGKEY_ENTER);//FLGKEY_UP=MENU,FLGKEY_DOWN=MODE
    BOOL    retV = FALSE;
    UINT32  uiMsg;

    if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
    {
        debug_err(("#Card locked\r\n"));
        DbgMsg_UIRecAvi(("#Card locked \r\n"));
        maskKey |= FLGKEY_PLAYBACK;
        g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
        retV = TRUE;
        return retV;
    }

    if(UI_Validate_Storage(STORAGE_CHECK_ERROR, NULL) == FALSE)
    {
        DbgMsg_UIRecAvi(("#IntrMem Full \r\n"));
        g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
        #if ((_PSTOREDEVICE_ == _PSTOREDEVICE_SPIFLASH_) && (_RAM_DISK_ == DISABLE))
        uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_NO_CARD : FLOWWRNMSG_ISSUE_CARD_ERR;
        #else
        uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_MEM_ERR : FLOWWRNMSG_ISSUE_CARD_ERR;
        #endif
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,uiMsg,FLOWWRNMSG_TIMER_KEEP);
        retV = TRUE;
        return retV;
    }

    if(UI_Validate_Storage(STORAGE_CHECK_FULL, &(gUIAviRecMaxTime)) == FALSE)
    {
        gUIAviStoreFull = TRUE;
        gUIAviRecMaxTime = 0;
        maskKey |= FLGKEY_PLAYBACK;
        DbgMsg_UIRecAvi(("#Card Full \r\n"));

        if (GetCardStatus() == CARD_REMOVED)
        {
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
        }
        else
        {

	        if (Get_MovieCyclicRecTime() != 0)
	        {
                  debug_err(("#Card Full Get_MovieCyclicRecTime : %d\r\n",Get_MovieCyclicRecTime()));			        
	            FlowMovie_CheckMemoryForCyclicRec(Get_MovieCyclicRecTime());
			return FALSE;
		 }            
		else
		{
                 g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
                 Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_FULL,FLOWWRNMSG_TIMER_2SEC);
		}
        }
        retV = TRUE;
        return retV;
    }

    retV = FALSE;
    return retV;
}

static void FlowMovie_StopRec(BOOL stopLib)
{
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_NULL);
    Ux_FlushEvent();

    UxCtrl_SetShow(&UIFlowWndMovie_PanelCtrl,FALSE);

    if (stopLib == TRUE)
    {
        Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_STOP_RECAVI,NULL);
    }
    else
    {
        KeyScan_EnableAutoPoweroff(TRUE);
        KeyScan_EnableUSBDet(TRUE);
        gUIAviIsRecording = FALSE;
        FlowMovie_DrawMaxRecTime(TRUE);
    if(gbKscanTVPlug == FALSE){	
	  KeyScan_EnableLEDToggle(KEYSCAN_LED_GREEN, FALSE);
	  KeyScan_TurnOnLED(KEYSCAN_LED_GREEN);	}
 	  if(gbMoviFileLock == TRUE)
	  {
	 	UIFlowWndMovie_OnExeLockFile(FALSE);	    		
	 	UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl, FALSE);	
	  }	  
        KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    }
}

static void FlowMovie_StopDownTimer(void)
{
    if (gUIAviTimerID != NULL_TIMER)
    {
        KeyScan_stopTimer(&gUIAviTimerID);
        gUIAviTimerID = NULL_TIMER;
    }
    gUIAviSelfTimerSec = 0;
}

static UINT32 FlowMovie_CheckMemoryForCyclicRec(UINT32 uiCyclicRecTime)
{
    UH      uhDirID = 1, uhFileID = 1;
    UINT32  err;

    while (uiCyclicRecTime > MediaRec_Disk2Second())
    {
        // always get oldest (1st) DCF file
        FilesysWaitInitFinish(FST_TIME_INFINITE);
        FilesysWaitCmdFinish(FST_TIME_INFINITE);
        err = FilesysGetDCFIDBySeq(1, &uhDirID, &uhFileID);
        FilesysWaitCmdFinish(FST_TIME_INFINITE);

        // check if there is no DCF file then stop
        if (uhDirID == 0 && uhFileID == 0)
        {
            debug_err(("[Cyclic Rec]: No DCF file\r\n"));
            break;
        }

        // check if file is protected; if yes, unlock it
        FilesysSetFileLock(uhFileID, uhDirID, FALSE);
        FilesysWaitCmdFinish(FST_TIME_INFINITE);

        // erase file
        debug_ind(("[Cyclic Rec]: Erase file: DirID = %d, FileID = %d\r\n", uhDirID, uhFileID));
        err = FilesysDeleteFile(uhDirID, uhFileID, FST_FMT_ANYFORMAT);
        FilesysWaitCmdFinish(FST_TIME_INFINITE);
    }

    if (uiCyclicRecTime > MediaRec_Disk2Second()) // still no enough space for recording one period
    {
        return FALSE;
    }

    return TRUE;
}

static void FlowMovie_StartRec(void)
{
    if (gUIAviSelfTimerSec == 0)
    {
        gUIAviIsRecording = TRUE;
        gUIFlashAviIsRecording = FALSE;
        gUIAviRecCurTime = 0;
        UIFlowWndMovie_SetPIMReady(TRUE);
        KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_NULL);
        Ux_FlushEvent();
        Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_START_RECAVI,NULL);
        KeyScan_EnableAutoPoweroff(FALSE); //disable auto poweroff,while recording
        KeyScan_EnableUSBDet(FALSE);       //disable USB detect,while recording
        KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, MOVIERECORD_KEY_PRESS_MASK);
    }
    else
    {
        debug_err(("FlowMovie_StartRec: Not yet,gUIAviSelfTimerSec=%d\r\n", gUIAviSelfTimerSec));
    }
}

static BOOL FlowMovie_ChkDrawStoreFullFolderFull(void)
{
    if(UI_Validate_Storage(STORAGE_CHECK_FULL, &(gUIAviRecMaxTime)) == FALSE)
    {
        gUIAviStoreFull = TRUE;
        gUIAviRecMaxTime = UIRecMovie_GetData(RECMOVIE_MAXSECOND);
        if (GetCardStatus() == CARD_REMOVED)
        {
            DbgMsg_UIRecAvi(("@IntrMem Full \r\n"));
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_KEEP);
            return TRUE;
        }
        else
        {
            DbgMsg_UIRecAvi(("@Card Full \r\n"));
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_FULL,FLOWWRNMSG_TIMER_KEEP);
            return TRUE;
        }
    }
    return FALSE;
}

static UINT32 UIFlowWndMovie_CheckRec(UINT32 state)
{
    // don't allow recording as HDMI inserted due to bandwidth issue
    if (KeyScan_IsHDMIPlugIn() == TRUE)
    {
        //Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_MEM_FULL,FLOWWRNMSG_TIMER_2SEC);
        return NVTEVT_CONSUME;
    }

    if (gUIAviIsRecording == TRUE)
    {
        if (gUIAviRecCurTime >= 1) // need to record 1 sec at least
        {
            DbgMsg_UIRecAvi(("Stop Rec Avi, Save Avi File\r\n"));
            //g_bManualStop = TRUE;
            //FlowMovie_StopRec(TRUE);

            // recording again because this case is cut fail !!

            if (state==UIFlowWndMovie_Restart_Rec)
            {
               FlowMovie_StopRec(FALSE);
               Ux_PostEvent(NVTEVT_KEY_ENTER, 2, NVTEVT_KEY_PRESS, FLGKEY_PRESSED);
            } else {
               FlowMovie_StopRec(TRUE);
               if (Get_MovieMotionDetIndex()==MOVIE_MOTIONDET_ON)
                {
                    if (g_uiRecordIngMotionDet == TRUE)
                    {
                        //g_uiRecordIngMotionDet = FALSE;
			    //Set_MovieMotionDetIndex(MOVIE_MOTIONDET_OFF);						
                    }
                }
            }
        }
    }
    else
    {
        if (FlowMovie_IsEnvErr(TRUE) == TRUE)
        {
            return NVTEVT_CONSUME;
        }

        if (gUIAviTimerID != NULL_TIMER)
        {
            DbgMsg_UIRecAvi(("Shutter2 during Count-Down,Stop Self-Timer\r\n"));
            FlowMovie_StopDownTimer();
            return NVTEVT_CONSUME;
        }

//        UxCtrl_SetShow(&UIFlowWndMovie_StaticText_ReadyCtrl,FALSE);
//        UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_RecordCtrl,TRUE);
        gUIAviSelfTimerSec = 0; //0 seconds
        gUIAviStoreFull = FALSE;
        DbgMsg_UIRecAvi(("Start Rec Avi:d=%d,f=%d\r\n",Get_FilesysDirId(),Get_FilesysFileId()));
        //#NT#2009/03/03#Photon Lin -begin
        //FilesysSetWriteNextFileId(((UINT16)Get_FilesysDirId()), ((UINT16)Get_FilesysFileId()), FALSE);
        //#NT#2009/03/03#Photon Lin -end
/*
        if (Get_MovieMotionDetIndex()==MOVIE_MOTIONDET_ON)
        {
            g_uiRecordIngMotionDet = TRUE;
        } else {
            g_uiRecordIngMotionDet = FALSE;
        }
        */
	
        FlowMovie_StartRec();
    }
    //Ux_DefaultEvent(pCtrl,NVTEVT_KEY_ENTER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

static void UIFlowWndMovie_OnExePIM(void)
{
#if (_MOVIE_PIM_MODE_ == ENABLE)
    ACTFBADDR_PRAM gTempFBAddr;
    RAW_ENC_OBJ RawEncObj;

    UINT32  uiPoolAddr;
    UINT32  y1, cb1, cr1;
    UINT8   status;
    UINT32  sec, unsafe;

    if (!UIFlowWndMovie_CheckPIMReady())
        return;

    debug_msg("encode one...\r\n");
    //sec = MediaRec_Disk2Second();
    //MediaRec_SetDisk2SecRestriction(MEDIAREC_RESTR_INDEXBUF,0);
    //sec = MediaRec_Disk2SecondWithType(MEDIAREC_COUNTTYPE_FS,0);//AVIRec_Disk2Second();
    unsafe = MediaRec_CheckUnsavedFileBlocks();
    //debug_msg("recording sec=%d, before RAWENC\r\n", sec);
    if (((gUIAviRecMaxTime-gUIAviRecCurTime)>3)&&(unsafe == 0))
    {
        UIFlowWndMovie_SetPIMReady(FALSE);
        UIFlowWndMovie_DrawPIM(TRUE);
        //#NT#2010/09/06#Meg Lin -begin
        //GetActImgFBAddr_Path2(&gTempFBAddr);
        MediaRec_GetActVideoAddr(&gTempFBAddr);
        //#NT#2010/09/06#Meg Lin -end

        //debug_msg("y=0x%lx, 2=0x%lx, 3=0x%lx!\r\n", gTempFBAddr.y_addr, gTempFBAddr.cb_addr, gTempFBAddr.cr_addr);
        RawEnc_SetRawAddr2Encode(gTempFBAddr.y_addr, gTempFBAddr.cb_addr, gTempFBAddr.cr_addr, gTempFBAddr.SrcYLineOffset);//2010/03/19 Meg Lin
    }
    else
    {
        if (unsafe)
        {
            debug_err(("unsafe to take picture !\r\n"));
        }
        else
        {
            debug_err(("no space to encode RAW !\r\n"));
        }
    }
#endif
}

static INT32 UIFlowWndMovie_OnExeZoomIn(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state;

    if (paramNum > 0)
        state = *paramArray;
    debug_err(("[UIFlowWndMovie_OnExeZoomIn][%d]\n\r",*paramArray));
    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_ZOOMIN,0);
        break;
    case NVTEVT_KEY_RELEASE:
        Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_ZOOMSTOP,0);
        break;
    }
    return NVTEVT_PASS;
}

static INT32 UIFlowWndMovie_OnExeZoomOut(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  state;

    if (paramNum > 0)
        state = *paramArray;
    debug_err(("[UIFlowWndMovie_OnExeZoomOut][%d]\n\r",*paramArray));
    switch(state)
    {
    case NVTEVT_KEY_PRESS:
        Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_ZOOMOUT,0);
        break;
    case NVTEVT_KEY_RELEASE:
        Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_ZOOMSTOP,0);
        break;
    }
    return NVTEVT_PASS;
}

static INT32 UIFlowWndMovie_OnExeRecord(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 1
    UINT32  state;

    if (paramNum >= 3)
        state = paramArray[2];
	
    if (GPIOMap_DetStrgCard() == FALSE)
    {
        g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
        return NVTEVT_CONSUME;		
    }
	
    if(UI_Validate_Storage(STORAGE_CHECK_CLUSTER, NULL) == FALSE)
    {
        g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CLUSTER_WRONG,FLOWWRNMSG_TIMER_3SEC);
        return;
    }
	
    UIFlowWndMovie_CheckRec(state);
#else
    if (gUIAviIsRecording == TRUE)
    {
        if(gUIAviRecCurTime >= 1)
        {
            DbgMsg_UIRecAvi(("Stop Rec Avi, Save Avi File\r\n"));
            FlowMovie_StopRec(TRUE);
        }
    }
    else
    {
        if (FlowMovie_IsEnvErr(TRUE) == TRUE)
        {
            return NVTEVT_CONSUME;
        }
        if (gUIAviTimerID != NULL_TIMER)
        {
            DbgMsg_UIRecAvi(("Shutter2 during Count-Down,Stop Self-Timer\r\n"));
            FlowMovie_StopDownTimer();
            return NVTEVT_CONSUME;
        }
        UxCtrl_SetShow(&UIFlowWndMovie_PanelCtrl,TRUE);
        gUIAviSelfTimerSec = 0; ///0 seconds
        gUIAviStoreFull = FALSE;
        DbgMsg_UIRecAvi(("Start Rec Avi:d=%d,f=%d\r\n",Get_FilesysDirId(),Get_FilesysFileId()));

        FlowMovie_StartRec();
    }
    return NVTEVT_CONSUME;
#endif
}

static void UIFlowWndMovie_Update_Icon(void)
{
 AlgMsgInfo *pAlgMsgInfo = Get_AlgMsgInfo();

    if (0)//(Get_MovieGodBlessIndex()==MOVIE_GODBLESS_ON)
    {
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,FALSE);
        if(gUIAviIsRecording != TRUE)
        {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,FALSE);
            FlowMovie_DrawMaxRecTime(FALSE);
        }
        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,FALSE);
    } else {
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,TRUE);
        if(gUIAviIsRecording != TRUE)
        {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,TRUE);
            FlowMovie_DrawMaxRecTime(TRUE);
        }

        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,TRUE);
        if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN){
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);}
        else{
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);}

        UxState_SetData(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,STATE_CURITEM,Get_MovieCyclicRecIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,TRUE);
        UxState_SetData(&UIFlowWndMovie_StatusICN_MotionDetCtrl,STATE_CURITEM,Get_MovieMotionDetIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,TRUE);
        UxState_SetData(&UIFlowWndMovie_StatusICN_AudioCtrl,STATE_CURITEM,Get_MovieAudioIndex());		
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_AudioCtrl,TRUE);

        UxState_SetData(&UIFlowWndMovie_StatusICN_LEDLightCtrl,STATE_CURITEM,KeyScan_GetLedLightSta());	
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_LEDLightCtrl,FALSE);
		
        UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl,FALSE);

        UxState_SetData(&UIFlowWndMovie_StatusICN_ColorCtrl,STATE_CURITEM,Get_ColorIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_ColorCtrl,TRUE);

        UxState_SetData(&UIFlowWndMovie_StatusICN_EVCtrl,STATE_CURITEM,Get_EVIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_EVCtrl,TRUE);
        UxState_SetData(&UIFlowWndMovie_StatusICN_WBCtrl,STATE_CURITEM,Get_WBIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_WBCtrl,TRUE);		

        UxState_SetData(&UIFlowWndMovie_StatusICN_GSENSORCtrl,STATE_CURITEM,Get_MovieGsensorIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_GSENSORCtrl,TRUE);
		
    }
    
}
#if 0
static void UIFlowWndMovie_Update_Info(void)
{
    UINT32  uiMsg,uiFreePicNum;
    INT32   ev_icon_index,wb_icon_index;
    UINT32  macro_state;
    AlgMsgInfo *pAlgMsgInfo = Get_AlgMsgInfo();
    UINT32 speed_hi,speed_lo,speed_total;
	
    if (GPIOMap_DetStrgCard() == FALSE)
    {
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,FALSE);
		
        g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_KEEP);
        //return NVTEVT_CONSUME;		
    }
    else
    {
    UxStatic_SetData(&UIFlowWndMovie_Static_resolutionCtrl,STATIC_VALUE,Txt_Pointer(resolution_Buf[Get_MovieSizeIndex()]));

    //UxStatic_SetData(&UIFlowWndMovie_Zoom_StaticCtrl,STATIC_VALUE,Txt_Pointer(dzoom_Buf[Get_UIDzoomIndex()]));
    /* Update digital zoom ratio OSD string */
    UxStatic_SetData(&UIFlowWndMovie_Zoom_StaticCtrl,STATIC_VALUE,Txt_Pointer(Get_DZoomRatioString(pAlgMsgInfo)));

    if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN)
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);
    else
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);

    UxState_SetData(&UIFlowWndMovie_Status_batteryCtrl,STATE_CURITEM,GetBatteryLevel());
    UxState_SetData(&UIFlowWndMovie_StatusICN_StorageCtrl,STATE_CURITEM,(GetCardStatus() == CARD_REMOVED)? UIFlowWndMovie_StatusICN_Storage_ICON_INTERNAL_FLASH : UIFlowWndMovie_StatusICN_Storage_ICON_SD_CARD);

#if 0
    UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
#else
//update time
{
    RTC_DATE    Date;
    RTC_TIME    Time;
    Date = rtc_getDate();
    Time = rtc_getTime();
    sprintf(date_str,"%04d/%02d/%02d",Date.s.year,Date.s.month,Date.s.day);
    sprintf(time_str,"%02d:%02d:%02d",Time.s.hour,Time.s.minute,Time.s.second);
    UxStatic_SetData(&UIFlowWndMovie_YMD_StaticCtrl,STATIC_VALUE,Txt_Pointer(date_str));
    UxStatic_SetData(&UIFlowWndMovie_HMS_StaticCtrl,STATIC_VALUE,Txt_Pointer(time_str));

    switch(Get_DisplayIndex())
    {
        case DISPLAY_OFF://disappear.
            UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
            UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
            if(g_uiTimeTimerID != NULL_TIMER)
                KeyScan_stopTimer(&g_uiTimeTimerID);
            break;
        case DISPLAY_NORMAL://display normal
        case DISPLAY_ALL://displayall
            if (Get_MovieGodBlessIndex()==MOVIE_GODBLESS_ON)
            {
                UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
                UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
            } else {
                UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,TRUE);
                UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,TRUE);
            }
            if(g_uiTimeTimerID == NULL_TIMER)
                g_uiTimeTimerID = KeyScan_startTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
            break;
    }
}
#endif
//----------------------jack lan begin-----------------------------------------
		  
    sprintf(SP_buf, "SP: %d%d%d%d.%d%d%d%d.%d%d%d%d",SP_1[0],SP_1[1],SP_1[2],SP_1[3],SP_1[4],SP_1[5],SP_1[6],SP_1[7],SP_1[8],
			SP_1[9],SP_1[10],SP_1[11]);
    UxStatic_SetData(&UIFlowWndMovie_GPSCtrl,STATIC_VALUE,Txt_Pointer(SP_buf));
	
    speed_total = ((Speed[0]<<8)&&0xff00)|(Speed[1]&&0xff);
    speed_hi = speed_total/10;
    speed_lo = speed_total%10;
    sprintf(Speed_buf,"Speed: %03d.%d km/h",speed_hi,speed_lo);
    UxStatic_SetData(&UIFlowWndMovie_SpeedCtrl,STATIC_VALUE,Txt_Pointer(Speed_buf));
    switch(Get_DisplayIndex())
    {
    case DISPLAY_OFF://disappear.
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,FALSE);
        break;
    case DISPLAY_NORMAL://display normal
    case DISPLAY_ALL://displayall
        UIFlowWndMovie_Update_Icon();
#if 0
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,TRUE);
        if(gUIAviIsRecording != TRUE)
        {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,TRUE);
            FlowMovie_DrawMaxRecTime(TRUE);
        }

        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,TRUE);
        if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN)
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);
        else
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);

        UxState_SetData(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,STATE_CURITEM,Get_MovieCyclicRecIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,TRUE);
        UxState_SetData(&UIFlowWndMovie_StatusICN_MotionDetCtrl,STATE_CURITEM,Get_MovieMotionDetIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,TRUE);
#endif
        break;
#if 0
    case DISPLAY_ALL://displayall
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,TRUE);
        if(gUIAviIsRecording != TRUE)
        {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,TRUE);
            FlowMovie_DrawMaxRecTime(TRUE);
        }

        UxState_SetData(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,STATE_CURITEM,Get_MovieCyclicRecIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,TRUE);
        UxState_SetData(&UIFlowWndMovie_StatusICN_MotionDetCtrl,STATE_CURITEM,Get_MovieMotionDetIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,TRUE);
        if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN)
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);
        else
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,TRUE);
        break;
#endif
    }

    /* Not Validating storage while movie recording */
    if (gUIAviIsRecording != TRUE)
    {
        if(UI_Validate_Storage(STORAGE_CHECK_ERROR, NULL) == FALSE)
        {
            #if ((_PSTOREDEVICE_ == _PSTOREDEVICE_SPIFLASH_) && (_RAM_DISK_ == DISABLE))
            uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_NO_CARD : FLOWWRNMSG_ISSUE_CARD_ERR;
            #else
            uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_MEM_ERR : FLOWWRNMSG_ISSUE_CARD_ERR;
            #endif
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,uiMsg,FLOWWRNMSG_TIMER_KEEP);
            return;
        }
        else if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
        {
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_KEEP);
            return;
        }
        else if(UI_Validate_Storage(STORAGE_CHECK_FULL, &uiFreePicNum) == FALSE)
        {
            if (Get_MovieCyclicRecTime() == 0)
            {
                uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_NO_CARD : FLOWWRNMSG_ISSUE_CARD_FULL;
                g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
                if (GetCardStatus() == CARD_REMOVED)
                {
                    DbgMsg_UIRecAvi(("@IntrMem Full \r\n"));
                    g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
                    return;
                }
                else
                {
                    DbgMsg_UIRecAvi(("@Card Full \r\n"));
                    g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_FULL,FLOWWRNMSG_TIMER_2SEC);
                    return;
                }
            }
        }
    }    	
    return;
    	}
}
#endif

static void UIFlowWndMovie_Update_Info(void)
{
    UINT32  uiMsg,uiFreePicNum;
    INT32   ev_icon_index,wb_icon_index;
    UINT32  macro_state;
    AlgMsgInfo *pAlgMsgInfo = Get_AlgMsgInfo();
    UINT32 speed_hi,speed_lo,speed_total;
	int step;
	step = GPIOMap_DetStrgCard();
    switch (step)
    {
	case 0:
    {
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,FALSE);
		
        g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
        //return NVTEVT_CONSUME;	
        step= 1;
    }
    case 1:
    {
    UxStatic_SetData(&UIFlowWndMovie_Static_resolutionCtrl,STATIC_VALUE,Txt_Pointer(resolution_Buf[Get_MovieSizeIndex()]));

    //UxStatic_SetData(&UIFlowWndMovie_Zoom_StaticCtrl,STATIC_VALUE,Txt_Pointer(dzoom_Buf[Get_UIDzoomIndex()]));
    /* Update digital zoom ratio OSD string */
    UxStatic_SetData(&UIFlowWndMovie_Zoom_StaticCtrl,STATIC_VALUE,Txt_Pointer(Get_DZoomRatioString(pAlgMsgInfo)));

    if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN)
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);
    else
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);

    UxState_SetData(&UIFlowWndMovie_Status_batteryCtrl,STATE_CURITEM,GetBatteryLevel());
    UxState_SetData(&UIFlowWndMovie_StatusICN_StorageCtrl,STATE_CURITEM,(GetCardStatus() == CARD_REMOVED)? UIFlowWndMovie_StatusICN_Storage_ICON_INTERNAL_FLASH : UIFlowWndMovie_StatusICN_Storage_ICON_SD_CARD);

#if 0
    UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
#else
//update time
{
    RTC_DATE    Date;
    RTC_TIME    Time;
    Date = rtc_getDate();
    Time = rtc_getTime();
    sprintf(date_str,"%04d/%02d/%02d",Date.s.year,Date.s.month,Date.s.day);
    sprintf(time_str,"%02d:%02d:%02d",Time.s.hour,Time.s.minute,Time.s.second);
    UxStatic_SetData(&UIFlowWndMovie_YMD_StaticCtrl,STATIC_VALUE,Txt_Pointer(date_str));
    UxStatic_SetData(&UIFlowWndMovie_HMS_StaticCtrl,STATIC_VALUE,Txt_Pointer(time_str));

    switch(Get_DisplayIndex())
    {
        case DISPLAY_OFF://disappear.
            UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
            UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
            if(g_uiTimeTimerID != NULL_TIMER)
                KeyScan_stopTimer(&g_uiTimeTimerID);
            break;
        case DISPLAY_NORMAL://display normal
        case DISPLAY_ALL://displayall
            if (Get_MovieGodBlessIndex()==MOVIE_GODBLESS_ON)
            {
                UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
                UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
            } else {
                UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,TRUE);
                UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,TRUE);
            }
            if(g_uiTimeTimerID == NULL_TIMER)
                g_uiTimeTimerID = KeyScan_startTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
            break;
    }
}
#endif
//----------------------jack lan begin-----------------------------------------
		  
    //sprintf(SP_buf, "SP: %d%d%d%d.%d%d%d%d.%d%d%d%d",SP_1[0],SP_1[1],SP_1[2],SP_1[3],SP_1[4],SP_1[5],SP_1[6],SP_1[7],SP_1[8],
			//SP_1[9],SP_1[10],SP_1[11]);
    //UxStatic_SetData(&UIFlowWndMovie_GPSCtrl,STATIC_VALUE,Txt_Pointer(SP_buf));
	
    //speed_total = ((Speed[0]<<8)&&0xff00)|(Speed[1]&&0xff);
    //speed_hi = speed_total/10;
    //speed_lo = speed_total%10;
    //sprintf(Speed_buf,"Speed: %03d.%d km/h",speed_hi,speed_lo);
    //sprintf(Speed_buf,"Speed: %f km/h",gpsdata.rmcinfo.Speed);
    //UxStatic_SetData(&UIFlowWndMovie_SpeedCtrl,STATIC_VALUE,Txt_Pointer(Speed_buf));
    switch(Get_DisplayIndex())
    {
    case DISPLAY_OFF://disappear.
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,FALSE);
        break;
    case DISPLAY_NORMAL://display normal
    case DISPLAY_ALL://displayall
        UIFlowWndMovie_Update_Icon();
#if 0
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,TRUE);
        if(gUIAviIsRecording != TRUE)
        {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,TRUE);
            FlowMovie_DrawMaxRecTime(TRUE);
        }

        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,TRUE);
        if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN)
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);
        else
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);

        UxState_SetData(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,STATE_CURITEM,Get_MovieCyclicRecIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,TRUE);
        UxState_SetData(&UIFlowWndMovie_StatusICN_MotionDetCtrl,STATE_CURITEM,Get_MovieMotionDetIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,TRUE);
#endif
        break;
#if 0
    case DISPLAY_ALL://displayall
        UxCtrl_SetShow(&UIFlowWndMovie_Static_cameraCtrl,TRUE);
        if(gUIAviIsRecording != TRUE)
        {
            UxCtrl_SetShow(&UIFlowWndMovie_Static_maxtimeCtrl,TRUE);
            FlowMovie_DrawMaxRecTime(TRUE);
        }

        UxState_SetData(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,STATE_CURITEM,Get_MovieCyclicRecIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_CyclicRecCtrl,TRUE);
        UxState_SetData(&UIFlowWndMovie_StatusICN_MotionDetCtrl,STATE_CURITEM,Get_MovieMotionDetIndex());
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_Static_resolutionCtrl,TRUE);
        if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN)
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);
        else
            UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);
        UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_YMD_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_HMS_StaticCtrl,TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_StorageCtrl,TRUE);
        break;
#endif
    }

    /* Not Validating storage while movie recording */
    if (gUIAviIsRecording != TRUE)
    {
        if(UI_Validate_Storage(STORAGE_CHECK_ERROR, NULL) == FALSE)
        {
            #if ((_PSTOREDEVICE_ == _PSTOREDEVICE_SPIFLASH_) && (_RAM_DISK_ == DISABLE))
            uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_NO_CARD : FLOWWRNMSG_ISSUE_CARD_ERR;
            #else
            uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_MEM_ERR : FLOWWRNMSG_ISSUE_CARD_ERR;
            #endif
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,uiMsg,FLOWWRNMSG_TIMER_KEEP);
            return;
        }
        else if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
        {
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_KEEP);
            return;
        }
        else if(UI_Validate_Storage(STORAGE_CHECK_FULL, &uiFreePicNum) == FALSE)
        {
            if (Get_MovieCyclicRecTime() == 0)
            {
                uiMsg = (GetCardStatus() == CARD_REMOVED)? FLOWWRNMSG_ISSUE_NO_CARD : FLOWWRNMSG_ISSUE_CARD_FULL;
                g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
                if (GetCardStatus() == CARD_REMOVED)
                {
                    DbgMsg_UIRecAvi(("@IntrMem Full \r\n"));
                    g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_CARD,FLOWWRNMSG_TIMER_2SEC);
                    return;
                }
                else
                {
                    DbgMsg_UIRecAvi(("@Card Full \r\n"));
                    g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_FULL,FLOWWRNMSG_TIMER_2SEC);
                    return;
                }
            }
        }
    }    	
    return;
    	}
	break;
    }
}
static void UIFlowWndMovie_Initparam()
{
    Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_EXE_EV,1,Get_EVIndex());
    //Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_COLOR,1,Get_MovieColorIndex());
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_MOVIEDIS,1,MOVIE_DIS_OFF);
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_DATEIMPRINT,1,Get_MovieDateImprintIndex());
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_CYCLIC_REC,1,Get_MovieCyclicRecIndex());
    /* Video resolution setting must be set after other IQ settings */
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_MOVIESIZE,1,Get_MovieSizeIndex());

    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_GOLF_SHOT,1,Get_MovieGolfShotIndex());
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_FLASH_REC,1,Get_MovieFlashRecIndex());
    //Ux_SendEvent(&UISystemObjCtrl,NVTEVT_EXE_IMAGEROTATE,1,Get_ImageRotateIndex());
    if (Get_MovieGodBlessIndex())
    {
        //SysInit_DisplaySplashScreen(LOGO_GOD,0,0);
    }
}
INT32 UIFlowWndMovie_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
   static BOOL first = TRUE;
   
    UIFlowWndMovie_Initparam();
    /* Init window key mask variables & set key and key released mask */

    g_uiMaskKeyPress = MOVIE_KEY_PRESS_MASK;
    g_uiMaskKeyRelease = MOVIE_KEY_RELEASE_MASK;
    
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, g_uiMaskKeyPress);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, g_uiMaskKeyRelease);
     UxCtrl_SetShow(&UIFlowWndMovie_GPSCtrl, FALSE);
	 //UxCtrl_SetShow(&UIFlowWndMovie_GPSCtrl, TRUE);
     UxCtrl_SetShow(&UIFlowWndMovie_SpeedCtrl, FALSE);	
	 
	
    UIFlowWndMovie_Update_Info();
    UxCtrl_SetShow(&UIFlowWndMovie_PanelCtrl,FALSE);
    UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_PIMCtrl, FALSE);
    //DCF_SetFileId();
    // update g_uiRecordIngMotionDet flag
    if (gUIMotionDetTimerID==TIMER_NULL)
    {
        gUIMotionDetTimerID = KeyScan_startTimer(TIMER_HALF_SEC, NVTEVT_05SEC_TIMER, TIMER_TYPE_CONTINUE);
    }
	
    #if(_GPS_RECEIVER_ == ENABLE)
    GPSRec_Open(UART_BAUDRATE_9600);
    if (Get_MovieGPSIndex()==MOVIE_GPS_ON)
    {
        Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_GPS,1,MOVIE_GPS_ON);
        if(g_uiUpdateSpeedTimerID == NULL_TIMER)
             g_uiUpdateSpeedTimerID = KeyScan_startTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
        else {
             KeyScan_stopTimer(&g_uiUpdateSpeedTimerID);
             g_uiUpdateSpeedTimerID = KeyScan_startTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
        }
    } else {
        Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_GPS,1,MOVIE_GPS_OFF);
    }
    #endif
    if(Get_MovieMotionDetIndex()==MOVIE_MOTIONDET_ON)
    {
         g_uiRecordIngMotionDet = TRUE;        
    }	
    //uiImageRotatePreValue = Get_ImageRotateIndex();
    if(first == TRUE)
    {
         first = FALSE;
	   if((GPIOMap_DetTV() == FALSE)&&(Get_MovieMotionDetIndex()==MOVIE_MOTIONDET_OFF)){
         Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);}
     }
    else if((gbKscanTVPlug == TRUE)&&(Get_MovieMotionDetIndex()==MOVIE_MOTIONDET_OFF))
    { 
         gbKscanTVPlug = FALSE;
         Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);
    }
    if (GPIOMap_IsLCDBacklightOn() == FALSE  &&
        KeyScan_IsTVPlugIn() == FALSE &&
        KeyScan_IsHDMIPlugIn() == FALSE)
    {
       TimerDelayMs(400);
        GPIOMap_TurnOnLCDBacklight();
    }
    KeyScan_SetDetGSPNAVIEn(TRUE);
    GPIOMap_SetSPIWp(FALSE);	
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(g_uiTimeTimerID != NULL_TIMER)
        KeyScan_stopTimer(&g_uiTimeTimerID);

    if (gUIMotionDetTimerID!=TIMER_NULL)
        KeyScan_stopTimer(&gUIMotionDetTimerID);

    #if(_GPS_RECEIVER_ == ENABLE)
    if (Get_MovieGPSIndex()==MOVIE_GPS_ON)
    {
        Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_GPS,1,MOVIE_GPS_OFF);
		UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_GPSCtrl,FALSE);
        if(g_uiUpdateSpeedTimerID != NULL_TIMER)
           KeyScan_stopTimer(&g_uiUpdateSpeedTimerID);
    }
    #endif
    if (gUIAviIsRecording == TRUE)
    {
        if(gUIAviRecCurTime <= 1)
        {
            TimerDelayMs(1000);
        }
        FlowMovie_StopRec(TRUE);
        Ux_SendEvent(&UIFlowWndMovieCtrl,NVTEVT_CB_MOVIE_FINISH,0);
    }

    //#NT#2012/1/18#Philex Lin- begin
    // do file system scan for file crashing function
    // this function do file movement but this operation can't sync with DCF table,
    // sync dcf table here
    FilesysScanDCFObj();
    FilesysWaitCmdFinish(FST_TIME_INFINITE);
    //#NT#2012/1/18#Philex Lin- end

    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(gUIAviIsRecording == TRUE)
    {
    		if(gbMoviFileLock == TRUE)
    		{
	       UIFlowWndMovie_OnExeLockFile(FALSE);	    		
	       UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl, FALSE);	
    		}
		else
		{
	       UIFlowWndMovie_OnExeLockFile(TRUE);	    		
	       UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl, TRUE);	
		}
     }
    else
    {
	    //Ux_DefaultEvent(pCtrl,NVTEVT_KEY_MENU,paramNum,paramArray);
	    Ux_OpenWindow(&UIMenuWndMovieVideoCtrl,0);
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //return UIFlowWndMovie_OnExeZoomIn(pCtrl, paramNum, paramArray);
}
INT32 UIFlowWndMovie_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //return UIFlowWndMovie_OnExeZoomOut(pCtrl, paramNum, paramArray);
}
INT32 UIFlowWndMovie_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (gUIAviIsRecording == FALSE)
    {
        // for Flash Shot
        if (gUIFlashAviIsRecording == FALSE)
        {
            gUIFlashAviIsRecording = TRUE;
            Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_START_FLASH_REC,0);
        } else {
            Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_STOP_RECAVI,NULL);
            gUIFlashAviIsRecording = FALSE;
            /* Update Flash recording icon info */
            UxState_SetData(&UIFlowWndMovie_StatusICN_MotionDetCtrl,STATE_CURITEM,Get_MovieMotionDetIndex());
            UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_MotionDetCtrl,TRUE);
        }
        Ux_DefaultEvent(pCtrl,NVTEVT_KEY_RIGHT,paramNum,paramArray);
        //Ux_OpenWindow(&UIMenuWndPhotoQuickSettingCtrl,0);
    }
    else
    {
        //if (Get_MovieSizeIndex()!=MOVIE_SIZE_1080P_HD)
            //UIFlowWndMovie_OnExePIM();
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiEvtKeyAct = 0;

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];
    debug_err(("------------------UIFlowWndMovie_OnKeyEnter....\r\n"));
    switch(uiEvtKeyAct)
    {
        case NVTEVT_KEY_PRESS:       
    		return UIFlowWndMovie_OnExeRecord(pCtrl, paramNum, paramArray);
	  break;
	  default:
	  break;
    	}
        	
}
INT32 UIFlowWndMovie_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiEvtKeyAct = 0;

    if(paramNum > 0)
        uiEvtKeyAct = paramArray[0];
    debug_err(("------------------UIFlowWndMovie_OnKeyShutter2....\r\n"));
    switch(uiEvtKeyAct)
    {
        case NVTEVT_KEY_PRESS:       
    		return UIFlowWndMovie_OnExeRecord(pCtrl, paramNum, paramArray);
	  break;
	  default:
	  break;
    	}
        	
}
INT32 UIFlowWndMovie_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndMovie_OnExeZoomIn(pCtrl, paramNum, paramArray);
}
INT32 UIFlowWndMovie_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return UIFlowWndMovie_OnExeZoomOut(pCtrl, paramNum, paramArray);
}
INT32 UIFlowWndMovie_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (gUIAviIsRecording == TRUE)
    {
        //if (gUIAviRecCurTime > 1) {
            // stop recording really after recording at least in 1-sec interval
            //FlowMovie_StopRec(TRUE);
            //Ux_SendEvent(pCtrl,NVTEVT_CB_MOVIE_FINISH,0);
        //} else {
            // do nothing because recording time is so short and generate one bad video file
            return NVTEVT_CONSUME;
       // }
    }
    //if(Get_MovieSizeIndex() == MOVIE_SIZE_1080P_HD)
    //Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_MOVIESIZE,2,1,TRUE);//jack lan
	
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_CHANGE_DSCMODE,1,DSCMODE_CHGTO_NEXT);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_PLAYBACK_MODE,0);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //UIFlowWndMovie_Update_Info();
    UxState_SetData(&UIFlowWndMovie_Status_batteryCtrl,STATE_CURITEM,GetBatteryLevel());
    UxCtrl_SetShow(&UIFlowWndMovie_Status_batteryCtrl,FALSE);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiWnd = g_uiChildWndMode;
    IPL_OBJ obj;
	
	
    /* Reset child window record */
    g_uiChildWndMode = MOVIE_CHILD_WND_NULL;
    //debug_err(("UIFlowWndMovie_OnChildClose.uiWnd = 0x%x\n\r",uiWnd));
    switch(uiWnd)
    {
        case MOVIE_CHILD_WND_WRNMSG:
            if(paramNum > 0)
            {
                if(paramArray[0] == NVTRET_ENTER_MENU)
                {
                    /* Create Menu window */
                    g_uiChildWndMode = MOVIE_CHILD_WND_MENU;
                    Ux_OpenWindow(&UIMenuWndMovieVideoCtrl,0);
                    return NVTEVT_CONSUME;
                }
            }
            break;

        case MOVIE_CHILD_WND_MENU:
        case MOVIE_CHILD_WND_QUICKSETTING:
        default:
            g_uiMaskKeyPress = MOVIE_KEY_PRESS_MASK;
            g_uiMaskKeyRelease = MOVIE_KEY_RELEASE_MASK;
            KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, g_uiMaskKeyPress);
            KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, g_uiMaskKeyRelease);
//------------jack lan ,begin---------------			
               if (Get_MovieMotionDetIndex()==MOVIE_MOTIONDET_ON)
                {
                      g_uiRecordIngMotionDet = TRUE;                    
                }			
		   else
		   {
                      g_uiRecordIngMotionDet = FALSE;                    
		   }
//------------jack lan ,end---------------			   

            /* Update window info */
            UIFlowWndMovie_Update_Info();
            // update g_uiUpdateSpeedTimerID status after menu setting
            #if(_GPS_RECEIVER_ == ENABLE)
            if (Get_MovieGPSIndex()==MOVIE_GPS_ON)
            {
                Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_GPS,1,MOVIE_GPS_ON);
                if(g_uiUpdateSpeedTimerID == NULL_TIMER)
                     g_uiUpdateSpeedTimerID = KeyScan_startTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
                else {
                     KeyScan_stopTimer(&g_uiUpdateSpeedTimerID);
                     g_uiUpdateSpeedTimerID = KeyScan_startTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
                }
            } else {
                Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_GPS,1,MOVIE_GPS_OFF);
                if (g_uiUpdateSpeedTimerID != NULL_TIMER)
                     KeyScan_stopTimer(&g_uiUpdateSpeedTimerID);
            }
            #endif

			
            break;
    }

    if (Get_MovieGodBlessIndex())
    {
        SysInit_DisplaySplashScreen(LOGO_GOD,0,0);
    } else {
        PhotoDisplay_SetMode(DISPLAY_MODE_VIDEO, TRUE);
    }
#if 0	
	if(uiImageRotatePreValue != Get_ImageRotateIndex())
	{
	   uiImageRotatePreValue = Get_ImageRotateIndex();
	   
	   obj.uiCmd = IPL_CMD_CHG_MODE;
	   obj.Mode = IPL_MODE_OFF;
	   IPL_SetCmd(&obj);
	    if(Get_ImageRotateIndex() == IMAGE_ROTATE_OFF)
	    {
			UI_SetParameter(_ImageFlip,_Flip_Off);
	    }
	    else
	    {
			UI_SetParameter(_ImageFlip,_Flip_H_V);
	    }
	   obj.uiCmd = IPL_CMD_CHG_MODE;
	   obj.Mode = IPL_MODE_VIDEO;
	   IPL_SetCmd(&obj);	
	}
#endif	
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT16 uhFolderId, uhFileId;
    UINT32 uhSelect = 0;

    if(paramNum == 1)
        uhSelect= paramArray[0];

    debug_err(("-------FlowMovie_OnMovieFinish:paramNum=%d,recording=%d\r\n",paramNum,gUIAviIsRecording));
    if (gUIAviIsRecording == TRUE)
    {
#if (_MOVIE_DIS_MODE_ == ENABLE)
        //#NT#2010/11/09#Hideo Lin -begin
        //#NT#Marked; using callback function to set display view
        /*
        if (Get_MovieDISIndex() == MOVIE_DIS_ON)
        {
            ide_disableVideo(IDE_VIDEOID_1);
            PhotoDis_setMode(PHOTODIS_MODE_IDLE, TRUE);
            PhotoDisplay_SetMode(DISPLAY_MODE_VIDEO, TRUE);
            // Delay 4 frames to avoid seeing error picture
            sie_waitVD(4);
            ide_enableVideo(IDE_VIDEOID_1);
        }
        */
        //#NT#2010/11/09#Hideo Lin -end
#endif

        if(UI_Validate_Storage(STORAGE_CHECK_FULL, &(gUIAviRecMaxTime)) != FALSE)
        {
            FilesysGetDCFNextID(&uhFolderId,&uhFileId);
            Set_FilesysDirId(uhFolderId);
            Set_FilesysFileId(uhFileId);
            DbgMsg_UIRecAvi(("Finish:D=%d,F=%d,FS=%d\r\n",Get_FilesysDirId(),Get_FilesysFileId(),GetFSStatus()));
            Save_MenuInfo();
        }
        gUIAviIsRecording = FALSE;
        //g_uiRecordIngMotionDet = FALSE;
        if(Get_MovieMotionDetIndex()==MOVIE_MOTIONDET_ON)
        {
             //g_uiRecordIngMotionDet = FALSE;        
	  	//Set_MovieMotionDetIndex(MOVIE_MOTIONDET_OFF);        
        }
        KeyScan_EnableAutoPoweroff(TRUE);
        KeyScan_EnableUSBDet(TRUE);
        FlowMovie_DrawMaxRecTime(TRUE);
        UxCtrl_SetShow(&UIFlowWndMovie_PanelCtrl,FALSE);
        if (FlowMovie_ChkDrawStoreFullFolderFull() == FALSE)
        {
            DbgMsg_UIRecAvi(("Stop Rec-Avi Done\r\n\r\n"));
            UIFlowWndMovie_Update_Info();
            KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, MOVIE_KEY_PRESS_MASK);
            //#NT#2011/5/25#Philex - begin
            // re-start recording again because SD card's write speed is too slow
#if 0
            if (uhSelect==UIFlowWndMovie_Restart_Rec)
               {
                g_bManualStop = TRUE;
                Ux_PostEvent(NVTEVT_KEY_ENTER, 2, NVTEVT_KEY_PRESS, FLGKEY_PRESSED);
                return NVTEVT_CONSUME;
               }
#endif
            //#NT#2011/5/25#Philex - end
        }
        else
        {
            DbgMsg_UIRecAvi(("Stop Rec-Avi but Folder or Store Full\r\n\r\n"));
            return NVTEVT_CONSUME;
        }
    }
    else
    {
        debug_err(("Stop Rec-Avi but gUIAviIsRecording is FALSE\r\n"));
    }
	if(gbMoviFileLock== TRUE)
     {               
	       //FilesysGetDCFNextID(&uhFolderId, &uhFileId);
	       //Set_FilesysFileId(uhFileId);
		 //Set_FilesysDirId(uhFolderId);
		debug_err(("-----UIFlowWndMovie_OnMovieFinish--lock %d, %d---\r\n",Get_FilesysFileId()-1,Get_FilesysDirId()));        	
	      //GFILE_SetGfile(Get_FilesysFileId()-2,Get_FilesysDirId());
		FilesysWaitInitFinish(FST_TIME_INFINITE);	 
		FilesysWaitCmdFinish(FST_TIME_INFINITE);  
		FilesysSetFileLock(Get_FilesysFileId()-1,Get_FilesysDirId(),TRUE);
             UIFlowWndMovie_OnExeLockFile(FALSE);					
             UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl, FALSE);		
     }	
	 if(bStarMovie == TRUE)
	 {
		bStarMovie = FALSE;		
	 }	
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //DbgMsg_UIRecAvi(("FlowMovie_OnMovieOneSec:recSec=%d,recording=%d\r\n",*paramArray,gUIAviIsRecording));
#if 0
    if (gUIFlashAviIsRecording == TRUE)
    {
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_FlashRecCtrl,!UxCtrl_IsShow(&UIFlowWndMovie_StatusICN_FlashRecCtrl));
    }
#endif

    if (gUIAviIsRecording == TRUE)
    {
     UINT32 uiCyclicRecTime;
	 if(bStarMovie == TRUE)
	 {
		if(*paramArray >2)
		{
			bStarMovie = FALSE;
		}
	 }
        UxCtrl_SetShow(&UIFlowWndMovie_PanelCtrl,!UxCtrl_IsShow(&UIFlowWndMovie_PanelCtrl));
        FlowMovie_DrawRecTime(TRUE, *paramArray);
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT16 uhFolderId, uhFileId;
    DbgMsg_UIRecAvi(("FlowMovie_OnMovieFull\r\n"));
    if (gUIAviIsRecording == TRUE)
    {
        DbgMsg_UIRecAvi(("Store Full,Stop Rec Avi:D=%d,F=%d,FS=%d\r\n",Get_FilesysDirId(),Get_FilesysFileId(),GetFSStatus()));

        FlowMovie_StopRec(FALSE);
        gUIAviStoreFull = TRUE;

        /**
        if(UI_Validate_Storage(STORAGE_CHECK_FULL, &(gUIAviRecMaxTime)) != FALSE)
        {
            FilesysGetDCFNextID(&uhFolderId,&uhFileId);
            Set_FilesysDirId(uhFolderId);
            Set_FilesysFileId(uhFileId);
            DbgMsg_UIRecAvi(("Finish:D=%d,F=%d,FS=%d\r\n",Get_FilesysDirId(),Get_FilesysFileId(),GetFSStatus()));
            Save_MenuInfo();
        }
        if (GetCardStatus() == CARD_REMOVED)
        {
            DbgMsg_UIRecAvi(("#RevIntrMem Full \r\n"));
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORY_FULL,FLOWWRNMSG_TIMER_KEEP);
            return NVTEVT_CONSUME;
        }
        else
        {
            DbgMsg_UIRecAvi(("#RevCard Full \r\n"));
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARD_FULL,FLOWWRNMSG_TIMER_KEEP);
            return NVTEVT_CONSUME;
        }
        **/
    }
    else
    {
        KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS,MOVIE_KEY_PRESS_MASK);
        debug_err(("Err: Store Full but gUIAviIsRecording is FALSE\r\n"));
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT16 uhFolderId, uhFileId;
    DbgMsg_UIRecAvi(("UIFlowWndMovie_OnMovieWrError\r\n"));
    if (gUIAviIsRecording == TRUE)
    {
        DbgMsg_UIRecAvi(("Wr err,Stop Rec Avi:D=%d,F=%d,FS=%d\r\n",Get_FilesysDirId(),Get_FilesysFileId(),GetFSStatus()));

        FlowMovie_StopRec(FALSE);

        if (GetCardStatus() == CARD_LOCKED)
        {
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_CARD_LOCKED,FLOWWRNMSG_TIMER_3SEC);
            return NVTEVT_CONSUME;
        }
        else
        {
            g_uiChildWndMode = MOVIE_CHILD_WND_WRNMSG;
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORYERROR,FLOWWRNMSG_TIMER_3SEC);
            return NVTEVT_CONSUME;
        }
    }
    else
    {
        KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS,MOVIE_KEY_PRESS_MASK);
        debug_err(("Err: Store Full but gUIAviIsRecording is FALSE\r\n"));
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnOZoomStepChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnDZoomStepChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    AlgMsgInfo *pAlgMsgInfo = Get_AlgMsgInfo();

    /* Update digital zoom ratio OSD string */
    UxStatic_SetData(&UIFlowWndMovie_Zoom_StaticCtrl,STATIC_VALUE,Txt_Pointer(Get_DZoomRatioString(pAlgMsgInfo)));

    if(pAlgMsgInfo->DzoomIndex > UI_DZOOM_IDX_MIN)
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,TRUE);
    else
        UxCtrl_SetShow(&UIFlowWndMovie_Zoom_StaticCtrl,FALSE);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //FilesysWaitInitFinish(FST_TIME_INFINITE);
    debug_err(("[UIFlowWndMovie_OnStorageChange]\n\r"));
    UIFlowWndMovie_Update_Info();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, g_uiMaskKeyPress);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, g_uiMaskKeyRelease);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnMacroChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    debug_err(("UIFlowWndMovie_OnMacroChange: OnMacroChange - %s\r\n", (Get_MacroIndex() == MACRO_ON)? "ON" : "OFF"));
    UIFlowWndMovie_Update_Info();
    return NVTEVT_CONSUME;
}

static void UIFlowWndMovie_Update_Speed(void)
{
    BOOL bS;
    RMCINFO RMCInfo;
    Gsensor_Data GS_Data;
    RTC_DATE        CurDate;
    RTC_TIME        CurTime;
    UINT32 szIQInfo;

    gsensor_GetData(&GS_Data);
    bS = GPSRec_GetRMCDate(&RMCInfo);
    if (Get_MovieGPSIndex()==MOVIE_GPS_ON)
    {
        memcpy(&(gpsdata.rmcinfo),&RMCInfo,sizeof(RMCINFO));
        memcpy(&(gpsdata.gs_data),&GS_Data,sizeof(Gsensor_Data));

        //debug_msg("gpsdata.rmcinfo.Speed = %f\r\n", gpsdata.rmcinfo.Speed);
//#NT#2011/10/14#Spark Chou -begin
//#NT# Video IQ debug info
#if _MOVIE_IQLOG_
        CurDate = rtc_getDate();
        CurTime = rtc_getTime();
        gpsdata.rmcinfo.Year = CurDate.s.year;
        gpsdata.rmcinfo.Month= CurDate.s.month;
        gpsdata.rmcinfo.Day= CurDate.s.day;
        gpsdata.rmcinfo.Hour = CurTime.s.hour;
        gpsdata.rmcinfo.Minute= CurTime.s.minute;
        gpsdata.rmcinfo.Second = CurTime.s.second;

        szIQInfo = GetVideoIQInfo();
        sprintf(gpsdata.IQDebugInfo, "%s", (char*)szIQInfo);
        ResetVideoIQInfo();
#endif
//#NT#2011/10/14#Spark Chou -end
    } else {
        memset(&gpsdata,0,sizeof(GPSDATA));
    }
}

static void UIFlowWndMovie_Update_Gps_status(void)
{
    UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_GPSCtrl,FALSE);
	UxState_SetData(&UIFlowWndMovie_StatusICN_GPSCtrl,STATE_CURITEM,GPSRec_CheckData());
    UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_GPSCtrl,TRUE);
}
INT32 UIFlowWndMovie_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVT_USER_EVT key;
    UINT32 speed_hi,speed_lo,speed_total;
    UINT32 year,month,day;
    UINT32 hour,minute,second;	
    static UINT32 Counter =0;
    static UINT32 GPSTimeReset =0;
	
    static UINT32 SetTimeCounter =0;
	
    static UINT32 GPSDataCounter_Pre=0;
    RTC_DATE    Date;
    RTC_TIME    Time;	

    key = paramArray[0];
 //   debug_err(("UIFlowWndMovie_OnTimer\n\r"));
    if(Get_DisplayIndex() != DISPLAY_OFF)
    {
        switch(key)
        {
        case NVTEVT_2SEC_TIMER:
            Ux_PostEvent(NVTEVT_REDRAW, 0);
            break;
        case NVTEVT_1SEC_TIMER:
		Counter++;
            if (Get_MovieGPSIndex()==MOVIE_GPS_ON)
            {
               UIFlowWndMovie_Update_Speed();
			   UIFlowWndMovie_Update_Gps_status();  
            }
			
		//update time
		Time = rtc_getTime();
        Date = rtc_getDate();
        //debug_msg("rtc_get_time: hour = %d, minute = %d, second = %d \r\n",Time.s.hour, Time.s.minute, Time.s.second);    
        sprintf(date_str,"%04d/%02d/%02d",Date.s.year,Date.s.month,Date.s.day);
        sprintf(time_str,"%02d:%02d:%02d",Time.s.hour,Time.s.minute,Time.s.second);
        UxStatic_SetData(&UIFlowWndMovie_YMD_StaticCtrl,STATIC_VALUE,Txt_Pointer(date_str));
        UxStatic_SetData(&UIFlowWndMovie_HMS_StaticCtrl,STATIC_VALUE,Txt_Pointer(time_str));
			
//----------------------jack lan begin-----------------------------------------
        //if(GPSDataCounter!=GPSDataCounter_Pre)
		if(GPSRec_CheckData()) 
        {
          UxCtrl_SetShow(&UIFlowWndMovie_GPSCtrl, FALSE);
          UxCtrl_SetShow(&UIFlowWndMovie_SpeedCtrl, FALSE);			
	    //sprintf(SP_buf, "SP: %d%d%d%d.%d%d%d%d.%d%d%d%d",SP_1[0],SP_1[1],SP_1[2],SP_1[3],SP_1[4],SP_1[5],SP_1[6],SP_1[7],SP_1[8],
			//SP_1[9],SP_1[10],SP_1[11]);
	    //UxStatic_SetData(&UIFlowWndMovie_GPSCtrl,STATIC_VALUE,Txt_Pointer(SP_buf));
		
	    //speed_total = ((Speed[0]<<8)&0xff00)|(Speed[1]&0xff);
	    //speed_hi = speed_total/10;
	    //speed_lo = speed_total%10;
	    //sprintf(Speed_buf,"Speed: %03d.%d km/h",speed_hi,speed_lo);
	    sprintf(Speed_buf,"Speed: %d km/h",(UINT32)(gpsdata.rmcinfo.Speed));
	    UxStatic_SetData(&UIFlowWndMovie_SpeedCtrl,STATIC_VALUE,Txt_Pointer(Speed_buf));          
          //UxCtrl_SetShow(&UIFlowWndMovie_GPSCtrl, TRUE);
          UxCtrl_SetShow(&UIFlowWndMovie_SpeedCtrl, TRUE);
	    GPSDataCounter_Pre =GPSDataCounter;
	    GPSDataInputFlag=TRUE;		
	    Counter=0;
	    debug_msg("----GPS has Data----\r\n");		
          }	   
	   else
         {
			Counter++;
			if(Counter>6)
			{
        		    Counter =0;
		          //GPSDataCounter=0;
			    //GPSDataCounter_Pre=0;
			    GPSSetTime = TRUE;
			    GPSDataInputFlag=FALSE;
			    GPSTimeReset=0;
		          UxCtrl_SetShow(&UIFlowWndMovie_GPSCtrl, FALSE);
		          UxCtrl_SetShow(&UIFlowWndMovie_SpeedCtrl, FALSE);
			    debug_err(("----GPS no Data----\r\n"));
			}
	   } 	   	
	   if(GPSDataInputFlag == TRUE)
	   {   
	         SetTimeCounter++;
		   GPSTimeReset++;
			 
		   if(SetTimeCounter<3)
		   	return;
	         if(GPSSetTime == TRUE)
		  {
		   if(gUIAviIsRecording == TRUE)
		   {
                     //Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);			
		   }
		   GPSSetTime = FALSE;
		   #if 0
	         year = (0x7D0|GPSTime_Y);
		   if((year>2050)||(year<2013))
		   	year=2013;			 
	         month = GPSTime_M;
		   if((month>12)||(month<1))
		   	month=1;
	         day = GPSTime_D;
		   if((day>31)||(day<1))
		   	day=1;			 
	         hour = GPSTime_H;
		   if((hour>23)||(hour<1))
		   	hour=0;			 
	         minute = GPSTime_Mi;
		   if((minute>59)||(minute<1))
		   	minute=0;				 
	         second = GPSTime_S;
		   if((second>59)||(second<1))
		   	second=0;
		   #else
		    year = (0x7D0|gpsdata.rmcinfo.Year);
		   if((year>2050)||(year<2013))
		   	year=2013;			 
	         month = gpsdata.rmcinfo.Month;
		   if((month>12)||(month<1))
		   	month=1;
	         day = gpsdata.rmcinfo.Day;
		   if((day>31)||(day<1))
		   	day=1;			 
	         hour = gpsdata.rmcinfo.Hour + 8;
		   if((hour>23)||(hour<1))
		   	hour=0;			 
	         minute = gpsdata.rmcinfo.Minute;
		   if((minute>59)||(minute<1))
		   	minute=0;				 
	         second = gpsdata.rmcinfo.Second;
		   if((second>59)||(second<1))
		   	second=0;
		   #endif
			    debug_err(("----GPS set time----\r\n"));
		         
                rtc_setTime(hour,minute,second);
				rtc_setDate(year,month,day);
				//debug_msg("gps_set_time: hour = %d, minute = %d, second = %d\r\n",hour,minute,second);
    		   USERFolder_set();
		   GPSTimeReset=0;
				
	         }
	   }
	   
	   /*if(	GPSTimeReset>10)
	   {
		if(GPSSetTime==FALSE){
			GPSSetTime=TRUE;
			GPSTimeReset=0;}
	   }*/

//----------------------jack lan end-----------------------------------------				
            break;
        case NVTEVT_05SEC_TIMER:
                // Motion Detect function
                if (g_uiRecordIngMotionDet==TRUE)
                {
                  static UINT32  uiMotionDetGo = 0;
                  static UINT32  uiMotionDetStop = 0;

                    if (MotionDetection()==TRUE)
                    {
                         uiMotionDetGo++;
                         if (uiMotionDetGo>=2)
                         {
                            uiMotionDetStop=0;
                            if (gUIAviIsRecording==FALSE)
                            {
                                // reset uiMotionDetGo
                                uiMotionDetGo = 0;
                                // press enter key to record video
                                Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS);
                            }
                         }
                    } else {
                        uiMotionDetStop++;
                        if (uiMotionDetStop>=2) // 1 sec
                        {
                            uiMotionDetGo=0;
                        }
                        if (uiMotionDetStop>=24) // 10 Sec
                        {
                            uiMotionDetStop = 0;
                            if (gUIAviIsRecording==TRUE)
                            {
                               if (gUIAviRecCurTime >= 1) {
                                   gUIAviIsRecording=FALSE;
                                   FlowMovie_StopRec(TRUE);
					   UIFlowWndMovie_Update_Info();	
            				   KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, MOVIE_KEY_PRESS_MASK);					   
                               }
                            }
                        }
                    }
                }
            break;
        }
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

 
INT32 UIFlowWndMovie_OnOSDReflash(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
        UxState_SetData(&UIFlowWndMovie_StatusICN_AudioCtrl,STATE_CURITEM,Get_MovieAudioIndex());		
        UxCtrl_SetShow(&UIFlowWndMovie_StatusICN_AudioCtrl,TRUE);
    return NVTEVT_CONSUME;
}

INT32 UIFlowWndMovie_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT16 uhFolderId, uhFileId;
    debug_err(("UIFlowWndMovie_OnKeyDisplay gbMoviFileLock : %d ...\r\n",gbMoviFileLock));

    if(gUIAviIsRecording == TRUE)
    {
          if(gsensor_gettype()==GSENSOR_GMA301)
          {
          	  // if(gUIAviRecCurTime>1){
	          if(gbMoviFileLock==FALSE){
		    UIFlowWndMovie_OnExeLockFile(TRUE);
	          debug_err(("---SOS--FilesysSetFileLock --Cur-- : %d - %d---\r\n",Get_FilesysFileId(),Get_FilesysDirId()));					
		    UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl, TRUE);	}//}
          }
	   else
	   	{
	          if(gbMoviFileLock==FALSE){
		    UIFlowWndMovie_OnExeLockFile(TRUE);
	          debug_err(("---SOS--FilesysSetFileLock --Cur-- : %d - %d---\r\n",Get_FilesysFileId(),Get_FilesysDirId()));					
		    UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl, TRUE);	}}
	   
	}	
    	    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMovie_OnAutoRecordStop(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (gUIAviIsRecording == TRUE)
    {
        if (gUIAviRecCurTime >= 1) // need to record 1 sec at least
        {
            DbgMsg_UIRecAvi(("Stop Rec Avi, Save Avi File\r\n"));
            FlowMovie_StopRec(TRUE);
        }
    }
}
//----------------------UIFlowWndMovie_Static_cameraCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Static_camera)
EVENT_END

//----------------------UIFlowWndMovie_Status_batteryCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Status_battery)
EVENT_END

//---------------------UIFlowWndMovie_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMovie_Panel)
CTRL_LIST_END

//----------------------UIFlowWndMovie_PanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Panel)
EVENT_END

//----------------------UIFlowWndMovie_Static_timeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Static_time)
EVENT_END

//----------------------UIFlowWndMovie_Static_maxtimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Static_maxtime)
EVENT_END

//----------------------UIFlowWndMovie_Static_resolutionCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Static_resolution)
EVENT_END

//----------------------UIFlowWndMovie_Zoom_StaticCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Zoom_Static)
EVENT_END
//extern void UIFlowWndPhoto_GetHistogram(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);   //Temporarily marked for extern

//----------------------UIFlowWnd_HistoCtrl Event---------------------------
INT32 UIFlowWnd_Histo_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIFlowWnd_Histo_OnRedraw(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWnd_Histo)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWnd_Histo_OnTimer)
EVENT_ITEM(NVTEVT_REDRAW,UIFlowWnd_Histo_OnRedraw)
EVENT_END

INT32 UIFlowWnd_Histo_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVT_USER_EVT key;
    key = paramArray[0];
debug_err(("UIFlowWnd_Histo_OnTimer\n\r"));
    if(Get_DisplayIndex() != DISPLAY_OFF)
    {
        switch(key)
        {
        case NVTEVT_2SEC_TIMER:
            Ux_PostEvent(NVTEVT_REDRAW, 0);
            break;
        case NVTEVT_1SEC_TIMER:
            UIFlowWndMovie_Update_Info();
            break;
        }
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWnd_Histo_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //debug_err(("UIFlowWnd_Histo_OnTimer [%d]\n\r",Get_DisplayIndex()));
    //UxStatic_SetData(&UIFlowWndMovie_Zoom_StaticCtrl,STATIC_VALUE,Txt_Pointer(dzoom_Buf[Get_UIDzoomIndex()]));
    if(Get_DisplayIndex() == 1)
    {
        //UIFlowWndCommon_GetHistogram(pCtrl,paramNum,paramArray);   //Temporarily marked for extern
        UxCtrl_SetDirty(pCtrl, TRUE);
        Ux_DefaultEvent(pCtrl,NVTEVT_REDRAW,paramNum,paramArray);
    }
    else
    {
        if(gHistogram_show_timer != NULL_TIMER)
        {
            KeyScan_stopTimer(&gHistogram_show_timer);
        }
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndMovie_OnCultNormal(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	  if(gbMoviFileLock==TRUE)
	  {
		FilesysWaitInitFinish(FST_TIME_INFINITE);	 
		FilesysWaitCmdFinish(FST_TIME_INFINITE);  
		debug_err(("-----UIFlowWndMovie_OnMovieFinish--lock %d, %d---\r\n",Get_FilesysFileId(),Get_FilesysDirId()));        			
		FilesysSetFileLock(Get_FilesysFileId(),Get_FilesysDirId(),TRUE);
		FilesysWaitInitFinish(FST_TIME_INFINITE);	 
		FilesysWaitCmdFinish(FST_TIME_INFINITE);  		
             UIFlowWndMovie_OnExeLockFile(FALSE);					
             UxCtrl_SetShow(&UIFlowWndMovie_StaticIcon_LockCtrl, FALSE);						
	  }
}
//----------------------UIFlowWndMovie_YMD_StaticCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_YMD_Static)
EVENT_END

//----------------------UIFlowWndMovie_HMS_StaticCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_HMS_Static)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_StorageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_Storage)
EVENT_END

//----------------------UIFlowWndMovie_StaticIcon_PIMCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StaticIcon_PIM)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_CyclicRecCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_CyclicRec)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_MotionDetCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_MotionDet)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_LEDLightCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_LEDLight)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_AudioCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_Audio)
EVENT_END

//----------------------UIFlowWndMovie_StaticIcon_LockCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StaticIcon_Lock)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_ColorCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_Color)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_EVCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_EV)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_WBCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_WB)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_GSENSORCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_GSENSOR)
EVENT_END

//----------------------UIFlowWndMovie_SpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_Speed)
EVENT_END

//----------------------UIFlowWndMovie_GPSCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_GPS)
EVENT_END

//----------------------UIFlowWndMovie_StatusICN_GPSCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndMovie_StatusICN_GPS)
EVENT_END

