//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupRes.c"
#include "UIMenuWndSetup.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUP_ERROR_MSG        1
#define _UIMENUWNDSETUP_TRACE_MSG        0

#if (_UIMENUWNDSETUP_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupErrMsg(...)            debug_msg ("^R UIMenuWndSetup: "__VA_ARGS__)
#else
#define UIMenuWndSetupErrMsg(...)
#endif

#if (_UIMENUWNDSETUP_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupTraceMsg(...)          debug_msg ("^B UIMenuWndSetup: "__VA_ARGS__)
#else
#define UIMenuWndSetupTraceMsg(...)
#endif

//---------------------UIMenuWndSetupCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup)
CTRL_LIST_ITEM(UIMenuWndSetup_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_End_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Setup_Menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupCtrl Event---------------------------
INT32 UIMenuWndSetup_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetup)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetup_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetup_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndSetup_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetup_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetup_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetup_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetup_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetup_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetup_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetup_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Panel)
EVENT_END

//---------------------UIMenuWndSetup_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Title_Mode_Status)
CTRL_LIST_ITEM(UIMenuWndSetup_Title_Old_Status)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Title_Panel)
EVENT_END

//----------------------UIMenuWndSetup_Title_Mode_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Title_Mode_Status)
EVENT_END

//----------------------UIMenuWndSetup_Title_Old_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Title_Old_Status)
EVENT_END

//---------------------UIMenuWndSetup_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_End_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Return_Static)
CTRL_LIST_ITEM(UIMenuWndSetup_Dir_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Dir2_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_Dir3_Panel)
CTRL_LIST_ITEM(UIMenuWndSetup_PageNum_Static)
CTRL_LIST_END

//----------------------UIMenuWndSetup_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_End_Panel)
EVENT_END

//----------------------UIMenuWndSetup_Return_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Return_Static)
EVENT_END

//---------------------UIMenuWndSetup_Dir_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Dir_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Dir_Panel)
EVENT_END

//---------------------UIMenuWndSetup_Dir2_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Dir2_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Dir2_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Dir2_Panel)
EVENT_END

//---------------------UIMenuWndSetup_Dir3_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetup_Dir3_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetup_Dir3_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_Dir3_Panel)
EVENT_END

//----------------------UIMenuWndSetup_PageNum_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetup_PageNum_Static)
EVENT_END

//----------------------UIMenuWndSetup_Setup_MenuCtrl Event---------------------------
INT32 UIMenuWndSetup_Setup_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetup_Setup_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetup_Setup_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetup_Setup_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetup_Setup_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetup_Setup_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetup_Setup_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetup_Setup_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetup_Setup_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetup_Setup_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
