//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupDelayPowerOffRes.c"
#include "UIMenuWndSetupDelayPowerOff.h"
//---------------------UIMenuWndSetupDelayPowerOffCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDelayPowerOff)
CTRL_LIST_ITEM(UIMenuWndSetupDelayPowerOff_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetupDelayPowerOffCtrl Event---------------------------
INT32 UIMenuWndSetupDelayPowerOff_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDelayPowerOff)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupDelayPowerOff_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupDelayPowerOff_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupDelayPowerOff_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupDelayPowerOff_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupDelayPowerOff_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupDelayPowerOff_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupDelayPowerOff_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupDelayPowerOff_Panel)
CTRL_LIST_ITEM(UIMenuWndSetupDelayPowerOff_List_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupDelayPowerOff_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupDelayPowerOff_Panel)
EVENT_END

//----------------------UIMenuWndSetupDelayPowerOff_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupDelayPowerOff_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupDelayPowerOff_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupDelayPowerOff_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupDelayPowerOff_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupDelayPowerOff_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
