//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPIMAGEROTATE_H
#define UIMENUWNDSETUPIMAGEROTATE_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupImageRotateCtrl;//Panel type 

extern VControl UIMenuWndSetupImageRotate_List_TextCtrl;//List type 

typedef enum
{
UIMenuWndSetupImageRotate_List_Text_STRID_OFF,
UIMenuWndSetupImageRotate_List_Text_STRID_ON,
UIMenuWndSetupImageRotate_List_Text_MAX
}UIMenuWndSetupImageRotate_List_Text_Setting;

#endif
