//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupImageRotateRes.c"
#include "UIMenuWndSetupImageRotate.h"
//---------------------UIMenuWndSetupImageRotateCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupImageRotate)
CTRL_LIST_ITEM(UIMenuWndSetupImageRotate_List_Text)
CTRL_LIST_END

//----------------------UIMenuWndSetupImageRotateCtrl Event---------------------------
INT32 UIMenuWndSetupImageRotate_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupImageRotate_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupImageRotate_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupImageRotate_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupImageRotate_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupImageRotate)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupImageRotate_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupImageRotate_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupImageRotate_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupImageRotate_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupImageRotate_OnKeyMode)
EVENT_END

INT32 UIMenuWndSetupImageRotate_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupImageRotate_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupImageRotate_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupImageRotate_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupImageRotate_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupImageRotate_List_TextCtrl Event---------------------------
INT32 UIMenuWndSetupImageRotate_List_Text_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupImageRotate_List_Text_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupImageRotate_List_Text_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupImageRotate_List_Text)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupImageRotate_List_Text_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupImageRotate_List_Text_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupImageRotate_List_Text_OnKeyEnter)
EVENT_END

INT32 UIMenuWndSetupImageRotate_List_Text_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupImageRotate_List_Text_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupImageRotate_List_Text_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
