//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndMovieDISRes.c"
#include "UIMenuWndMovieDIS.h"
#include "UIMenuWndMovieVideo.h"
#include "UIMovieObj.h"
#include "UISystemObj.h"
#include "KeyScanTsk.h"

//---------------------UIMenuWndMovieDISCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieDIS)
CTRL_LIST_ITEM(UIMenuWndMovieDIS_Panel)
CTRL_LIST_END

//----------------------UIMenuWndMovieDISCtrl Event---------------------------
INT32 UIMenuWndMovieDIS_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieDIS_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieDIS)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndMovieDIS_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndMovieDIS_OnClose)
EVENT_END

INT32 UIMenuWndMovieDIS_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxMenu_SetData(&UIMenuWndMovieDIS_MenuCtrl,MNU_CURITM,Get_MovieDISIndex());
    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieDIS_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndMovieDIS_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieDIS_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieDIS_Menu)
CTRL_LIST_END

//----------------------UIMenuWndMovieDIS_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieDIS_Panel)
EVENT_END

//----------------------UIMenuWndMovieDIS_MenuCtrl Event---------------------------
INT32 UIMenuWndMovieDIS_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieDIS_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieDIS_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieDIS_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieDIS_Menu_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieDIS_Menu_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieDIS_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndMovieDIS_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndMovieDIS_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndMovieDIS_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndMovieDIS_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndMovieDIS_Menu_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndMovieDIS_Menu_OnKeyMode)
EVENT_END

INT32 UIMenuWndMovieDIS_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieDIS_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieDIS_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieDISCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieDIS_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   value;
    value = UxMenu_GetData(pCtrl,MNU_CURITM);
    Ux_SendEvent(&UIMovieObjCtrl,NVTEVT_EXE_MOVIEDIS,1,value);
    Ux_CloseWindow(&UIMenuWndMovieDISCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieDIS_Menu_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(&UIMenuWndMovieVideoCtrl,0); // close movie video menu
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieDIS_Menu_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
