//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayProtectRes.c"
#include "UIMenuWndPlayProtect.h"
//#NT#2009/09/14#Chris Chung -begin
#include "UIPlayObj.h"
#include "UIFlowWndWrnMsg.h"
#include "UISystemStatusSettings.h"
#include "UIFlowWndWaitMoment.h"
#include "UISystemObj.h"
#include "UIMenuWndPlayback.h"
#include "KeyScanTsk.h"
//#NT#2009/09/14#Chris Chung -end

//---------------------UIMenuWndPlayProtectCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayProtect)
CTRL_LIST_ITEM(UIMenuWndPlayProtect_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayProtectCtrl Event---------------------------
INT32 UIMenuWndPlayProtect_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayProtect)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayProtect_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayProtect_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayProtect_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayProtect_OnKeyMode)
EVENT_END

INT32 UIMenuWndPlayProtect_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    UxMenu_SetData(&UIMenuWndPlayProtect_MenuCtrl, MNU_CURITM, 0);

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    //#NT#2009/09/14#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    //#NT#2009/09/14#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/05#Chris Chung -begin
    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT && paramArray[1]==NVTRET_PROTECT)
        {
            Ux_RedrawAllWind();
        }
    }
    //#NT#2009/08/05#Chris Chung -end
    else
    {
        Ux_RedrawAllWind();
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    //#NT#2009/09/14#Chris Chung -end
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayProtect_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayProtect_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayProtect_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPlayProtect_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayProtect_Panel)
EVENT_END

//----------------------UIMenuWndPlayProtect_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayProtect_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayProtect_Menu_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayProtect_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayProtect_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayProtect_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayProtect_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayProtect_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayProtect_Menu_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPlayProtect_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/07/28#Chris Chung -begin
    if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
    {
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
        return NVTEVT_CONSUME;
    }

    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_EXE_PROTECT,1,UxMenu_GetData(pCtrl,MNU_CURITM));

    switch(UxMenu_GetData(pCtrl,MNU_CURITM))
    {
    case UIMenuWndPlayProtect_Menu_STRID_LOCKONE:
    case UIMenuWndPlayProtect_Menu_STRID_UNLOCKONE:
        Ux_CloseWindow((VControl *)(&UIMenuWndPlayProtectCtrl), 0);
        break;

    case UIMenuWndPlayProtect_Menu_STRID_LOCKALL:
    case UIMenuWndPlayProtect_Menu_STRID_UNLOCKALL:
        Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
        break;
    default:
        debug_err(("UIMenuWndPlayProtect_Menu_OnKeyEnter: error MNU_CURITM\r\n"));
    }
    //#NT#2009/07/28#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/07/16#Chris Chung -begin
    Ux_CloseWindow((VControl *)(&UIMenuWndPlayProtectCtrl), 0);
    //#NT#2009/07/16#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayProtect_Menu_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/04#Chris Chung -begin
    Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);
    //#NT#2009/08/04#Chris Chung -end
    return NVTEVT_CONSUME;
}
