//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYBACK_H
#define UIMENUWNDPLAYBACK_H

#include "UIFramework.h"

extern VControl UIMenuWndPlaybackCtrl;//Panel type 

extern VControl PlaybackMenuBackgroundCtrl;//Panel type 

extern VControl UIMenuWndPlayback_TitleBarCtrl;//Panel type 

extern VControl UIMenuWndPlayback_TitleNameCtrl;//Status type 

typedef enum
{
UIMenuWndPlayback_TitleName_STRID_PLAYBACK,
UIMenuWndPlayback_TitleName_STRID_DELETE,
UIMenuWndPlayback_TitleName_STRID_PROTECT,
UIMenuWndPlayback_TitleName_STRID_SLIDE_SHOW,
UIMenuWndPlayback_TitleName_STRID_DPOF,
UIMenuWndPlayback_TitleName_MAX
}UIMenuWndPlayback_TitleName_Setting;

extern VControl UIMenuWndPlayback_TipsBarCtrl;//Panel type 

extern VControl UIMenuWndPlayback_ReturnTipsCtrl;//Static type 

extern VControl UIMenuWndPlayback_LDRTipsCtrl;//Panel type 

extern VControl UIMenuWndPlayback_LUDRTipsCtrl;//Panel type 

extern VControl UIMenuWndPlayback_LUDOKTipsCtrl;//Panel type 

extern VControl UIMenuWndPlayback_ItemCtrl;//Menu type 

typedef enum
{
UIMenuWndPlayback_Item_STRID_DELETE,
UIMenuWndPlayback_Item_STRID_PROTECT,
UIMenuWndPlayback_Item_STRID_SLIDE_SHOW,
UIMenuWndPlayback_Item_STRID_DPOF,
UIMenuWndPlayback_Item_MAX
}UIMenuWndPlayback_Item_Setting;

extern VControl UIMenuWndPlayback_PageNum_StaticCtrl;//Static type 

#endif
