//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayConfirmDelRes.c"
#include "UIMenuWndPlayConfirmDel.h"
//#NT#2009/09/14#Chris Chung -begin
#include "UIPlayObj.h"
#include "UIMenuWndPlayDel.h"
#include "UIFlowWndWrnMsg.h"
#include "UISystemStatusSettings.h"
#include "UIFlowWndWaitMoment.h"
#include "UISystemObj.h"
#include "UIMenuWndPlayback.h"
#include "KeyScanTsk.h"
//#NT#2009/09/14#Chris Chung -end

//---------------------UIMenuWndPlayConfirmDelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayConfirmDel)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayConfirmDelCtrl Event---------------------------
INT32 UIMenuWndPlayConfirmDel_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayConfirmDel)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayConfirmDel_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayConfirmDel_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayConfirmDel_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayConfirmDel_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayConfirmDel_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayConfirmDel_OnKeyMode)
EVENT_END

INT32 UIMenuWndPlayConfirmDel_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    UxMenu_SetData(&UIMenuWndPlayConfirmDel_MenuCtrl, MNU_CURITM, 0);

    if(paramNum > 0)
    {
        UxState_SetData(&UIMenuWndPlayConfirmDel_StatusTextCtrl,STATE_CURITEM,paramArray[0]);
    }
    else
    {
        UIPLAY_ERR(("UIMenuWndPlayConfirmDel_OnOpen: param error\r\n"));
    }

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    //#NT#2009/09/14#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    //#NT#2009/09/14#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/11/24#Chris Chung -begin
    if(paramNum > 0)
    {
        if(paramArray[0]==NVTRET_WAITMOMENT && (paramArray[1]==NVTRET_DELETEALL||paramArray[1]==NVTRET_DELETEONE))
        {
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_PLAYCURR,0);
            Ux_CloseWindow((VControl *)(&UIMenuWndPlayDelCtrl), 0);
        }
    }
    else
    {
        Ux_RedrawAllWind();
    }
    //#NT#2009/11/24#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/04#Chris Chung -begin
    Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);
    //#NT#2009/08/04#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/05#Chris Chung -begin
    Ux_CloseWindow((VControl *)(&UIMenuWndPlayConfirmDelCtrl), 0);
    //#NT#2009/08/05#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    //#NT#2009/09/14#Chris Chung -end
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayConfirmDel_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayConfirmDel_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_Menu)
CTRL_LIST_ITEM(UIMenuWndPlayConfirmDel_StatusText)
CTRL_LIST_END

//----------------------UIMenuWndPlayConfirmDel_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayConfirmDel_Panel)
EVENT_END

//----------------------UIMenuWndPlayConfirmDel_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayConfirmDel_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayConfirmDel_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayConfirmDel_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayConfirmDel_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayConfirmDel_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/10/27#Chris Chung -begin
    if(UxMenu_GetData(pCtrl,MNU_CURITM)==UIMenuWndPlayConfirmDel_Menu_STRID_OK)
    {
        if(UI_Validate_Storage(STORAGE_CHECK_LOCKED, NULL) == FALSE)
        {
            Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_CARD_LOCKED,FLOWWRNMSG_TIMER_2SEC);
            return NVTEVT_CONSUME;
        }

        switch(UxState_GetData(&UIMenuWndPlayConfirmDel_StatusTextCtrl,STATE_CURITEM))
        {
        case UIMenuWndPlayConfirmDel_StatusText_STRID_ERASE_THIS:

            if(UIPlay_GetData(PLAY_LOCKSTATUS))
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_FILE_PROTECTED,FLOWWRNMSG_TIMER_2SEC);
                return NVTEVT_CONSUME;
            }

            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_EXE_DEL,1,0);
            break;
        case UIMenuWndPlayConfirmDel_StatusText_STRID_ERASE_ALL:
            Ux_OpenWindow(&UIFlowWndWaitMomentCtrl,1,FLOWWAITMOMENT_MSG_PLEASEWAIT);
            Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_EXE_DEL,1,1);
            break;
        default:
            debug_err(("UIMenuWndPlayConfirmDel_Menu_OnKeyEnter: status text error\r\n"));
        }
    }
    else
    {
        Ux_CloseWindow((VControl *)(&UIMenuWndPlayDelCtrl), 0);
    }
    //#NT#2009/10/27#Chris Chung -end
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayConfirmDel_StatusTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayConfirmDel_StatusText)
EVENT_END

