//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlaybackRes.c"
#include "UIMenuWndPlayback.h"
//#NT#2009/10/05#Chris Chung -begin
#include "UIMenuWndSetup.h"
#include "UIMenuWndPlayDel.h"
#include "UIMenuWndPlayProtect.h"
#include "UIMenuWndPlayCopyToCard.h"
#include "UIMenuWndPlaySlideShow.h"
#include "UIMenuWndPlayDPOF.h"
#include "UIFlowWndPlay.h"
#include "UISystemObj.h"
#include "Utility.h"
#include "KeyScanTsk.h"
#include "UIPlayObj.h"
#include "UIFlowWndWrnMsg.h"
//#NT#2009/10/05#Chris Chung -end
//---------------------UIMenuWndPlaybackCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayback)
CTRL_LIST_ITEM(PlaybackMenuBackground)
CTRL_LIST_ITEM(UIMenuWndPlayback_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPlayback_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPlayback_Item)
CTRL_LIST_ITEM(UIMenuWndPlayback_PageNum_Static)
CTRL_LIST_END

//----------------------UIMenuWndPlaybackCtrl Event---------------------------
INT32 UIMenuWndPlayback_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayback)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayback_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayback_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayback_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayback_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPlayback_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayback_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayback_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayback_OnKeyMode)
EVENT_END

static char BottomBar_Buf[32];
static BOOL bUIMenuWndPlayback_ItemCtrl_rx_event = FALSE;
INT32 UIMenuWndPlayback_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    INT32 item,page,total_page;

    UxMenu_SetData(&UIMenuWndPlayback_ItemCtrl, MNU_CURITM, 0);

    bUIMenuWndPlayback_ItemCtrl_rx_event = FALSE;

    for (item=0;item<UIMenuWndPlayback_Item_MAX;item++) {
        UxMenu_SetItemData(&UIMenuWndPlayback_ItemCtrl,item,MNUITM_STATUS,(STATUS_DISABLE | STATUS_NORMAL_BIT));
    }

    UxCtrl_SetShow(&UIMenuWndPlayback_LDRTipsCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndPlayback_LUDRTipsCtrl,FALSE);
    UxCtrl_SetShow(&UIMenuWndPlayback_LUDOKTipsCtrl,FALSE);

    /* show page number */
    item = UxMenu_GetData(&UIMenuWndPlayback_ItemCtrl,MNU_CURITM);
    page = UxMenu_GetData(&UIMenuWndPlayback_ItemCtrl,MNU_PAGEITEM);
    item = (item / page) + 1;
    total_page = ((UIMenuWndPlayback_Item_MAX % page) == 0)?(UIMenuWndPlayback_Item_MAX / page):(UIMenuWndPlayback_Item_MAX / page + 1);
    snprintf((char *)BottomBar_Buf,32,"%d/%d",item,total_page);
    UxStatic_SetData(&UIMenuWndPlayback_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    //#NT#2009/09/14#Chris Chung -end

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    //#NT#2009/09/14#Chris Chung -end
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxState_SetData(&UIMenuWndPlayback_TitleNameCtrl,STATE_CURITEM,UIMenuWndPlayback_TitleName_STRID_PLAYBACK);

    if(bUIMenuWndPlayback_ItemCtrl_rx_event == FALSE)
    {
        UxCtrl_SetShow(&UIMenuWndPlayback_LDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDOKTipsCtrl,FALSE);
    }
    else
    {
        UxCtrl_SetShow(&UIMenuWndPlayback_LDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDOKTipsCtrl,FALSE);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(bUIMenuWndPlayback_ItemCtrl_rx_event == FALSE) {
        Ux_OpenWindow(&UIMenuWndSetupCtrl,1,UIMenuWndSetup_Title_Old_Status_ICON_MENU_PLAYBACK_OFF);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndPlayback_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (bUIMenuWndPlayback_ItemCtrl_rx_event == FALSE) {
        Ux_OpenWindow(&UIMenuWndSetupCtrl,1,UIMenuWndSetup_Title_Old_Status_ICON_MENU_PLAYBACK_OFF);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndPlayback_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/08/04#Chris Chung -begin
    Ux_CloseWindow(&UIMenuWndPlaybackCtrl,0);
    //#NT#2009/08/04#Chris Chung -end
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 item,page,total_page;

    if (bUIMenuWndPlayback_ItemCtrl_rx_event == FALSE) {
        bUIMenuWndPlayback_ItemCtrl_rx_event = TRUE;
        for (item=0;item<UIMenuWndPlayback_Item_MAX;item++) {
            UxMenu_SetItemData(&UIMenuWndPlayback_ItemCtrl,item,MNUITM_STATUS,STATUS_ENABLE);
        }
        UxMenu_SetData(&UIMenuWndPlayback_ItemCtrl,MNU_CURITM,0); // reset to 1st item

        item = UxMenu_GetData(&UIMenuWndPlayback_ItemCtrl,MNU_CURITM);
        page = UxMenu_GetData(&UIMenuWndPlayback_ItemCtrl,MNU_PAGEITEM);

        debug_msg("UIMenuWndPlayback_OnKeyDown item = %d, page = %d\n\r",item, page);
        item = (item / page)+1;
        total_page = ((UIMenuWndPlayback_Item_MAX % page) == 0)?(UIMenuWndPlayback_Item_MAX / page):(UIMenuWndPlayback_Item_MAX / page + 1);
        //total_page = (UIMenuWndSetup_Setup_Menu_MAX / page);
        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        debug_msg("%s\n\r",BottomBar_Buf);
        UxStatic_SetData(&UIMenuWndPlayback_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        UxCtrl_SetShow(&UIMenuWndPlayback_LDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDOKTipsCtrl,FALSE);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndPlayback_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    //#NT#2009/09/14#Chris Chung -end
    return NVTEVT_CONSUME;
}
//---------------------PlaybackMenuBackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(PlaybackMenuBackground)
CTRL_LIST_END

//----------------------PlaybackMenuBackgroundCtrl Event---------------------------
EVENT_BEGIN(PlaybackMenuBackground)
EVENT_END

//---------------------UIMenuWndPlayback_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayback_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPlayback_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndPlayback_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_TitleBar)
EVENT_END

//----------------------UIMenuWndPlayback_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_TitleName)
EVENT_END

//---------------------UIMenuWndPlayback_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayback_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPlayback_ReturnTips)
CTRL_LIST_ITEM(UIMenuWndPlayback_LDRTips)
CTRL_LIST_ITEM(UIMenuWndPlayback_LUDRTips)
CTRL_LIST_ITEM(UIMenuWndPlayback_LUDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndPlayback_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_TipsBar)
EVENT_END

//----------------------UIMenuWndPlayback_ReturnTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_ReturnTips)
EVENT_END

//---------------------UIMenuWndPlayback_LDRTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayback_LDRTips)
CTRL_LIST_END

//----------------------UIMenuWndPlayback_LDRTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_LDRTips)
EVENT_END

//---------------------UIMenuWndPlayback_LUDRTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayback_LUDRTips)
CTRL_LIST_END

//----------------------UIMenuWndPlayback_LUDRTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_LUDRTips)
EVENT_END

//---------------------UIMenuWndPlayback_LUDOKTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayback_LUDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndPlayback_LUDOKTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_LUDOKTips)
EVENT_END

//----------------------UIMenuWndPlayback_ItemCtrl Event---------------------------
INT32 UIMenuWndPlayback_Item_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_Item_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_Item_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_Item_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayback_Item_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayback_Item)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayback_Item_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayback_Item_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayback_Item_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPlayback_Item_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayback_Item_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayback_Item_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    INT32   page,total_page;
    if(bUIMenuWndPlayback_ItemCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        if(item == 0)
        {
            item = UIMenuWndPlayback_Item_MAX - 1;
            item = (item/ page) + 1;
        }
        else
            item = ((item-1) / page) + 1;
        total_page = ((UIMenuWndPlayback_Item_MAX % page) == 0)?(UIMenuWndPlayback_Item_MAX / page):(UIMenuWndPlayback_Item_MAX / page + 1);
        //total_page = (UIMenuWndSetup_Setup_Menu_MAX / page);
        debug_msg("UIMenuWndPlayback_Item_OnKeyUp item = %d, page = %d\n\r",item, page);

        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        UxStatic_SetData(&UIMenuWndPlayback_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_Item_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    INT32   page,total_page;
    if(bUIMenuWndPlayback_ItemCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        if(item == (UIMenuWndPlayback_Item_MAX - 1))
        {
            item = 0;
            item = (item/ page) + 1;
        }
        else
            item = ((item+1) / page) + 1;
        total_page = ((UIMenuWndPlayback_Item_MAX % page) == 0)?(UIMenuWndPlayback_Item_MAX / page):(UIMenuWndPlayback_Item_MAX / page + 1);
        //total_page = (UIMenuWndSetup_Setup_Menu_MAX / page);
        debug_msg("UIMenuWndPlayback_Item_OnKeyDown item = %d, page = %d\n\r",item, page);

        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        UxStatic_SetData(&UIMenuWndPlayback_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_Item_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 item;

    if (bUIMenuWndPlayback_ItemCtrl_rx_event == TRUE) {
        for (item=0;item<UIMenuWndPlayback_Item_MAX;item++) {
            UxMenu_SetItemData(&UIMenuWndPlayback_ItemCtrl,item,MNUITM_STATUS,(STATUS_DISABLE|STATUS_NORMAL_BIT));
        }
        UxMenu_SetData(&UIMenuWndPlayback_ItemCtrl,MNU_CURITM,0); // reset to 1st item

        UxCtrl_SetShow(&UIMenuWndPlayback_LDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDOKTipsCtrl,FALSE);
    }
    bUIMenuWndPlayback_ItemCtrl_rx_event = FALSE;
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_Item_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    extern  void UIFlowWndPlay_OpenNoImageWnd(FLOWWRNMSG_TIMER timer_keep);

    if (bUIMenuWndPlayback_ItemCtrl_rx_event == TRUE) {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        UxState_SetData(&UIMenuWndPlayback_TitleNameCtrl,STATE_CURITEM,(item + 1));
        UxCtrl_SetDirty(&UIMenuWndPlayback_TitleNameCtrl, TRUE);

        UxCtrl_SetShow(&UIMenuWndPlayback_LDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPlayback_LUDOKTipsCtrl,TRUE);
        Ux_Redraw();
        switch (item)
        {
            case UIMenuWndPlayback_Item_STRID_DELETE:
                if(UIPlay_GetData(PLAY_FILENUM)==0)
                    UIFlowWndPlay_OpenNoImageWnd(FLOWWRNMSG_TIMER_2SEC);
                else
                    Ux_OpenWindow(&UIMenuWndPlayDelCtrl,0);
                break;

            case UIMenuWndPlayback_Item_STRID_PROTECT:
                if(UIPlay_GetData(PLAY_FILENUM)==0)
                    UIFlowWndPlay_OpenNoImageWnd(FLOWWRNMSG_TIMER_2SEC);
                else
                    Ux_OpenWindow(&UIMenuWndPlayProtectCtrl,0);
                break;

            case UIMenuWndPlayback_Item_STRID_SLIDE_SHOW:
                if(UIPlay_GetData(PLAY_FILENUM)==0)
                    UIFlowWndPlay_OpenNoImageWnd(FLOWWRNMSG_TIMER_2SEC);
                //else if(UIPlay_GetData(PLAY_CURRMODE)!=PLAYMODE_PRIMARY)
                //    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NOT_JPEG,FLOWWRNMSG_TIMER_2SEC);
                else
                    Ux_OpenWindow(&UIMenuWndPlaySlideShowCtrl,0);
                break;

            #if 0
            case UIMenuWndPlayback_Item_STRID_COPY_TO_CARD:
                Ux_OpenWindow(&UIMenuWndPlayCopyToCardCtrl,0);
                break;
            #endif

            case UIMenuWndPlayback_Item_STRID_DPOF:
                if(UIPlay_GetData(PLAY_FILENUM)==0)
                    UIFlowWndPlay_OpenNoImageWnd(FLOWWRNMSG_TIMER_2SEC);
                else if(UIPlay_GetData(PLAY_CURRMODE)!=PLAYMODE_PRIMARY)
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NOT_JPEG,FLOWWRNMSG_TIMER_2SEC);
                else
                    Ux_OpenWindow(&UIMenuWndPlayDPOFCtrl,0);
                break;
        }
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayback_Item_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2009/09/14#Chris Chung -begin
    UIMenuWndPlayback_Item_OnKeyRight(pCtrl, paramNum, paramArray);
    //#NT#2009/09/14#Chris Chung -end
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayback_PageNum_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayback_PageNum_Static)
EVENT_END

