//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndMovieVideoRes.c"
#include "UIMenuWndMovieVideo.h"
//---------------------UIMenuWndMovieVideoCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieVideo)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_End_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_Video_Menu)
CTRL_LIST_END

//----------------------UIMenuWndMovieVideoCtrl Event---------------------------
INT32 UIMenuWndMovieVideo_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieVideo)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndMovieVideo_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndMovieVideo_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndMovieVideo_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndMovieVideo_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndMovieVideo_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndMovieVideo_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndMovieVideo_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndMovieVideo_OnKeyMode)
EVENT_END

INT32 UIMenuWndMovieVideo_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndMovieVideo_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieVideo_Panel)
CTRL_LIST_END

//----------------------UIMenuWndMovieVideo_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieVideo_Panel)
EVENT_END

//---------------------UIMenuWndMovieVideo_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieVideo_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_Title_Mode_Status)
CTRL_LIST_END

//----------------------UIMenuWndMovieVideo_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieVideo_Title_Panel)
EVENT_END

//----------------------UIMenuWndMovieVideo_Title_Mode_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieVideo_Title_Mode_Status)
EVENT_END

//---------------------UIMenuWndMovieVideo_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieVideo_End_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_Return_Static)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_Dir_Panel)
CTRL_LIST_ITEM(UIMenuWndMovieVideo_PageNum_Static)
CTRL_LIST_END

//----------------------UIMenuWndMovieVideo_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieVideo_End_Panel)
EVENT_END

//----------------------UIMenuWndMovieVideo_Return_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieVideo_Return_Static)
EVENT_END

//---------------------UIMenuWndMovieVideo_Dir_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndMovieVideo_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndMovieVideo_Dir_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieVideo_Dir_Panel)
EVENT_END

//----------------------UIMenuWndMovieVideo_PageNum_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndMovieVideo_PageNum_Static)
EVENT_END

//----------------------UIMenuWndMovieVideo_Video_MenuCtrl Event---------------------------
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndMovieVideo_Video_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndMovieVideo_Video_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndMovieVideo_Video_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndMovieVideo_Video_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndMovieVideo_Video_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndMovieVideo_Video_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndMovieVideo_Video_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
