//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEWB_H
#define UIMENUWNDMOVIEWB_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieWBCtrl;//Panel type 

extern VControl UIMenuWndMovieWB_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieWB_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieWB_Menu_STRID_AUTO,
UIMenuWndMovieWB_Menu_STRID_WB_DAY,
UIMenuWndMovieWB_Menu_STRID_WB_CLOUDY,
UIMenuWndMovieWB_Menu_STRID_WB_TUNGSTEN,
UIMenuWndMovieWB_Menu_STRID_WB_FLUORESCENT,
UIMenuWndMovieWB_Menu_MAX
}UIMenuWndMovieWB_Menu_Setting;

#endif
