//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEGSENSOR_H
#define UIMENUWNDMOVIEGSENSOR_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieGsensorCtrl;//Panel type 

extern VControl UIMenuWndMovieGsensor_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieGsensor_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieGsensor_Menu_STRID_OFF,
UIMenuWndMovieGsensor_Menu_STRID_LOW,
UIMenuWndMovieGsensor_Menu_STRID_MED,
UIMenuWndMovieGsensor_Menu_STRID_HIGH,
UIMenuWndMovieGsensor_Menu_MAX
}UIMenuWndMovieGsensor_Menu_Setting;

#endif
