//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDMOVIEVIDEO_H
#define UIMENUWNDMOVIEVIDEO_H

#include "UIFramework.h"

extern VControl UIMenuWndMovieVideoCtrl;//Panel type 

extern VControl UIMenuWndMovieVideo_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieVideo_Title_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieVideo_Title_Mode_StatusCtrl;//Status type 

typedef enum
{
UIMenuWndMovieVideo_Title_Mode_Status_STRID_VIDEO,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_RESOLUTION,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_CYCLIC_REC,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_MOTION_DET,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_DATE_STAMP,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_RECORD_AUDIO,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_EV,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_WB,
UIMenuWndMovieVideo_Title_Mode_Status_STRID_GSENSOR_SENSITIVITY,
UIMenuWndMovieVideo_Title_Mode_Status_MAX
}UIMenuWndMovieVideo_Title_Mode_Status_Setting;

extern VControl UIMenuWndMovieVideo_End_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieVideo_Return_StaticCtrl;//Static type 

extern VControl UIMenuWndMovieVideo_Dir_PanelCtrl;//Panel type 

extern VControl UIMenuWndMovieVideo_PageNum_StaticCtrl;//Static type 

extern VControl UIMenuWndMovieVideo_Video_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndMovieVideo_Video_Menu_STRID_RESOLUTION,
UIMenuWndMovieVideo_Video_Menu_STRID_CYCLIC_REC,
UIMenuWndMovieVideo_Video_Menu_STRID_MOTION_DET,
UIMenuWndMovieVideo_Video_Menu_STRID_DATE_STAMP,
UIMenuWndMovieVideo_Video_Menu_STRID_RECORD_AUDIO,
UIMenuWndMovieVideo_Video_Menu_STRID_EV,
UIMenuWndMovieVideo_Video_Menu_STRID_WB,
UIMenuWndMovieVideo_Video_Menu_STRID_GSENSOR_SENSITIVITY,
UIMenuWndMovieVideo_Video_Menu_MAX
}UIMenuWndMovieVideo_Video_Menu_Setting;

//---------------------UIMenuWndMovieVideoCtrl User Export---------------------------
#endif
