//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOCAPTUREMODE_H
#define UIMENUWNDPHOTOCAPTUREMODE_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoCaptureModeCtrl;//Panel type 

extern VControl UIMenuWndPhotoCaptureMode_PanelCtrl;//Panel type 

extern VControl UIMenuWndPhotoCaptureMode_MenuCtrl;//Menu type 

typedef enum
{
UIMenuWndPhotoCaptureMode_Menu_STRID_CAP_SINGLE,
UIMenuWndPhotoCaptureMode_Menu_STRID_CAP_TIMER2S,
UIMenuWndPhotoCaptureMode_Menu_STRID_CAP_TIMER5S,
UIMenuWndPhotoCaptureMode_Menu_STRID_CAP_TIMER10S,
UIMenuWndPhotoCaptureMode_Menu_STRID_CAP_BURST,
UIMenuWndPhotoCaptureMode_Menu_MAX
}UIMenuWndPhotoCaptureMode_Menu_Setting;

#endif
