//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoStillRes.c"
#include "UIMenuWndPhotoStill.h"
#include "UIMenuWndPhotoCaptureMode.h"
#include "UIMenuWndPhotoResolution.h"
#include "UIMenuWndPhotoCompression.h"
#include "UIMenuWndPhotoScene.h"
#include "UIMenuWndPhotoWB.h"
#include "UIMenuWndPhotoISO.h"
#include "UIMenuWndPhotoColor.h"
#include "UIMenuWndPhotoSharpness.h"
#include "UIMenuWndPhotoFD.h"
#include "UIMenuWndPhotoAntiSha.h"
#include "UIMenuWndPhotoQuickView.h"
#include "UIMenuWndPhotoDateStamp.h"
#include "UIMenuWndSetup.h"
#include "UISystemObj.h"
#include "KeyScanTsk.h"
#include "Debug.h"
//---------------------UIMenuWndPhotoStillCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill)
CTRL_LIST_ITEM(PhotoMenuBackground)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_Item)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_PageNum_Static)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStillCtrl Event---------------------------
INT32 UIMenuWndPhotoStill_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoStill)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoStill_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoStill_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPhotoStill_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoStill_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPhotoStill_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPhotoStill_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoStill_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPhotoStill_OnKeyMode)
EVENT_END

static UINT8 BottomBar_Buf[20];
static BOOL bUIMenuWndPhotoStill_ItemCtrl_rx_event = FALSE;
INT32 UIMenuWndPhotoStill_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 item,page,total_page;

    bUIMenuWndPhotoStill_ItemCtrl_rx_event = FALSE;
    UxState_SetData(&UIMenuWndPhotoStill_TitleNameCtrl,STATE_CURITEM,UIMenuWndPhotoStill_TitleName_STRID_STILL);

    for(item = 0;item < UIMenuWndPhotoStill_Item_MAX;item++)
        UxMenu_SetItemData(&UIMenuWndPhotoStill_ItemCtrl,item,MNUITM_STATUS,(STATUS_DISABLE | STATUS_NORMAL_BIT));

    UxCtrl_SetShow(&UIMenuWndPhotoStill_LDRTipsCtrl,TRUE);
    UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDRTipsCtrl,FALSE);
    UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDOKTipsCtrl,FALSE);

    UxMenu_SetData(&UIMenuWndPhotoStill_ItemCtrl, MNU_CURITM, 0);


    item = UxMenu_GetData(&UIMenuWndPhotoStill_ItemCtrl,MNU_CURITM);
    page = UxMenu_GetData(&UIMenuWndPhotoStill_ItemCtrl,MNU_PAGEITEM);
    item = (item / page)+1;
    total_page = ((UIMenuWndPhotoStill_Item_MAX % page) == 0)?(UIMenuWndPhotoStill_Item_MAX / page):(UIMenuWndPhotoStill_Item_MAX / page + 1);
    sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
    debug_ind(("%s\n\r",BottomBar_Buf));
    UxStatic_SetData(&UIMenuWndPhotoStill_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UxState_SetData(&UIMenuWndPhotoStill_TitleNameCtrl,STATE_CURITEM,UIMenuWndPhotoStill_TitleName_STRID_STILL);

    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == FALSE)
    {
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDOKTipsCtrl,FALSE);
    }
    else
    {
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDOKTipsCtrl,FALSE);
    }
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == FALSE)
    {
        Ux_OpenWindow(&UIMenuWndSetupCtrl,0);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndPhotoStill_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == FALSE)
    {
        Ux_OpenWindow(&UIMenuWndSetupCtrl,0);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndPhotoStill_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(pCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32 item,page,total_page;
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == FALSE)
    {
        bUIMenuWndPhotoStill_ItemCtrl_rx_event = TRUE;
        for(item = 0;item < UIMenuWndPhotoStill_Item_MAX;item++)
        {
            UxMenu_SetItemData(&UIMenuWndPhotoStill_ItemCtrl,item,MNUITM_STATUS,(STATUS_ENABLE));
        }
        UxMenu_SetData(&UIMenuWndPhotoStill_ItemCtrl,MNU_CURITM,0); // reset to 1st item
        item = UxMenu_GetData(&UIMenuWndPhotoStill_ItemCtrl,MNU_CURITM);
        page = UxMenu_GetData(&UIMenuWndPhotoStill_ItemCtrl,MNU_PAGEITEM);

        debug_ind(("UIMenuWndPhotoStill_OnKeyZoomout item = %d, page = %d\n\r",item, page));
        item = (item / page) + 1;
        total_page = ((UIMenuWndPhotoStill_Item_MAX % page) == 0)?(UIMenuWndPhotoStill_Item_MAX / page):(UIMenuWndPhotoStill_Item_MAX / page + 1);

        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        debug_ind(("%s\n\r",BottomBar_Buf));
        UxStatic_SetData(&UIMenuWndPhotoStill_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        UxCtrl_SetShow(&UIMenuWndPhotoStill_LDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDOKTipsCtrl,FALSE);
        return NVTEVT_CONSUME;
    }
    return NVTEVT_PASS;
}
INT32 UIMenuWndPhotoStill_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//---------------------PhotoMenuBackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(PhotoMenuBackground)
CTRL_LIST_END

//----------------------PhotoMenuBackgroundCtrl Event---------------------------
EVENT_BEGIN(PhotoMenuBackground)
EVENT_END

//---------------------UIMenuWndPhotoStill_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_TitleBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_TitleBar)
EVENT_END

//----------------------UIMenuWndPhotoStill_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_TitleName)
EVENT_END

//---------------------UIMenuWndPhotoStill_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_TipsBar)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_ReturnTips)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_LDRTips)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_LUDRTips)
CTRL_LIST_ITEM(UIMenuWndPhotoStill_LUDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_TipsBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_TipsBar)
EVENT_END

//----------------------UIMenuWndPhotoStill_ReturnTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_ReturnTips)
EVENT_END

//---------------------UIMenuWndPhotoStill_LDRTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_LDRTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_LDRTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_LDRTips)
EVENT_END

//---------------------UIMenuWndPhotoStill_LUDRTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_LUDRTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_LUDRTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_LUDRTips)
EVENT_END

//---------------------UIMenuWndPhotoStill_LUDOKTipsCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoStill_LUDOKTips)
CTRL_LIST_END

//----------------------UIMenuWndPhotoStill_LUDOKTipsCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_LUDOKTips)
EVENT_END

//----------------------UIMenuWndPhotoStill_ItemCtrl Event---------------------------
INT32 UIMenuWndPhotoStill_Item_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoStill_Item_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoStill_Item)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoStill_Item_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoStill_Item_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoStill_Item_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPhotoStill_Item_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoStill_Item_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoStill_Item_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    INT32   page,total_page;
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        if(item == 0)
        {
            item = UIMenuWndPhotoStill_Item_MAX - 1;
            item = (item / page) + 1;
        }
        else
            item = ((item - 1) / page) + 1;
        total_page = ((UIMenuWndPhotoStill_Item_MAX % page) == 0)?(UIMenuWndPhotoStill_Item_MAX / page):(UIMenuWndPhotoStill_Item_MAX / page + 1);
        debug_ind(("UIMenuWndPhotoStill_Item_OnKeyZoomin item = %d, page = %d\n\r",item, page));

        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        UxStatic_SetData(&UIMenuWndPhotoStill_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item;
    INT32   page,total_page;
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        if(item == (UIMenuWndPhotoStill_Item_MAX - 1))
        {
            item = 0;
            item = (item / page) + 1;
        }
        else
            item = ((item + 1) / page) + 1;
        total_page = ((UIMenuWndPhotoStill_Item_MAX % page) == 0)?(UIMenuWndPhotoStill_Item_MAX / page):(UIMenuWndPhotoStill_Item_MAX / page + 1);
        debug_ind(("UIMenuWndPhotoStill_Item_OnKeyZoomout item = %d, page = %d\n\r",item, page));

        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        UxStatic_SetData(&UIMenuWndPhotoStill_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item,page,total_page;
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == TRUE)
    {
        for(item = 0;item < UIMenuWndPhotoStill_Item_MAX;item++)
        {
            UxMenu_SetItemData(&UIMenuWndPhotoStill_ItemCtrl,item,MNUITM_STATUS,(STATUS_DISABLE | STATUS_NORMAL_BIT));
        }
        UxMenu_SetData(pCtrl,MNU_CURITM,0);

        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        page = UxMenu_GetData(pCtrl,MNU_PAGEITEM);
        item = (item / page) + 1;
        total_page = ((UIMenuWndPhotoStill_Item_MAX % page) == 0)?(UIMenuWndPhotoStill_Item_MAX / page):(UIMenuWndPhotoStill_Item_MAX / page + 1);
        debug_ind(("UIMenuWndPhotoStill_Item_OnKeyLeft item = %d, page = %d\n\r",item, page));
        sprintf((char *)BottomBar_Buf,"%d/%d",item,total_page);
        debug_ind(("%s\n\r",BottomBar_Buf));
        UxStatic_SetData(&UIMenuWndPhotoStill_PageNum_StaticCtrl,STATIC_VALUE,Txt_Pointer(BottomBar_Buf));

        UxCtrl_SetShow(&UIMenuWndPhotoStill_LDRTipsCtrl,TRUE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDOKTipsCtrl,FALSE);
    }
    bUIMenuWndPhotoStill_ItemCtrl_rx_event = FALSE;
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  item;
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        UxState_SetData(&UIMenuWndPhotoStill_TitleNameCtrl,STATE_CURITEM,(item + 1));
        UxCtrl_SetDirty(&UIMenuWndPhotoStill_TitleNameCtrl, TRUE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDOKTipsCtrl,TRUE);
        switch (item)
        {
        case UIMenuWndPhotoStill_Item_STRID_CAP_MODE:
            Ux_OpenWindow(&UIMenuWndPhotoCaptureModeCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_RESOLUTION:
            Ux_OpenWindow(&UIMenuWndPhotoResCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_QUALITY:
            Ux_OpenWindow(&UIMenuWndPhotoCompressionCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_SHARPNESS:
            Ux_OpenWindow(&UIMenuWndPhotoSharpnessCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_WB:
            Ux_OpenWindow(&UIMenuWndPhotoWBCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_COLOR:
            Ux_OpenWindow(&UIMenuWndPhotoColorCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_ISO:
            Ux_OpenWindow(&UIMenuWndPhotoISOCtrl,0);
            break;
//#NT#2010/11/29#philex Lin - begin
// Disable Scene mode selection
#if 0
        case UIMenuWndPhotoStill_Item_STRID_SCENESETTING:
            Ux_OpenWindow(&UIMenuWndPhotoSceneCtrl,0);
            break;
#endif
//#NT#2010/11/29#philex Lin - end
        case UIMenuWndPhotoStill_Item_STRID_FACE_DET:
            Ux_OpenWindow(&UIMenuWndPhotoFDCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_ANTI_SHAKING:
            Ux_OpenWindow(&UIMenuWndPhotoAntiShaCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_QUICK_VIEW:
            Ux_OpenWindow(&UIMenuWndPhotoQuickViewCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_DATE_STAMP:
            Ux_OpenWindow(&UIMenuWndPhotoDateStampCtrl,0);
            break;
        default:
            debug_err(("UIMenuWndPhotoStill: Unknown item 0x%x\r\n", item));
            break;
        }
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoStill_Item_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  item;
    if(bUIMenuWndPhotoStill_ItemCtrl_rx_event == TRUE)
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        UxState_SetData(&UIMenuWndPhotoStill_TitleNameCtrl,STATE_CURITEM,(item + 1));
        UxCtrl_SetDirty(&UIMenuWndPhotoStill_TitleNameCtrl, TRUE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDRTipsCtrl,FALSE);
        UxCtrl_SetShow(&UIMenuWndPhotoStill_LUDOKTipsCtrl,TRUE);
        switch (item)
        {
        case UIMenuWndPhotoStill_Item_STRID_CAP_MODE:
            Ux_OpenWindow(&UIMenuWndPhotoCaptureModeCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_RESOLUTION:
            Ux_OpenWindow(&UIMenuWndPhotoResCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_QUALITY:
            Ux_OpenWindow(&UIMenuWndPhotoCompressionCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_SHARPNESS:
            Ux_OpenWindow(&UIMenuWndPhotoSharpnessCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_WB:
            Ux_OpenWindow(&UIMenuWndPhotoWBCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_COLOR:
            Ux_OpenWindow(&UIMenuWndPhotoColorCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_ISO:
            Ux_OpenWindow(&UIMenuWndPhotoISOCtrl,0);
            break;
//#NT#2010/11/29#philex Lin - begin
// Disable Scene mode selection
#if 0
        case UIMenuWndPhotoStill_Item_STRID_SCENESETTING:
            Ux_OpenWindow(&UIMenuWndPhotoSceneCtrl,0);
            break;
#endif
//#NT#2010/11/29#philex Lin - end
        case UIMenuWndPhotoStill_Item_STRID_FACE_DET:
            Ux_OpenWindow(&UIMenuWndPhotoFDCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_ANTI_SHAKING:
            Ux_OpenWindow(&UIMenuWndPhotoAntiShaCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_QUICK_VIEW:
            Ux_OpenWindow(&UIMenuWndPhotoQuickViewCtrl,0);
            break;
        case UIMenuWndPhotoStill_Item_STRID_DATE_STAMP:
            Ux_OpenWindow(&UIMenuWndPhotoDateStampCtrl,0);
            break;
        default:
            debug_err(("UIMenuWndPhotoStill: Unknown item 0x%x\r\n", item));
            break;
        }
    }
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPhotoStill_PageNum_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoStill_PageNum_Static)
EVENT_END

