//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoQuickSettingRes.c"
#include "UIMenuWndPhotoQuickSetting.h"
#include "UIMenuPhotoSettings.h"
#include "UIPhotoObj.h"
#include "UISystemObj.h"
#include "KeyScanTsk.h"
#include "PrimaryTsk.h"


//---------------------UIMenuWndPhotoQuickSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoQuickSetting)
CTRL_LIST_ITEM(UIMenuWndPhotoQS_End_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPhotoQuickSettingCtrl Event---------------------------
INT32 UIMenuWndPhotoQuickSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuickSetting_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuickSetting_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQuickSetting_OnKeyMode(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoQuickSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoQuickSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoQuickSetting_OnClose)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoQuickSetting_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPhotoQuickSetting_OnKeyMode)
EVENT_END

INT32 UIMenuWndPhotoQuickSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   downmenu_ev_index;

    switch(Get_EVIndex())
    {
        case EV_N20:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_M2P0;
            break;
        case EV_N16:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P6;
            break;
        case EV_N13:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P3;
            break;
        case EV_N10:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P0;
            break;
        case EV_N06:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_M0P6;
            break;
        case EV_N03:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_M0P3;
            break;
        case EV_00:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P0;
            break;
        case EV_P03:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P3;
            break;
        case EV_P06:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P6;
            break;
        case EV_P10:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P0;
            break;
        case EV_P13:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P3;
            break;
        case EV_P16:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P6;
            break;
        case EV_P20:
            downmenu_ev_index = UIMenuWndPhotoQS_EV_Menu_ICON_EV_P2P0;
            break;
    }

    UxMenu_SetData(&UIMenuWndPhotoQS_EV_MenuCtrl,MNU_CURITM,downmenu_ev_index);
    UxCtrl_SetShow(&UIMenuWndPhotoQS_EV_MenuCtrl,TRUE);

    /* Set key press/release/continue mask */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQuickSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    /* Reset key press/release/continue mask to default */
    Ux_FlushEvent();
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_RELEASE, FLGKEY_KEY_REL_MASK_DEFAULT);
    KeyScan_SetKeyMask(KEYSCAN_KEYMODE_CONTINUE, FLGKEY_KEY_CONT_MASK_DEFAULT);
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQuickSetting_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_CloseWindow(pCtrl,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQuickSetting_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(&UISystemObjCtrl,NVTEVT_FORCETO_LIVEVIEW_MODE,0);
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoQS_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoQS_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPhotoQS_EV_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoQS_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoQS_End_Panel)
EVENT_END

//----------------------UIMenuWndPhotoQS_EV_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoQS_EV_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoQS_EV_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoQS_EV_Menu)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPhotoQS_EV_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoQS_EV_Menu_OnKeyLeft)
EVENT_END

INT32 UIMenuWndPhotoQS_EV_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item,ae_index;
    if(UxCtrl_IsShow(pCtrl))
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        if(item > 0)
            item = (item-1) % UIMenuWndPhotoQS_EV_Menu_MAX;
        else
        {
            item = UxMenu_GetData(pCtrl,MNU_TOTITM) - 1;
        }

        Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
        switch(UxMenu_GetData(pCtrl,MNU_CURITM))
        {
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M2P0:
            ae_index = EV_N20;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P6:
            ae_index = EV_N16;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P3:
            ae_index = EV_N13;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P0:
            ae_index = EV_N10;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M0P6:
            ae_index = EV_N06;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M0P3:
            ae_index = EV_N03;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P0:
            ae_index = EV_00;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P3:
            ae_index = EV_P03;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P6:
            ae_index = EV_P06;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P0:
            ae_index = EV_P10;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P3:
            ae_index = EV_P13;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P6:
            ae_index = EV_P16;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P2P0:
            ae_index = EV_P20;
            break;
        default:
            ae_index = EV_00;
            break;
        }
        Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_EXE_EV,2,ae_index,TRUE);
    }
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoQS_EV_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    INT32   item,ae_index;
    if(UxCtrl_IsShow(pCtrl))
    {
        item = UxMenu_GetData(pCtrl,MNU_CURITM);
        item = (item+1) % UIMenuWndPhotoQS_EV_Menu_MAX;

        Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
        switch(UxMenu_GetData(pCtrl,MNU_CURITM))
        {
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M2P0:
            ae_index = EV_N20;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P6:
            ae_index = EV_N16;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P3:
            ae_index = EV_N13;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M1P0:
            ae_index = EV_N10;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M0P6:
            ae_index = EV_N06;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_M0P3:
            ae_index = EV_N03;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P0:
            ae_index = EV_00;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P3:
            ae_index = EV_P03;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P0P6:
            ae_index = EV_P06;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P0:
            ae_index = EV_P10;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P3:
            ae_index = EV_P13;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P1P6:
            ae_index = EV_P16;
            break;
        case UIMenuWndPhotoQS_EV_Menu_ICON_EV_P2P0:
            ae_index = EV_P20;
            break;
        default:
            ae_index = EV_00;
            break;
        }
        Ux_SendEvent(&UIPhotoObjCtrl,NVTEVT_EXE_EV,2,ae_index,TRUE);
    }
    return NVTEVT_CONSUME;
}
